### ISSUE TITLE
Company page- Sorting issue in auto billing contracts.- vinod sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1013]
**Describe the bug**
Sorting issue in auto billing contracts. when i provide billing date it does not get displayed as per date

**Post**
https://community.easycloudbooks.com/t/Questions%20or%20Bugs/2becdae9-ef65-4921-9b56-9da5714ff423

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/166182790-3a3145bf-6011-4a55-a29c-f16497b97635.png)

**Comment by dharmendraecb** [comment]
Company Settings like 01-04-2022

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/166422114-177562c4-c0ed-447e-b8fc-d320b6582857.png)

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/4d6107a3-a498-5a07-92b6-f7bd31118733
