### ISSUE TITLE
Company contract list - Company contractList --> change to "Recurring Fees Contract" -Vinod sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1014]
**Describe the bug**
Company contract[List](https://ac-74.s1.easycloudbooks.com/user/Company/list) --> change to "Recurring Fees Contract"

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/166183581-ec8ba96e-74bf-4526-ab54-2b9ebabf881a.png)

**Comment by dharmendraecb** [comment]
Possible View
![image](https://user-images.githubusercontent.com/46588108/166196823-1f207343-a8fe-4146-b0ee-7515403728cc.png)
