### ISSUE TITLE
Contact page- When adding tag there is ui issue in  add tag page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1022]
**Describe the bug**
- when adding multiple character tag then there is some UI issue in display that tag

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/166187050-286ec546-e4af-4a07-be48-640eea282eda.png)

**Comment by dharmendraecb** [comment]
tagify plugin issue size
