### ISSUE TITLE
Contact page - tags are not display correctly on mobile view 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1023]
**Describe the bug**
- Tags are going outside when we see tags in mobile view
- give some space to bottom
- email id is not display correctly
- Transaction is going out in ipad view

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/166188197-0a97478e-1fc0-4b19-9382-699c4352a3fe.png)
![image](https://user-images.githubusercontent.com/46588125/166188894-5533e2dd-3318-4976-9c0e-8b14aedfb874.png)
![image](https://user-images.githubusercontent.com/46588125/166188974-90920292-1e73-4f96-88bb-f6018c8b22db.png)
![image](https://user-images.githubusercontent.com/46588125/166207138-be5a5c82-c3f6-4938-8783-ed204c31c25a.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/166420693-0c23a36a-31c9-4050-a932-8ec44dda8493.png)
![image](https://user-images.githubusercontent.com/46588125/166420918-7009ba1c-7719-4c71-b11f-50f742bb257a.png)
![image](https://user-images.githubusercontent.com/46588125/166420989-1ac24f94-8d82-40f3-8249-692e33ed131f.png)

**Comment by dharmendraecb** [comment]
Tag Ui Is Rightn responsive
