### ISSUE TITLE
Contact page- hover not working in advance viewer  when hover on menu

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1026]
**Describe the bug**
- when hover on icon there is not any pointer cursor and change color
- when we hover on menu also change color of icon with name

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/166191961-82c8e457-e2d3-4ce5-9318-b757bf686de1.png)

**Comment by dharmendraecb** [comment]
Not Ui Issue  theme Provider Template
