### ISSUE TITLE
Billing- Tax not calculated while pay

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#104]
### Billing- Tax not calculated while pay
![2020-09-22_22-49-34](https://user-images.githubusercontent.com/46882964/93915871-47002d80-fd26-11ea-981a-48850a2878bc.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/95423417-abde9900-095e-11eb-8635-1e4042e22a95.png)

**Comment by ajayrajecb** [comment]
![2021-02-02_15-53-19](https://user-images.githubusercontent.com/46882964/106587183-51052900-656f-11eb-9fe1-d199a604c6ec.png)
