### ISSUE TITLE
Company page -  combine position and contacts in one page - Vinod Sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1042]
**Describe the bug**
- combine position and contacts in single page as contacts 

**Post**
https://community.easycloudbooks.com/t/Questions%20or%20Bugs/c2bc8381-bb0e-4368-b58b-613ec7f4eb05

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/166636182-f1990875-9614-42ae-ae59-c25a2a9fc3e3.png)

**Comment by mitulpanch** [comment]
not posible
