### ISSUE TITLE
Project page - by default date selection is wrong when change project status by Vinod sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1047]
**Describe the bug**
- Max Note Span is 15 days in service page 
- when change project status in project page default date selection is showing according to 7 days not 15 days

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/166905149-9f4aa42d-410b-439e-a992-ced219f2a769.png)
![image](https://user-images.githubusercontent.com/46588125/166905184-d3722f2e-8b00-40a2-bb1d-78533f29f9c1.png)

**Comment by Avinash-ecb** [comment]
Default 7 days selection is only provided by @dharmendraecb

**Comment by mitulpanch** [comment]
This is correct Behavior, Auto Selection date gives only 7 days, MAx Note Span is how much user can select,

Default Date is 7 Days from Today
