### ISSUE TITLE
Company ledger page - Different company working differently when click on any company ledger some open transaction list and other open company page - Suresh Sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1052]
**Describe the bug**
- in company ledger page there is working differently when click on any company some open company view and other open transaction page

**Video**
https://www.berrycast.com/conversations/ddd9b14b-29e3-52f7-b3bb-2319e4c72312
https://www.berrycast.com/conversations/4a7d3465-512a-5369-8333-777b703a2a45

**Comment by mitulpanch** [comment]
nai esa nai he

**Comment by mitulpanch** [comment]
Different buttons different work karte he

**Comment by Avinash-ecb** [comment]
Different role works differently
