### ISSUE TITLE
Service Page - Filter not working Correctly

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1054]
Dropdown required for Recurring / Non Recurring Filter,
Currently it gives only non recurring service when we filter

same way, No selection Option required for type,
Currently on Other types of service gets filtered

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/168209958-8c97ecee-2310-4f2e-b07b-d61aa722ca28.png)
