### ISSUE TITLE
Service Page - Scheduler count not required

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1055]
just Give Yes / No in column count not required
![image](https://user-images.githubusercontent.com/5259926/167068655-3ba00950-39ac-46bb-9d93-b6221243e9f3.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/167074451-6b387d84-1dfa-4ef0-842e-9cb1c093fb1a.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/167084977-50f2d146-0bfb-4756-a6cd-227e5234270c.png)
![image](https://user-images.githubusercontent.com/46588108/167085013-e9e25de3-2bd0-4aa9-8aa0-f2a52b22934c.png)

**Comment by dharmendraecb** [comment]
#1056

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/168208476-e8674acb-df89-437b-9e9e-582ec86951a8.png)
