### ISSUE TITLE
Transaction Page - Unbilled Project List - Filter - Have Contract

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1057]
#1046 
Related to above Issue
Default Filter will be - Only Non contract related Projects

User can change filter from filter options

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/168208216-8d7a536b-d4d4-45f6-8129-e4028c35b1d6.png)

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/0727c36c-b599-5585-b73b-41f5bf49b67e
