### ISSUE TITLE
Contact page - change order of menu in contact view page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1059]
**Describe the bug**
- In contact view page there should be a menu order is like below
1. custom field (show pending)
2. companies 
3. positions
4. projects
5. contracts
6. ledger
7. transaction

- show some pending custom field beside custom field 
- when contact create show contact view page and open custom field drawer
- remove prefix

**Comment by mitulpanch** [comment]
on hold for
1. show some pending custom field beside custom field
2. when contact create show contact view page and open custom field drawer

**Comment by mitulpanch** [comment]
api different he

**Comment by mitulpanch** [comment]
duplicate
