### ISSUE TITLE
Contact page : same contact Error in different contact

### ISSUE THREAD

**Issue by harshitaexpcon** [Fammeo/EasyCloudBooks#106]
![image](https://user-images.githubusercontent.com/66782635/93973093-42249380-fd91-11ea-8333-ce492dd35b8e.png)

![image](https://user-images.githubusercontent.com/66782635/93973112-48b30b00-fd91-11ea-89ee-b15e186952f5.png)

![image](https://user-images.githubusercontent.com/66782635/93973146-57012700-fd91-11ea-95bf-49bd55a14848.png)

same contact Error in different contact

**Comment by ajayrajecb** [comment]
new contact cretae krte time kuch bhi likho first name last name me,
suggestion box aa jata hai 
fir erase kr k dusra bhi nam likho to bhi nhi jata
or kayi bar naam se related suggestion nhi hote, koi bhi 10 naam suggestion me aa jate hain
usne bug me jaisa naam likha hai tum bhi likho, fir erase kr k dusra nam likho, but suggestion box same hi ayega
