### ISSUE TITLE
Company ledger - when click on unbilled project redirect to unbilled project

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1072]
**Describe the bug**
- when click on unbilled project in company ledger page it redirects to transaction page but it should redirect to unbilled project 

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/167110447-6e97f68e-b8b1-440f-935e-bc8f2e751666.png)

**Video**
https://www.berrycast.com/conversations/ed043a69-7c1f-5865-a87a-07a3d2167ff3

**Post**
https://community.easycloudbooks.com/t/Questions%20or%20Bugs/bca44e96-22e6-42c2-a124-839cc9997288

**Comment by mitulpanch** [comment]
As stated before,
Unbilled Projects is part of Transaction Module, it is fully interlinked due to Selection and Create bill from it functionality on Unbilled Project Section,

so Direct to Un billed Project is not possible.
