### ISSUE TITLE
Setting page - two links are showing active

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1085]
**Describe the bug**
- when we are on domain page and click on website link it shows both link active
- showing general and themes active
- advance links not showing active on advance page and other page like industry experience
- check all menu 

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/167237078-01276269-095b-469a-a4a1-ca19d249b3e5.png)
![image](https://user-images.githubusercontent.com/46588125/167237127-f4ff992b-d73a-4a9b-9662-4dcfcecb9e83.png)
![image](https://user-images.githubusercontent.com/46588125/167237193-3712d53b-4e22-465f-b608-65048df342d2.png)

**Comment by dharmendraecb** [comment]
1 Screenshots Invaild

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/167336234-61eeabc5-3f41-4f43-8a39-9ada73b71f9e.png)
Industry experience page is open but it is not showing active link

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/168207760-6b8f9a3a-c135-49e8-9f38-2131cd42c49c.png)
