### ISSUE TITLE
Home page - After tag changed it is not reflected in home page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1091]
**Describe the bug**
Tag Change Error is resolved..
But on home screen tag summary is same.

**Video**
https://www.berrycast.com/conversations/f9db3e29-3c4a-5a7c-bc3c-8adc2d10c26d

**Post**
https://community.easycloudbooks.com/t/Questions%20or%20Bugs/da6d24a5-ee37-4e0b-af6d-ae9338f5d75e

**Comment by Avinash-ecb** [comment]
This is not an issue by @vinpahilwani

**Comment by mitulpanch** [comment]
Gadget updates only once in morning
