### ISSUE TITLE
Home page - some tags are not responsive in desktop screen and going out of screen

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1096]
**Describe the bug**
- when there is tag character is more then they going out of screen
- project tags, contact tags and company tags

![image](https://user-images.githubusercontent.com/46588125/167339815-1f164b7e-793b-466c-b351-1d41d52b8780.png)
![image](https://user-images.githubusercontent.com/46588125/167339846-894a7901-4d9d-43ae-98b6-b16fbeaa0b5e.png)
![image](https://user-images.githubusercontent.com/46588125/167339877-5806af0e-546e-463a-8f02-de241ee18802.png)

**Comment by dharmendraecb** [comment]
https://github.com/Fammeo/EasyCloudBooks/issues/1097
