### ISSUE TITLE
Home page - Some tags are not responsive in mobile view and goin out of screen

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1097]
**Describe the bug**
- when there is more characters in tags they are going out of screen
- Project tags, company tags and contact tags

![image](https://user-images.githubusercontent.com/46588125/167342044-4d16cfd7-2fd3-4e78-a66d-e84af4d575dc.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/167589547-ba8201eb-7919-4804-8888-e0db70baa94d.png)

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/3dc3ce23-1ba6-50b8-8dce-e86541853dd4
