### ISSUE TITLE
Company ledger print - Note should be print when we print company ledger - Suresh Sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1099]
**Describe the bug**
In ledger print notes also required for each transaction

**Video**
https://www.berrycast.com/conversations/eaa4e1db-d0dc-5920-bde4-1406ed41cf8d

**Post**
https://community.easycloudbooks.com/t/Questions%20or%20Bugs/64cf97a1-f48f-49fa-942b-fc1c79754e43

**Comment by mitulpanch** [comment]
approved by - @vinpahilwani

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/167766096-68cad0ff-1bc1-4c9e-a9ad-8f97055f6805.png)

**Comment by dharmendraecb** [comment]
Note: hata diya he

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/168207512-1202ef04-7018-43fe-ad9b-a87f05b56992.png)
