### ISSUE TITLE
Transaction Page - Unbilled Project show Current Status

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1104]
Revert - Add Unbilled Project Status (Lead, In Progress, Finished) to List

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/167766785-191b0d1e-da77-4d7a-8ba3-716fc5ac9a14.png)

**Comment by dharmendraecb** [comment]
Add New Column status

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/168206146-9e1cd1db-8351-42c0-81b0-451a6b39a1e1.png)
