### ISSUE TITLE
Personal gadget - Transaction count is showing wrong

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1107]
**Describe the bug**
- Type of object: **transaction**
- Type of Sub Object: **price**
- Type of Value: **total**
- query search : **Company Avinash Associates**

when create personal gadget it showing wrong count 
![image](https://user-images.githubusercontent.com/46588125/167781994-904d6bcf-2b73-44fb-80bc-e1be24cc514c.png)
![image](https://user-images.githubusercontent.com/46588125/167782120-7b5e8fd5-426f-4c72-bf0c-f625f8d2eab4.png)

**Comment by mitulpanch** [comment]
Total ke liye check karo ek bar

**Comment by mitulpanch** [comment]
and Query builder me Transaction type bhi dalna like "Invoice"
Sare ka total karoge to different ayega
