### ISSUE TITLE
Personal Gadget - project count gadget showing wrong count

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1108]
**Describe the bug**
- Type of Object: **project**
-  Type of Sub Object: **ProjectCount**
- Query search: **Company Avinash Associates**

![image](https://user-images.githubusercontent.com/46588125/167784167-6b93d136-c963-4fff-8621-d32cca0ba67a.png)
![image](https://user-images.githubusercontent.com/46588125/167784214-8cd4ff2b-d724-47c6-8da2-0b50e4ae0986.png)
![image](https://user-images.githubusercontent.com/46588125/167784280-441ac7f0-2835-4e6e-9801-a48d7e9ced9b.png)

**Comment by dharmendraecb** [comment]
count is mix

**Comment by dharmendraecb** [comment]
like project page and finish project, Review Project

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/b0607996-6601-56ff-bfe9-ec8fe77d542e
