### ISSUE TITLE
Personal Gadget - Is reverse is not working

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1109]
**Describe the bug**
- when is reverse switch is on then also the chart takes not any effect

**Before**
![image](https://user-images.githubusercontent.com/46588125/167786734-014ca14e-0e0c-4880-8109-4e3a7b13fec1.png)

**After**
![image](https://user-images.githubusercontent.com/46588125/167786835-31de371f-5659-47ca-80a9-c08e14a7c84e.png)

**Comment by dharmendraecb** [comment]
Check New Theme
