### ISSUE TITLE
Work Task - After combine import reports generates but not open

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#111]
### Click on report button open xml tree

![2020-09-23_22-52-38](https://user-images.githubusercontent.com/46882964/94047764-2e5c4a00-fdf0-11ea-925c-2137c8c3b4c7.png)

### After click
![2020-09-23_22-54-15](https://user-images.githubusercontent.com/46882964/94047844-48962800-fdf0-11ea-94b2-3fc2d12d5be1.png)

**Comment by ajayrajecb** [comment]
### This button throws common worktask page, 
### only combine import work task show hona chahiye is pe click krne par
![2021-02-02_16-57-09](https://user-images.githubusercontent.com/46882964/106594295-ead0d400-6577-11eb-9378-260e92fc13bc.png)

**Comment by mitulpanch** [comment]
Aaj sham ko release hoga
