### ISSUE TITLE
Personal Gadget - some textbox over lapping in mobile view

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1112]
**Describe the bug**
- parameter, type of subject and type of value are overlapping in mobile view
- give some space in textbox

![image](https://user-images.githubusercontent.com/46588125/167806113-478de231-7d18-436f-bb7b-1fc45f3e7ff1.png)

![image](https://user-images.githubusercontent.com/46588125/167806484-da7f7e4d-66c8-4322-9edf-6f60cd63e160.png)

**Comment by mitulpanch** [comment]
Too lengthy to complete, Leaving as of now, 

Responsive design for Query Builder is complete make over customization
