### ISSUE TITLE
Personal gadget- chart is not showing correct data

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1117]
**Describe the bug**
- in personal gadget chart is not showing correct data
- count showing 29 but it is 28
- arrow directions are different in old view and new view

![image](https://user-images.githubusercontent.com/46588125/167820864-50ae469a-ed1f-4bf4-a574-53cdb942cc05.png)
![image](https://user-images.githubusercontent.com/46588125/167824568-6d88b3f6-f11a-4e07-bfaa-af30d71eb691.png)
![image](https://user-images.githubusercontent.com/46588125/167824622-7054ef7a-84e4-455d-9499-0f9cd389981c.png)

**Comment by dharmendraecb** [comment]
arrow directions are different in old view and new view (Module Remove in new )
