### ISSUE TITLE
Personal gadget - when refresh personal gadget it changes all gadget colors

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1126]
**Describe the bug**
- when we refresh personal gadget it changes all gadgets colors

![image](https://user-images.githubusercontent.com/46588125/168008113-0fb063fe-b6f2-4cec-9ee8-1440f35892c9.png)

**Comment by dharmendraecb** [comment]
auto generate color Not UI Issue
