### ISSUE TITLE
Email Template - Email template copy button not working

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1156]
**Describe the bug**
- when we are try to copy email template it is updating

**Comment by Avinash-ecb** [comment]
Files is not copied

![image](https://user-images.githubusercontent.com/46588125/168971053-7aba0c8c-707c-4df5-964d-73b6d27c0bee.png)
![image](https://user-images.githubusercontent.com/46588125/168971099-61aad590-ea63-4c9d-8d8b-ac44b1e1c9c1.png)

**Comment by dharmendraecb** [comment]
file Copy Nahi karni he

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/86c4a5cb-9401-54d3-bff7-560809959bb2
