### ISSUE TITLE
Email template - dropdown list does not following display pattern

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1164]
- in filter apply to filter is not following dropdown display patter
- change label in filter filter -> Apply To
- In create view  apply to filter is not following dropdown display pattern

![image](https://user-images.githubusercontent.com/46588125/168972938-3fe19f54-f444-4a07-b174-be308b4027f0.png)
![image](https://user-images.githubusercontent.com/46588125/168972894-717ded8e-95cd-4ffa-b237-537bddead55f.png)

Follow this display pattern
![image](https://user-images.githubusercontent.com/46588125/168973016-07426600-a06d-4a6b-8e40-3ef1eefbb7a8.png)

**Comment by dharmendraecb** [comment]
create video in in filter apply to filter is not following dropdown display patter
