### ISSUE TITLE
Staff page- Shift work issues

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#118]
### Sumit ka shift work popup durr open hota hai uske btn se, or sumit k shift work me uska bhi naam aata hai, jo ki nhi aana chahiye

![2020-09-24_14-14-27](https://user-images.githubusercontent.com/46882964/94125594-2cd46580-fe74-11ea-98f5-ec44fd0e1006.png)

**Comment by ajayrajecb** [comment]
### and mouse scroll karne pe ye popup gayab ho jata hai, fir dubara click karne pe screen blink hota hai fir tisri bar me shift work popup wapas aata hai

**Comment by dharmendraecb** [comment]
Vinod Sir has been changed the design.
