### ISSUE TITLE
Notification Template Page - There is not any default image when we upload image

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1188]
**Describe the bug**
- when we try to upload image there is not any default image in image uploader

![image](https://user-images.githubusercontent.com/46588125/169219369-5b56a1d7-264c-442b-af83-71b505bc154e.png)

**Comment by dharmendraecb** [comment]
default Images (transparent image) -- https://cdn.easycloudbooks.com/ecb/www/contents/images/1x1.png
