### ISSUE TITLE
Warning message appear while we just open create new tax, it should be come when we save without add sub tax

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/EasyCloudBooks#119]
### Warning message appear while we just open create new tax, it should be come when we save without add sub tax

![Screenshot_2020-09-24 EasyCloudBooks - The Smart Way of Managing Practice(2)](https://user-images.githubusercontent.com/58812881/94130533-6d36e200-fe7a-11ea-8b4e-f1bef5020009.png)

**Comment by dharmendraecb** [comment]
bug nahi he

**Comment by ajayrajecb** [comment]
Warning message aana chahiye jb bina sub tax add kiye save pe click karen tab
