### ISSUE TITLE
Company page open add Service Viewer

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/EasyCloudBooks#1190]
Open any Company Advance Viewer open,  view on Custome Field, Contacts, Positions, Projects, Contracts, Ledger, Transactions, License but not view Services So, Company don't know what services apply

https://user-images.githubusercontent.com/77724114/169225368-4909a1e5-4668-483b-9f78-2adc0588dc0f.mp4

ed**

**Comment by mitulpanch** [comment]
old issue
