### ISSUE TITLE
Notification Template Page - When edit template it shows only text in notification template

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1192]
**Describe the bug**
- When edit notification template it shows only text in notification template not showing html

![image](https://user-images.githubusercontent.com/46588125/169231128-465fd770-6328-4bc0-8daf-763df495041b.png)
![image](https://user-images.githubusercontent.com/46588125/169231171-4025b3d4-8961-4a06-a9fb-e106ad11059a.png)

**Comment by dharmendraecb** [comment]
Remove Tool Bar

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/34386999-0860-5ce8-a576-4c79aecf904b
