### ISSUE TITLE
Email Template Page - UI changes

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1197]
Provide Email Template Details you can add multiple details for every field. - NOT REQUIRED KINDLY REMOVE
Select Type of Create Template --> Select Type (to get appropriate placeholder value)
KEY --> Placeholder
Provide Email Subject.Max 500 Characters --> NOT REQUIRED KINDLY REMOVE
Remove Default Overlay --> Custom HTML Code
This will remove default email design from Template, use only when you are Fully Customizing Above Template --> Use Only when you are technical expert.
You can add multiple Files for condition. --> You can add multiple Files
Upload Excel File. Popup will Auto Close after File Save --> REMOVE

**Comment by mitulpanch** [comment]
Only English change / no functionality change

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/187626949-fb96a5d0-92c6-4906-9c9f-5b0a801559b0.png)
![image](https://user-images.githubusercontent.com/46588125/187627268-a2f1a3a3-149d-4b4c-9eca-5e6f79603f70.png)
