### ISSUE TITLE
Ui issue 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/EasyCloudBooks#12]
![image](https://user-images.githubusercontent.com/58812881/88509714-4cc7e400-cfff-11ea-803d-ea9b8d807b04.png)

Go To Org 
https://www.fammeo.in/p/EasyCloudBooks

**Comment by ajayrajecb** [comment]
### Both Buttons size  should be similar.

https://www.fammeo.in/p/EasyCloudBooks
