### ISSUE TITLE
Other setting- Project settings- Force Project Custom Fields not working

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#120]
### I move some projects to complete stage without fill any custom fields and its move.

![2020-09-24_17-27-07](https://user-images.githubusercontent.com/46882964/94142143-6e243f80-fe8b-11ea-87ed-dfdba9099b9e.png)

### after move in complete stage
![2020-09-24_17-30-55](https://user-images.githubusercontent.com/46882964/94142374-cfe4a980-fe8b-11ea-973f-64353c39d8b4.png)

### All custom field blank
![2020-09-24_17-31-19](https://user-images.githubusercontent.com/46882964/94142383-d3783080-fe8b-11ea-9948-0650d18c8672.png)

**Comment by dharmendraecb** [comment]
![Untitled](https://user-images.githubusercontent.com/46588108/95417268-3ec50680-0952-11eb-8c3e-98f66df868dc.png)
