### ISSUE TITLE
Webhook Template Page - Webhook template is not updated

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1206]
**Describe the bug**
- when try to edit webhook template is not updated

![image](https://user-images.githubusercontent.com/46588125/169467114-06484264-ff56-4a65-9fcf-7ba7ce57512c.png)
![image](https://user-images.githubusercontent.com/46588125/169467179-cc564021-abcd-4582-858c-bfb4437af50e.png)

**Comment by dharmendraecb** [comment]
https://www.berrycast.com/conversations/216b5231-3c2d-587f-9652-2824d07dab43

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/2bda97ad-22d0-5798-9820-98b176b29d3d
