### ISSUE TITLE
Webhook Template Page - Give webhook url example in placeholder

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1207]
**Describe the bug**
- give example of URL in URL textbox like https://www.easycloudbooks.com/

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/172621232-05d6c9f5-cc0a-4f2b-b22a-024316334c79.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/175858403-6e93c479-f917-4d73-a0e9-98c6631b16c2.png)
