### ISSUE TITLE
Webhook Template Page - Key button is only required in post method

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1210]
**Describe the bug**
- when we select other than post method key button is not required

![image](https://user-images.githubusercontent.com/46588125/169500890-b977ccec-febb-4f7f-9ece-0d7b7d441764.png)

**Comment by dharmendraecb** [comment]
Fields Input Add Key

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/172619835-2aff5752-c68c-45cf-a68c-b5ddfa71aa21.png)
