### ISSUE TITLE
Required Documents option 

### ISSUE THREAD

**Issue by Fresh-loan** [Fammeo/EasyCloudBooks#1215]
![rEQU DOC](https://user-images.githubusercontent.com/101444132/169537098-06176850-51cb-4895-be00-7c6798e12117.png)

As per attached screen shot 
we Required Document option at the time of Viewing Separate Contacts OR Company
( for more details pls find attached screen shot )

**Comment by mitulpanch** [comment]
new Document Section Upcoming
