### ISSUE TITLE
Project Deviation Page - Some changes by Vinod sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1245]
**Describe the bug**
- Remove green timer button from project deviation page
- increase column width of budget and Time
- if budget and time will increase by limit show in red
- changes some color combination of budget and time column label

![image](https://user-images.githubusercontent.com/46588125/170431413-22e1c27b-c0f1-4bb3-b734-66339565fae8.png)

**Comment by dharmendraecb** [comment]
not increase column width of budget and Time

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/6a8757be-3bf3-5606-840d-8eb97d299cbe
