### ISSUE TITLE
All the options of the highlighted area of screenshot  image become invisible

### ISSUE THREAD

**Issue by Fresh-loan** [Fammeo/EasyCloudBooks#1250]
https://www.berrycast.com/conversations/e29f2e1f-daf0-5d55-b294-b7dea14f048c

![Untitled](https://user-images.githubusercontent.com/101444132/171111840-99e0bc6e-268c-4d20-a521-10f6f4924db5.png)

![IMG_20220531_084216](https://user-images.githubusercontent.com/101444132/171112469-79e01e08-f014-4c79-8150-61e734d10163.jpg)

As the highlighted area is visible in the screen shot image, all these options disappear in a few moments while operating from the mobile,

All the options of the highlighted image become invisible after showing a glimpse, there is no chance of clicking till

**Comment by mitulpanch** [comment]
new design coming soon
