### ISSUE TITLE
Tax Setting page - Text should be change 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1253]
**Describe the bug**
- Create Taxes From Here -> Create Tax, 
- No SubTax Added -> No Sub Tax Found
- Provide some Description about this Template
- Rupee symbol should be ₹

![image](https://user-images.githubusercontent.com/46588125/171559916-e2f58fc1-ce67-4a90-b1c7-b632364872b1.png)
![image](https://user-images.githubusercontent.com/46588125/171559987-20949d31-9a1e-4ba5-bcb6-cd2c2961b237.png)
![image](https://user-images.githubusercontent.com/46588125/171564428-61f293e0-e6ea-48ba-8d6c-66f47dd600d2.png)

**Comment by dharmendraecb** [comment]
Rupee symbol should be Setting page

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/67c2963b-6d37-5efd-aa8d-44ac7e4c4acb
