### ISSUE TITLE
Project Page - Some changes in year and period filter options by Vinod Sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1262]
**Describe the bug**
- default show current year in year filter and default show current month in period option
- there should be ascending order of month like jan, feb etc. in period option
- change option text none -> NA, full -> NA

![image](https://user-images.githubusercontent.com/46588125/171785843-c0608bbe-da7d-4148-8ddf-9fe084dfe7de.png)

**Comment by mitulpanch** [comment]
only sorting is possible

Full to NA is not possible

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/85ec46bc-321e-521c-acb3-e8c2c2c308f0
