### ISSUE TITLE
Project Page - Project due date showing all year when edit

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1263]
**Describe the bug**
- when edit due date it showing all year

![image](https://user-images.githubusercontent.com/46588125/171799597-a0d56c16-24cb-4705-933b-cff077760889.png)
![image](https://user-images.githubusercontent.com/46588125/171799538-9fe4110e-ed80-42f6-a148-b0178d2505a6.png)

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/ed869e6b-079d-5fe4-ae4a-e425b2dc2236

**Comment by dharmendraecb** [comment]
date not range

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/cb7bbde6-bc1d-56bb-a99c-cbcbce1bc08c
