### ISSUE TITLE
Project Page - When create project using recurring pattern from service due date is not creating

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1264]
**Describe the bug**
- when we are crating project using service recurring pattern and if we set due date it does not create due date

![image](https://user-images.githubusercontent.com/46588125/171830997-ceeb8641-62d0-43f8-a3f5-232b77787724.png)
![image](https://user-images.githubusercontent.com/46588125/171831074-f1be221b-e49a-4304-bebe-96e7f127f210.png)

**Comment by mitulpanch** [comment]
Period ke sath project banao

Service pe year none rakha he

And project full ka banane pe nai ayega

Period must match
