### ISSUE TITLE
Process Flow Page - Scheduler timing is not updating

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1272]
**Describe the bug**

https://www.berrycast.com/conversations/3c7665b9-29ac-5033-a862-3f963736138d

**Comment by dharmendraecb** [comment]
Change Bug Title

**Comment by dharmendraecb** [comment]
Different ApplyTo And showing New

![image](https://user-images.githubusercontent.com/46588108/175294652-763aa755-7099-4dcc-99ff-e5f64293a113.png)
