### ISSUE TITLE
Project Page - When saving working paper without entering data it shows wrong message

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1279]
**Describe the bug**
- when we are saving workpaper without entering any data it shows message "maximum 999 character Allow" 

https://www.berrycast.com/conversations/cf843ad2-61fc-5ff9-b4e7-cfe8ed308c9e

**Comment by dharmendraecb** [comment]
please provide Description And maximum 999 character Allow

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/aca6f202-68c9-5f12-b1c2-1680c824a45b
