### ISSUE TITLE
Account Design issue

### ISSUE THREAD

**Issue by harshitaexpcon** [Fammeo/EasyCloudBooks#128]
![image](https://user-images.githubusercontent.com/66782635/94239729-d9275200-ff2f-11ea-8ec9-b1334531ab4e.png)

Account ---> Create Account --> Members (Add Button)

**Comment by dharmendraecb** [comment]
recheck

**Comment by ajayrajecb** [comment]
> recheck

Ho raha hi, mouse scroll karne pe pura drop down sath sath move krta hai page me
