### ISSUE TITLE
Company page - rupee icon is different in same page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1287]
**Describe the bug**
Ruppee icon should be same in all page

https://www.berrycast.com/conversations/05c9827c-b710-5ca5-a342-c16037aaa73f

https://www.berrycast.com/conversations/a196bea9-230b-5e11-937e-6246656befd9

**Comment by dharmendraecb** [comment]
and Check General Settings Default Currency Set

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/dd28a043-cee3-5ab2-9e08-48485a627ae4
