### ISSUE TITLE
Contact Page - When name has more characters then edit and delete button has UI issue

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1291]
**Describe the bug**

https://www.berrycast.com/conversations/8263a341-78cf-5f8a-9ca6-80634791661b

**Comment by dharmendraecb** [comment]
Content (Text) Not Valid

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/ede6c151-059a-58eb-a50d-3fb7e165c3fb
