### ISSUE TITLE
Project Page - Showing database error while saving due dates

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1296]
**Describe the bug**
https://www.berrycast.com/conversations/1a04bc16-6cc3-5982-a5e3-7c016ee15055

**Comment by dharmendraecb** [comment]
back-end Error Solved And UI Issue Invalid

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/14ff2001-72b7-575d-867b-c06ecce3121a
