### ISSUE TITLE
Account Reload Error in no of counts

### ISSUE THREAD

**Issue by harshitaexpcon** [Fammeo/EasyCloudBooks#130]
![image](https://user-images.githubusercontent.com/66782635/94331529-c887e200-ffea-11ea-81f0-3cf4a5f1ca18.png)

### account delete ho raha he or vo list mese nikal bhi gya par niche count decrease nahi hote
refresh karne ke bad decrese hote he

**Comment by harshitaexpcon** [comment]
![image](https://user-images.githubusercontent.com/66782635/94334938-77312000-fff5-11ea-8093-6002075cb634.png)

**Comment by ajayrajecb** [comment]
### Not fixed, first time its work properly, but when 2nd accounts close , count number not change
