### ISSUE TITLE
Scheduler Page - dropdown design pattern is not followed

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1304]
**Describe the bug**
https://www.berrycast.com/conversations/922274b0-86fb-5821-b04f-4599644aa282

**Comment by dharmendraecb** [comment]
your Browser Problem check Different Browser

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/bf25d9b7-2578-578f-b553-cadd90f2bd3d
