### ISSUE TITLE
Scheduler page - Showing wrong month while creating half yearly pattern scheduler

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1309]
**Describe the bug**
https://www.berrycast.com/conversations/1377c9a1-8faa-5e77-b37f-b856faba84e1

**Comment by mitulpanch** [comment]
Just need to hide year and month for monthly scheduler

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/87eac8db-da68-5b7f-9ad0-a946610fe8a8
