### ISSUE TITLE
Seed Package Issue

### ISSUE THREAD

**Issue by sureshsirvi** [Fammeo/EasyCloudBooks#1329]
https://www.berrycast.com/conversations/ca6fa355-21c5-59e9-9462-63b5d363965b

**Comment by mitulpanch** [comment]
"note" html resetting fixed

Remove button for individual added Package is not possible

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/b3b9574e-a850-5f63-84a1-a82ca12f4ca2
