### ISSUE TITLE
Email Log Page - what is the use of create button

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1340]
**Describe the bug**
- what is the use of create button in email log page
![image](https://user-images.githubusercontent.com/46588125/176838751-008a9952-1da3-4645-bbb4-1b6e3265b8d2.png)

**Comment by dharmendraecb** [comment]
Click to open Create And after Send Email

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/b35b31ed-a743-5d9c-82f5-1ece70c47d66
