### ISSUE TITLE
API Key Page - there is not any staff section which is showing in log page in section column

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1372]
**Describe the bug**
![image](https://user-images.githubusercontent.com/46588125/177721256-0ec9ec93-50b7-4652-971e-ab71c7eff010.png)
![image](https://user-images.githubusercontent.com/46588125/177721345-7fbeece9-7cd1-4c4f-9a0d-92acfc757392.png)

**Comment by mitulpanch** [comment]
There are other possibilities, like Client area Key which do not have access to user area
