### ISSUE TITLE
API Key Log - if mutlitple checkbox is not used in future then remove it

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1378]
**Describe the bug**
![image](https://user-images.githubusercontent.com/46588125/177739670-e5a3ff80-74b6-456f-b61e-04aa58de909c.png)

**Comment by mitulpanch** [comment]
just design, different design on different pages give odd look

**Comment by mitulpanch** [comment]
this also increases development time , as special design on each page
