### ISSUE TITLE
Contact Page - Some old contacts not getting their phone and email type while edit

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1380]
**Describe the bug**
https://www.berrycast.com/conversations/4a8274d7-0e6e-5b80-a9f6-f65b3dc8a969

**Comment by mitulpanch** [comment]
Provide default if not matching
@dharmendraecb

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/eb0d8b7e-c568-554f-a351-6cfda9dd2169
