### ISSUE TITLE
Project View Remove in Service View

### ISSUE THREAD

**Issue by dharmendraecb** [Fammeo/EasyCloudBooks#1405]
Service Click View Open This Remove BY @vinpahilwani 
![image](https://user-images.githubusercontent.com/46588108/178489181-d63d5cff-93d5-4246-9dd3-2afd0cba0343.png)

![image](https://user-images.githubusercontent.com/46588108/178489322-0cf82ab9-7a34-4bdf-96c2-8d926af7e82b.png)

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/b0845a05-0b77-5339-b3bf-ff6f43cc6540
