### ISSUE TITLE
Rate Limitter Page - Email notification page process is not finishing

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1408]
**Describe the bug**
https://www.berrycast.com/conversations/73d2ea00-c3d0-59cb-a294-8553e7882cea

**Comment by dharmendraecb** [comment]
not Rate Limitter Page this page error page

**Comment by dharmendraecb** [comment]
UI Issue Solved

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/d014ce3e-46d4-5c4c-a78a-72fcc4422bc6
