### ISSUE TITLE
Login Page - in phone number login page icons is defferent

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1447]
**Describe the bug**
- phone icons is different in every stage
- tick icon is not matching with others

https://www.berrycast.com/conversations/b24c4a8f-4dc2-5b5b-8b7b-638e40fc237a
![image](https://user-images.githubusercontent.com/46588125/180728565-a8fc2596-3f03-4492-9d7c-fb70f9ccf7d3.png)
![image](https://user-images.githubusercontent.com/46588125/180728678-420deaab-cd28-4a53-87fb-127d6d2e5dac.png)

**Comment by dharmendraecb** [comment]
don't compare User Section UI
