### ISSUE TITLE
Login Page - Email Login - difficult to change otp

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1450]
**Describe the bug**
- If we want to change otp then we have to remove old , it is not replaced by just typing

![image](https://user-images.githubusercontent.com/46588125/180952101-edb06fff-789e-4826-8e90-6ec7c52c4ae4.png)

**Comment by mitulpanch** [comment]
Clear Textbox after each api call @dharmendraecb

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/777ae8e4-7994-516b-859b-c627ff1185ce
