### ISSUE TITLE
Email Log Page - When try to create email then body is required but not asking for content

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1452]
**Describe the bug**
https://www.berrycast.com/conversations/051e5077-62fd-5282-92e7-48d19f95c1e4

**Comment by mitulpanch** [comment]
Template is not required, @dharmendraecb  remove * icon

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/187352906-9d98b699-91a3-40ce-a168-07b0887a01b9.png)
