### ISSUE TITLE
Auth Code Page - Icon is not display correctly and show text on hover

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1455]
**Describe the bug**
https://www.berrycast.com/conversations/3e73dee2-c4ce-5c50-8605-8360fccadde4

**Comment by mitulpanch** [comment]
Change icon, or button to give clear indication to user, that button is for reset auth code

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/187138422-9283727e-cb64-4440-ad72-bd970107aa0f.png)
