### ISSUE TITLE
Auth Code Page - key is not showing only showing #

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1456]
**Describe the bug**
https://www.berrycast.com/conversations/2c95c0df-f367-58af-bb64-5b786c9948dd

**Comment by mitulpanch** [comment]
Design Error , Key is not displayed

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/187366651-f2411bd8-b30c-41c0-83ea-b69b1a53d8b9.png)
