### ISSUE TITLE
Auth code page - When we try to change code we have to select code

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1457]
**Describe the bug**
https://www.berrycast.com/conversations/3420bfd9-313f-5482-a8b3-c5a44f94ce1a

**Comment by mitulpanch** [comment]
Clear Textbox after every reset @dharmendraecb

**Comment by dharmendraecb** [comment]
Provid Valid Message @Avinash-ecb  (Video can't Load)

**Comment by Avinash-ecb** [comment]
- when try to update first digit it is not changing, all digit are working correct

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/0c38449c-7d57-576a-bafa-38e4b545116b

**Comment by Avinash-ecb** [comment]
After discuss with @dharmendraecb don't required too much validation
