### ISSUE TITLE
Auth code Page - There is not any message of already register user for reset

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1458]
**Describe the bug**
![image](https://user-images.githubusercontent.com/46588125/181446878-6d0dcf9a-4629-418f-80b6-7ba6ad17baf5.png)
![image](https://user-images.githubusercontent.com/46588125/181446928-a3aff12a-6d5b-4fc2-9137-f71959414817.png)

![image](https://user-images.githubusercontent.com/46588125/181447003-128872f1-48bd-4811-95d9-ef07aa1d447f.png)

**Comment by mitulpanch** [comment]
this is normal, because login provider website is different
