### ISSUE TITLE
Duplicate Contact (Mobile) No. accepted is an Error 

### ISSUE THREAD

**Issue by Fresh-loan** [Fammeo/EasyCloudBooks#1463]
![Photo from Kailash Joshi Director of Fresh Loan](https://user-images.githubusercontent.com/101444132/181914358-1867c489-f4d2-4366-b3cd-4e8038b35c59.jpg)

as per attached Image Duplicate Contact Mobile No. saved successfully

**Comment by mitulpanch** [comment]
forwarding to @Avinash-ecb to verify
