### ISSUE TITLE
Fees contract print page - Currency icon is not showing in some place

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1464]
**Describe the bug**

![image](https://user-images.githubusercontent.com/46588125/182074654-da3600c5-961d-4ac8-93a7-1aebbf0cdd31.png)

**Comment by mitulpanch** [comment]
give better description, video is for reference to find, but Problem, Suggestion should be there, without that i can not give  priority to this

Steps to reproduce, Problem, Suggestion, Clash with any other Module, any issue which we can link all things needs to be here

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/187153323-bbe59a22-91e8-4dd6-ad17-0b9bc0579fa9.png)
