### ISSUE TITLE
All Page - When we click notification it redirects to error page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1466]
**Describe the bug**

https://www.berrycast.com/conversations/d7e5e47a-b185-5a20-865d-8d6c000e498a

**Comment by mitulpanch** [comment]
anything All page is not good, can track

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/196597079-b47b4925-19ed-48dd-81d1-d9bcdc37bed0.png)
If we click on any notification which are showing in notification pop over then it redirects wrong url like below

https://ac-74.s1.easycloudbooks.com/user/{Current Page}/CreateNotification?id=SU3Y0g7KEESN4vq2hVCisw

this current page should remove
