### ISSUE TITLE
Scheduler Page - Project create scheduler is not working by Naman Dokania

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1468]
**Describe the bug**

https://www.berrycast.com/conversations/28ae2da9-d0f8-567f-9712-aaa04826bb84

**Comment by mitulpanch** [comment]
give better description, video is for reference to find, but Problem, Suggestion should be there, without that i can not give  priority to this

Steps to reproduce, Problem, Suggestion, Clash with any other Module, any issue which we can link all things needs to be here
