### ISSUE TITLE
Staff Page - Issue while filter in staff page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1473]
**Describe the bug**
https://www.berrycast.com/conversations/74ee67c7-227f-5215-b421-e5e1ba75605b

**Comment by mitulpanch** [comment]
give better description, video is for reference to find, but Problem, Suggestion should be there, without that i can not give  priority to this

Steps to reproduce, Problem, Suggestion, Clash with any other Module, any issue which we can link all things needs to be here

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/b962cef5-a01a-5469-8ef5-3f73f1c996c6
