### ISSUE TITLE
Staff page - primary and secondary emails are accepting same emails

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1474]
**Describe the bug**
https://www.berrycast.com/conversations/5445d9db-cd71-5a5e-8f92-4ee8b3464507

**Comment by mitulpanch** [comment]
give better description, video is for reference to find, but Problem, Suggestion should be there, without that i can not give  priority to this

Steps to reproduce, Problem, Suggestion, Clast with any other Module, any issue which we can link all things needs to be here

**Comment by mitulpanch** [comment]
forwarding this

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/84628c53-d3f8-59a5-8d3e-d6cf6ccdfa85
