### ISSUE TITLE
Service page - bullates points not saving while adding working paper

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1480]
**Describe the bug**
https://www.berrycast.com/conversations/a225e982-cf32-5cd3-9ff1-1ec4db276ae8

**Comment by mitulpanch** [comment]
give better description, video is for reference to find, but Problem, Suggestion should be there, without that i can not give  priority to this

Steps to reproduce, Problem, Suggestion, Clast with any other Module, any issue which we can link all things needs to be here

**Comment by mitulpanch** [comment]
considering this, forwarding this , due to small migration issue

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/7b9af25b-9f65-50b7-9656-737c51632b93
