### ISSUE TITLE
All Page - When we filter records and click enter it should filter data by Abhinav Sirvi Associates

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1487]
**Describe the bug**
![image](https://user-images.githubusercontent.com/46588125/183244308-8ab7b4ae-fbb4-44c7-af74-e1e8e7e53425.png)

**Comment by mitulpanch** [comment]
All page issues are not trackable, so clear indication with actual page will give better result in term of issue tracking,

closing for now, but taking Keyboard shortcut implementation as input
