### ISSUE TITLE
Data Upload Template Page - Show full column name on hover By Suresh Sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1492]
**Describe the bug**
- show full column name on hover
- company address line don't have numbers like company address line 1 and company address line 2

![image](https://user-images.githubusercontent.com/46588125/183562915-5d4ae319-1296-414b-960e-4728fe13bc41.png)

**Comment by mitulpanch** [comment]
approved

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/184479669-a451607a-f248-422d-a3d9-5def96fea842.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/184493155-e7d98d62-6530-47e0-893a-ab16dbbb61a2.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/184797889-b9aa79ae-1c7b-4543-845b-27817ed4b276.png)
