### ISSUE TITLE
Company Page - when create company it is not showing in top

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1500]
**Describe the bug**
https://www.berrycast.com/conversations/52bd0e68-6d62-53c6-b6ef-036ae9f24cba

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/b351083e-bc4c-56e3-a388-15900cc6b5ec

**Comment by vinpahilwani** [comment]
@mitulpanch what is default order ?
