### ISSUE TITLE
Company Page - service manager is not tick when we change manager from action

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1501]
**Describe the bug**
https://www.berrycast.com/conversations/b31e7868-a372-5839-901e-b4bf959f9f80

**Comment by dharmendraecb** [comment]
multi action Not Select Manager.
service manager in company ?

**Comment by vinpahilwani** [comment]
@Avinash-ecb this is not a bug, tune multi action button pe click kiya hai
