### ISSUE TITLE
Project Page - Todo comes from Service instead of Last Project

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1502]
Problem - 
Create Project from Project Page gets ToDo from Template instead of Last Project

Solution -
Change Behavior to Last Project then Template

Initially Reported by @sureshsirvi 
Verified by @Avinash-ecb

Initial Comment-

**Describe the bug**
https://www.berrycast.com/conversations/f709deef-0de7-5ef6-bb28-9f0ce9a40a27

**Comment by vinpahilwani** [comment]
this should be priority

**Comment by mitulpanch** [comment]
this is coming from Service Page - Template
I guess expectation is From Last Project

but not implemented on "Create Project" Single

Reason was - before all change - 
Template was getting Selected here, and only that was followed
l
still I can change this behavior to Follow Last Project then Template

**Comment by mitulpanch** [comment]
OK developed as required,

First Priority - Last Project by Create Date
Second - Template

**Comment by mitulpanch** [comment]
should be available in next Release

**Comment by mitulpanch** [comment]
there is no error related to Sort Order
