### ISSUE TITLE
Transaction Page - Box design is not display correctly in firefox

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1503]
**Describe the bug**
![image](https://user-images.githubusercontent.com/46588125/183861038-db6013f2-ae0c-4dcd-a84c-110ca2005264.png)

**Comment by dharmendraecb** [comment]
provaid video page load to end

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/183878293-f3d30689-bf80-49c3-aff1-59af9f4eb45f.png)

**Comment by mitulpanch** [comment]
Closed not relevent, not possible to fix
