### ISSUE TITLE
Project Page - Leave Project Option

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1504]
As described by @vinpahilwani 

Problem -
1. Project Member stays in Project whether they have any work or not
2. Project member's Project list keeps increasing after their work completion, until project manger flags Project as Completed.
3. Its difficult to Find what's need to be done from project list, as it shows all project

Solution suggested -
1. Add "Leave Project" Button for Project Members
2. Project Managers cannot leave Project
3. Club this functionality with "?" Project Manager will get to better understanding of what's need to be done
4. Project Member can leave project after his/her To-dos "Done", at any stage of Project
5. Project Members will have only project on which they can work, and leave project after "Done", don't stay in Project
6. Project Status was suggested for Project Members/ but it violates current structure / roles / responsibility of project manager, so dropped and later on Task Module will fulfill this requirement, as it has more power and structure possibilities.
7. Also at time of Leaving Project , the member need to check responsible note, ie. "Yes, I have completed all work!" to just give sense of responsibility.
8. There is no possibility of taking notes from leaving member, just check box. nothing taken from them.
9. this functionality is clubbed with #1505 to get better resolution for both manager and members

Design -
1. This button "Leave Project" will be at "Project Details" section
2. this is not coming to Project list Page
3. Project member need to open detail section of project and click "Leave Project", Popup will come up with disclaimer to check, and success Message

technicalities -
1. No data is taken from Leaving Member
2. only Member can use this feature
3. Managers can not use /see this
4. Project Details Page will have this button
5. List will not have this / or clubbed to something else

other details will be added on later stages

**Comment by vinpahilwani** [comment]
1. Button "Work Done" instead of "Leave Project"
2. Project Manager can change project manager to shift work as it is working currently

**Comment by vinpahilwani** [comment]
https://www.berrycast.com/conversations/51041a54-6414-56ce-825e-451af7581d22

**Comment by vinpahilwani** [comment]
This should be our priroty

**Comment by mitulpanch** [comment]
i consider this as all approved,

Please provide Message which we need to take as consent from member

**Comment by mitulpanch** [comment]
Button Placement is as shown in Video,

beside "+ ToDo" button, title = "Work Done"

I  suggest we should place it on Top bar

**Comment by vinpahilwani** [comment]
1. Button on Top besides remove project
2. Confirmation message "Plz Confirm, Have You Completed All Your Todos"

**Comment by mitulpanch** [comment]
only Members who are not Project Manager can see this

**Comment by mitulpanch** [comment]
after #1523 anyone who is in the team Project Manager / Project Member can see this

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/4cc9c7b6-fff5-5715-8fa8-698263e255aa
