### ISSUE TITLE
Company Page - Multiple Select beyond Paging

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1509]
allow to select beyond 100 Companies for Multiple Action

Problem -
1. Onboarding Client requires this to add Services to all Companies

Solution -
1. Create "Select All" button on filter option on Company Page
2. Clear All functionality will help handling this, uncheck this

Design -
1. Filter Popout on Company Page  will have new Option "Select All X Companies"
2. this will show max 100 companies only, but act as X companies Action
3. Clear filter bar will have option to Uncheck All / clear All
4. Multiple Action window will show "Doing Action on X Companies"
5. Only show Multiple Action which are available for beyond 100 companies

Technical Difficulties
1. Need to Make API dynamic / Background Handled to Take Load of 100 or More Companies 
2. Current API can not take this much Load, So each API need to work which ever Required
3. Currently Planned for Add Service only
4. Matching exact Count of Companies is difficult task, as multiple users work on same page
5. Delayed result is difficult to understand for End users
6. Flow will be like - 
    a. "Select X Companies" Option on filter Popout
    b. Go to Multiple Action
    c. Select Available Action (currently only 1 Add Service Available)
7. Technical Flow-
    a. "Select X Companies" set to Filter Expression
    b. Handle "uncheck" single / Multiple Company and save them as "Ignored Companies"
    c. Save Count of Companies for later Validation
    d. After Multiple Action click, Get actual Companies Ids to do Action , ignore CRIds that are unchecked
    e. Send return all 4000 CRIds to Delayed Action API

Time Required -
1. Design 2-3 Days minimum
2. Api - 2-3 for Delayed Action API

Notification is not considered yet

**Comment by vinpahilwani** [comment]
We need this but right now its not priority, we can postpone it for later date

**Comment by mitulpanch** [comment]
sir please check requirements, we can do this in separate windows, parallelly 
Not periodized , but if you can confirm requirements

**Comment by mitulpanch** [comment]
Requirement Approved by @vinpahilwani over phone,

**Comment by mitulpanch** [comment]
> 3. Currently Planned for Add Service only

Add Service and Remove Service only
Change Service not required

> 4. Matching exact Count of Companies is difficult task, as multiple users work on same page
> 5. Delayed result is difficult to understand for End users

Not required to do anything by System, User can understand this

**Comment by sureshsirvi** [comment]
> We need this but right now its not priority, we can postpone it for later date

Recently i have attempted to setup ECB for Aklaecha And Associates.. During Setup i need facility to add GSTR-3B and GSTR-1 Services to more then 400 companies.. 

Hence it is required on first time onboarding new companies.

**Comment by sureshsirvi** [comment]
> > 3. Currently Planned for Add Service only
> 
> Add Service and Remove Service only Change Service not required

We need both Add Service and Remove service ... Change service is not required.

**Comment by sureshsirvi** [comment]
> > 3. Currently Planned for Add Service only
> 
> Add Service and Remove Service only Change Service not required

We need both Add Service and Remove service ... Change service is not required.
