### ISSUE TITLE
Company Page - Service Scheduler adds services that are not recurring

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1510]
Problem -
System Auto adds Service(s) that are non recurring

Solution - Only Add Service(s) that are recurring

Technical Information-
Previous Module was adding all service that are recurring / non recurring
because previous module was combine , for billing and Project Schedule, so that behavior was good,
but after Company page Restructure this is left out

Initially reported by Ashok Bhurani
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
All changes done, now this should work correctly,

Now checking Service that is Auto Added to Company,
Only Recurring Service at time of Project Creation or Triggered Time gets added to Company

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/e239a1a3-5ffa-5ddb-a4b5-1e36a73f1455

**Comment by mitulpanch** [comment]
Company - Service Custom Fields comes from this , removing this will lead to Custom Field Miss, as Company selected services are only recurring service, Per project related service are not applicable anywhere , so custom field from that Company - Service will go missing
