### ISSUE TITLE
Scheduler Page - Remove Month Selection option from Monthly Pattern

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1511]
Problem -
Monthly Pattern gives Month Selection option that is also not giving any option to change month
this gives confusion to end user that, they can change Month
Even error is not possible because only current Month is enabled

Developer taken care that user can not select any other month, so error is not possible
just user gets confuse due to month change option

Solution-
hide month selection option in Monthly Pattern

Initially reported by Ashok Bhurani, Vinod Pahilwani
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
also hide month option in Quarterly option, as it is not relevant

**Comment by mitulpanch** [comment]
approved by @vinpahilwani

**Comment by mitulpanch** [comment]
do this on Quaterly, Monthly, Bi-Monthly, Half-yearly

**Comment by Avinash-ecb** [comment]
Quaterly
![image](https://user-images.githubusercontent.com/46588125/184804324-2628157a-63b5-4114-a05d-584a1ece0fc1.png)

Monthly
![image](https://user-images.githubusercontent.com/46588125/184804434-eb542242-890c-436d-984d-0d809d2984d7.png)

Bi -Monthly
![image](https://user-images.githubusercontent.com/46588125/184804653-dddc2324-ad5c-4e71-9a85-27f4ece03344.png)

**Comment by Avinash-ecb** [comment]
Month selection is showing in Quaterly, Monthly, Bi-Monthly

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/d43dc4fe-e547-5ec9-a68d-e202fee88b8e
