### ISSUE TITLE
Project Page - Change Default Sorting

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1512]
Current Sorting is Create Date ascending

Problem - 
Note Reminder missed missing due to default sorting
even Sort is not possible, as it Sorts Status (In progress, On hold, ), this only helps in case of Combine view which have multiple statuses for Projects

Solution -
Default Sort should be Note date descending, so End User work on pending Project which needs Attention 

Other Functionality-
This may give problem to users who Creates Project and wants to See Project on Top

Initially reported by @vinpahilwani , Ashok Bhurani
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
Technical -
change default sorting to notedate desc

**Comment by vinpahilwani** [comment]
Approved from my side

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/8ba08c7e-d84f-58a1-8790-2e75c463019f

Date order should be ascending order
