### ISSUE TITLE
Project Page - Required Note Prospective

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1513]

**Comment by vinpahilwani** [comment]
We need note perspective to show filtered projects (red projects) requiring status note update

**Comment by vinpahilwani** [comment]
we need to develop discipline among users to do process red projects first in the morning 

1. process red projects on lead then
2. process red projects on hold then
3. process red projects in prgross
4. highlight projects which he want to focus from in progress today, to make everyone know whats coming up

**Comment by vinpahilwani** [comment]
Approved from my side

**Comment by vinpahilwani** [comment]
We need common star functionality with this as well @sureshsirvi @mitulpanch

**Comment by mitulpanch** [comment]
Create New View for each filter is not good choice, if anything do able with Filter than that is advised,

completely due to technical difficulties and handling all view together is difficult in long run

**Comment by mitulpanch** [comment]
No of things user can do -
1. Query Builder is available to find those project whose note date is missing
2. Default Sort is already showing missing First
3. We have Home page Gadget for that
4. Lastly we can provide another filter for special needs

**Comment by vinpahilwani** [comment]
We need star to prioritize work which is being shared so that the owner as well as project manager and those project members so that they have common understanding what is important and urgent now. I would vote for "common star"

**Comment by sureshsirvi** [comment]
> We need star to prioritize work which is being shared so that the owner as well as project manager and those project members so that they have common understanding what is important and urgent now. I would vote for "common star"

I support "Common STAR" with following settings

1. STAR on projects is some times used by Project manager for its projects identification. 
2. Some times Admin also wants common STAR to convey high priority projects to all staffs. 

Currently it is used both way.

A Firm shoud have option for their own policy how to use this STAR functionality.

Sollution
1. We can provide setting on setting page for behavior of  "STAR" as common or userwise on project pages.

**Comment by mitulpanch** [comment]
Other Start issue already exists, so closing this

**Comment by mitulpanch** [comment]
#1516
