### ISSUE TITLE
Company Page - Auto Billing - Quick Settings

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1520]
Problem -
1. Current Module works Perfectly, but making Setting for Each Client is time consuming
2. Initially it was stated as "Contact is responsible Task, it need to done one by one, so checking and setting prices are required, system generated price, setting is not good practice"
3. some clients want this as "Fast / Quick setting without splitting in exact amount / service structure"
4. Client want to just select Services for which their Client is billed for - ie. ( Raj Associates wants to provide only Total Service they are offering to Mitul Panchal(Client) like 105000 rs per year, and they want to select dates on which Mitul would pay like (every month on 5th)).

Solution-
1. Adding Quick Setting Option inside Auto Billing Popout.
2. this will ask - Dates only with Price column
      Date                        Prices
      05/05/2022             25000
      05/10/2022             30000
3. each time dates is added Prices will be auto average to speed up / lower input
4. so ideal flow would be Add All dates then change Prices
5. some preset option was required by @sureshsirvi , like 
    Add Monthly - Add 12 dates of each month on 5th, 
    Quarterly - add 4 dates according to financial year - 5th of Apr, Jul, Oct, Jan
6. Tax and Note settings are also taken.
7. finally at time of save, System will remove All Previous Settings, and will create new setting according to this
    ie. Quarterly will create 4 date with all Service applicable on Client, with same tax settings / Note
8. Add Warning Message before Save
9. This is sub module that create ideal setting in single popout, no alternation needed in existing Module

Technical -
1. this module is setting creation module, so not code changes required in execution
2. quick setting will remove all current settings
3. Average prices will be taken for quick inputs as client only interested in Total Amount and Date
4. Initially it was given as Wizard but too much design changes was not suggested to single popout was selected

following Video is just visualization -
Above things are finalized
https://www.berrycast.com/conversations/eb266c3e-c5e4-58fd-bac5-15b1cc686b32

**Comment by mitulpanch** [comment]
Initially reported by - ECB Client(Saidulu diddi)
Verified by @vinpahilwani , @mitulpanch

**Comment by mitulpanch** [comment]
split of Money 
below example shows
Services - 2 (service1, service2)
Dates - 3 (1st may 22, 1st june 22, 1st july 22)

Total Money - 13000
Service 1 - 5000 per year
Service 2 - 8000 per year

1st may 22 - 3000 rs 
1st june 22 - 4500 rs
1st july 22 -  5500 rs




![image](https://user-images.githubusercontent.com/5259926/184787486-5e9bc592-49cc-43c6-8e1d-2e4b2fed71c1.png)

**Comment by mitulpanch** [comment]
@vinpahilwani insist on average out all value, don't give option to users, only give dates option
average out money ie 13000 total for all service then take 13000 / 3 = 4333 rs on each dates

I insist on give date and money option, Money is auto filled base on no of dates selected averaged out, but this give use option to take 3000 on first date and 5000 on last date(instead of 13000 / 3 on each dates without change option)

@vinpahilwani suggest user will change this in edit mode in next step after saving this.

Averaging out will make another problem as this is basic requirement


problem - event if i don't give that option, that does not leave any work on me, both things take same development time, but end user tends to take finite , understandable figures on dates instead of average out

User behavior also tends to say, user wants to change values to different money on different dates,
 without taking extra input Money textbox is auto filled , averaged out automatically (so user who do not want to give any input , then auto filled is working great for them)

We can help them out with their doubt annual amount total,  remainder, like we help on individual steps while setting for different date on initial behavior

this will help user clear all setting in single popup window, if user still wants to change service vise price then they would continue with individual date setting after saving this.

**Comment by mitulpanch** [comment]
Edit is not Possible in Quick Setting. as this will reset all Date Settings

**Comment by mitulpanch** [comment]
![image](https://user-images.githubusercontent.com/5259926/186186837-0ef14f56-89d3-430e-a5e3-e3f98a56c042.png)
Quick Settings => Move this to Billing Dates row as shown in image

Total of billing dates -> shift this to below list (same design as "Total Annual Fees" (purple design row ))

by @vinpahilwani over phone

**Comment by mitulpanch** [comment]
![image](https://user-images.githubusercontent.com/5259926/186187566-7cca556d-0d37-4a6a-a990-1d5fe073e813.png)

Design approved over phone

**Comment by mitulpanch** [comment]
![image](https://user-images.githubusercontent.com/5259926/186187760-b1813673-6858-4a23-8293-9b158f6cc731.png)

Preset design -> more preset requested to @vinpahilwani , @sureshsirvi for fast setting to end users
ie (examples) Quarterly Starting -> 1st of Quarter
Quarterly Endings -> 30th of Quarter

**Comment by mitulpanch** [comment]
> split of Money below example shows Services - 2 (service1, service2) Dates - 3 (1st may 22, 1st June 22, 1st July 22)
> 
> Total Money - 13000 Service 1 - 5000 per year Service 2 - 8000 per year
> 
> 1st may 22 - 3000 rs 1st june 22 - 4500 rs 1st july 22 - 5500 rs
> 
> ![image](https://user-images.githubusercontent.com/5259926/184787486-5e9bc592-49cc-43c6-8e1d-2e4b2fed71c1.png)

this logic works perfectly in case of possible valid amount, but huge different amount gets in problem
ie. Service total is 13000 and on date someone want to take 10 Rs. this is huge difference amount and Auto fill login fails / or gives unexpected values because averaging out is not possible

**Comment by vinpahilwani** [comment]
approved

**Comment by mitulpanch** [comment]
Available to Testing companies

**Comment by sureshsirvi** [comment]
Following changes are suggested.
1. We need click on "Total Annually Fees" to add service.

![Image](https://user-images.githubusercontent.com/46813198/186825132-ec3223e1-c1e4-41de-9e5d-8df53c97e41b.png)

2. We need "Clear All" Button to remove all present schedule.
3. In "Quick Setting" When we select a particular date then all monthly or Quaterly schedule should be repeated on selected date.

https://www.berrycast.com/conversations/5031b7f7-a2dc-509d-9ad6-f219f4cbad4a

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/4339db77-7db6-5b8e-9c57-f647c078522e
