### ISSUE TITLE
Project Page - project manager hover change title

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1521]
Show project manager name - team pending

On hover

"Ashok bhurani - Team Pending" whem pending

Or

"Ashok Bhurani" when team is present

Initially reported by @vinpahilwani 
Verified by @mitulpanch

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/184797147-6e6a096b-9587-4f3e-b542-a431f9883377.png)

**Comment by mitulpanch** [comment]
on where "?" is implemented

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/eaf9ebb8-30bc-5470-8e91-3eff4c58bac1
