### ISSUE TITLE
Project Page - Todo going back to first Stage keeps last moved by

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1522]
Problem -
1. End user moves todo to in progress.
2. now todo is assigned to user.
3.  then shifts it back to first stage.
4. but todo still assigned to user.

solution
1. when todo is moved to first stage - last assigned member should be removed

Initially reported by @vinpahilwani 
verified by @mitulpanch

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/c1ac0b0e-8263-5b85-87e1-2077f6a99fd2
