### ISSUE TITLE
Project Page - Work done - should be allowed to all users

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1523]
Problem -
1. Work Done button is currently visible to only members
2. @vinpahilwani suggested to open it for all users. so all user with or without project manager rights can use this
3. Multiple Project Manager can use this button to exit project, when other manger is handling project

Solution-
1. Allow all end user to see this button
2. don't hide from anyone, show it to everybody
3. Don't allow last Manager to exit project, anybody can exit project until last project manager 
4. Project requires at least one project manager

Technical Rule-
1. Allow any one to exit project, only check if there is other project manger exist in project

Initially reported by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
#1504  this issue change functionality of Leave Project  Work done initially committed

**Comment by vinpahilwani** [comment]
1. "suggested to open it for all users. so all user with or without project manager rights can use this". I guess this button will not be available to owner who is not on project
2. Allow any one to exit project, only check if there is other project manger exist in project - yeh samajh nahi aaya

Rest all things are ok we can proceed

**Comment by mitulpanch** [comment]
> 2. Allow any one to exit project, only check if there is other project manger exist in project

validation to exit project is , if any other project manger is exist then user can exit project, removing himself from project.

> 1.  "suggested to open it for all users. so all user with or without project manager rights can use this"

now "Work Done" button available to all member who are manager or member to project. at time of save , backend check for if any other project manager is present in project.

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/cb03495c-9a82-53d9-8fac-4de151e0180f
