### ISSUE TITLE
EXCEL DOWNLOAD BUTTON IN ACCOUNTS SECTION

### ISSUE THREAD

**Issue by amitkjainbaid** [Fammeo/EasyCloudBooks#153]
AS ACCOUNTS HAS TO BE DONE THROUGH ACCOUNTING SOFTWARE , THERE SHOULD BE EXCEL DOWNLOAD BUTTON TO GIVE CASH BOOK, BANK BOOK AND ADJUSTMENT BOOK TO ACCOUNTANT FOR SPECIFIED PERIOD. IT SHOULD BE SUCH EASY MODE THAT A LAYMAN ADMIN SHOULD BE ABLE TO DOWNLOAD AND GIVE TO ACCOUNTANT WITH EASE.

ACCORDINGLY ACCOUNTS AND VOCHERS SHOULD ALSO BE MADE DOWNLOADABE. FEATUREWS SUCH AS GROUP LEDGER DOWNLOAD WITH SPECIFYING PERIOD SHOULD BE THERE.

**Comment by mitulpanch** [comment]
Try to do this with Export Module
