### ISSUE TITLE
Project Page - Have Team option - Design Change

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1531]
Problem -
1. People who are not using Team concept are against this. as they use only one person per project style
2. They don't want "?" over Project Manager icon, they just want old clean design without "?"

Suggested Solution by @vinpahilwani 
1. Give Other icon for Having Team, instead of Not having Team.
2. Don't give anything on icon who does not have team
3. Create some other design to overcome hidden Project Manager Photo

Revert - 
1. #1505 issue worked Correctly, there was not discussion about this
2. This issue will reverse all thing done by #1505 

Design -
Still getting inputs from design team

Initiated by @sureshsirvi 
Verified by  @vinpahilwani

**Comment by vinpahilwani** [comment]
Approved

**Comment by sureshsirvi** [comment]
Design Issue:

Problem:

1. Some users are using as single member in Projects... they are facing always "?" on project instead of Image of Project Manager.. 

Sollution:

1. I suggest, use Red ring Circle around the PM image. OR
2. We can provide filter option.

**Comment by dharmendraecb** [comment]
Blinking at very low rate, to show who is Project Manager, this was issue for @sureshsirvi  and others, when they are assigning work ,
https://user-images.githubusercontent.com/46588108/186639791-c3d91ca1-1172-4772-a1d9-66b4bc2c7e68.mp4

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/186639972-a8ea3e51-42c2-4b37-8581-1230d9d88822.png)
this is without blinking

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/186640097-67f066c8-aaa9-4399-98e2-e8c91b49a3b3.png)

**Comment by mitulpanch** [comment]
this is animated

![Image](https://user-images.githubusercontent.com/5259926/186888181-14412539-94ad-4d2b-afca-b1262f241e00.gif)

**Comment by vinpahilwani** [comment]
Yes Blinking is fine

**Comment by dharmendraecb** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/46588108/186895297-c5cb824b-1a54-4b7b-9f3a-3d17e3169d7a.gif)

We can make this design more compact, better in view
this will take very small space, but we can give user different kind of attention to it, with animation to show errors
This design is not for everywhere, only on list  for now

**Comment by sureshsirvi** [comment]
https://github.com/Fammeo/EasyCloudBooks/issues/1531#issuecomment-1228386895

![Image](https://user-images.githubusercontent.com/46813198/187119011-de08a86d-85f2-4ee1-aa91-1590f2943510.png)

I approve the above design.

**Comment by vinpahilwani** [comment]
No problem

**Comment by mitulpanch** [comment]
Please Suggest any thing else if you want to add,
1. Have Team than Icon / still if continue for if don't have team them show some icon
2. any other metric

**Comment by sureshsirvi** [comment]
> Please Suggest any thing else if you want to add,
> 
> 1. Have Team than Icon / still if continue for if don't have team them show some icon
> 2. any other metric

Currently no need for any other metric.

**Comment by mitulpanch** [comment]
Trying Fade with 5 Sec frequency
with Minimum design impact,

@vinpahilwani do you still need Team have Option? or Previous Team Pending icon will be good?

**Comment by vinpahilwani** [comment]
You mean question marke jaisa abhi hai?

**Comment by mitulpanch** [comment]
Yes, if purpose of redesign was
1. Only single managers structure dobt want to see this
2. Cant see whos manager

As we are making new design, we need too think about show symbol for not having team or show symbol for having team

**Comment by vinpahilwani** [comment]
No problem - Use Yellow Color not the Red Color, Red color unko hurt karta hai

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/ff18a99d-f6c4-557b-be13-a71e83dfee92
![image](https://user-images.githubusercontent.com/46588125/188547121-2f278a83-886e-48b3-8112-5fec1f80f9fd.png)
