### ISSUE TITLE
Custom Field Setting Page - Split into 4 section

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1532]
Split Setting Page into 4 Parts
1. Company & Company-Service Section - Design on Company Custom Field List Page
2. Project & Project-Service Section - Design on Project Custom Field List Page
3. Contact Section - Design on Contact Custom Field List Page
4. Staff Section - Implementation Pending

This all Section will Open Setting from Side Popout on respective Pages

Problem -
1. there was no Problem
2. but in favor of User, who can do setting on individual page easiness this is suggested

Suggested Solution -
1. Split Current Custom Field Setting Page into 4 different Section on individual page
2. Remove Custom Field Setting Page
3. Roles have no change, they comes from Custom Field - Role as Currently Going

Initiated by @vinpahilwani

**Comment by vinpahilwani** [comment]
The above things are fine but i need something more related to how we can share it with clients

**Comment by mitulpanch** [comment]
on hold till further discussion about other requirements

**Comment by sureshsirvi** [comment]
Requirements
1. In custom filed we required "PASSWORD" Type feature.
![image](https://user-images.githubusercontent.com/46813198/188258529-5e2e516d-4b1a-4760-ae6d-883c332b98e7.png)

**Comment by sureshsirvi** [comment]
> Split Setting Page into 4 Parts
> 
> 1. Company & Company-Service Section - Design on Company Custom Field List Page
> 2. Project & Project-Service Section - Design on Project Custom Field List Page
> 3. Contact Section - Design on Contact Custom Field List Page
> 4. Staff Section - Implementation Pending
> 
> This all Section will Open Setting from Side Popout on respective Pages
> 
> Problem -
> 
> 1. there was no Problem
> 2. but in favor of User, who can do setting on individual page easiness this is suggested
> 
> Suggested Solution -
> 
> 1. Split Current Custom Field Setting Page into 4 different Section on individual page
> 2. Remove Custom Field Setting Page
> 3. Roles have no change, they comes from Custom Field - Role as Currently Going
> 
> Initiated by @vinpahilwani

I Agreed with this setting changes.

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/203516013-4f786c57-797c-4b98-83f3-97a90d1f8238.png)
![image](https://user-images.githubusercontent.com/46588125/203516093-173ab474-addb-45fd-8509-55b92ce40456.png)
![image](https://user-images.githubusercontent.com/46588125/203516163-b2959400-803d-4a23-9f44-0dcccd2eaf7c.png)
