### ISSUE TITLE
Company Custom Field - Add Setting in Popover

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1533]
as #1532 suggested 
This is sub Issue to Track Individual Progress

Problem-
1. Move existing Custom Field Setting Page in side Popover on Company Custom Field List Page

Design
1. Settings will come in side Popover
2. No Role Change - Role will be - Custom Field Role
3. Apply To Option is not Required, as this setting is for Company & Company-Service Setting, Although Company OR Company-Service selection is Required, (Selection box - 1. For All Company(Company) 2. Service-wise(Company-Service))
4. For Service-wise Selection Services need to be Selected
    Design for Service Selection will be
    Service List Popout
        Sort - Alphabetical ascending
        Selection - Selected Service 
        Filter - No filter option
        Grouping - No Option
        Paging - 20 
        Beyond Selection- selection should hold selected service when Paging changes
    So end user can select / change Service
5. Design should be as same as Company Page Service Selection to simple design and commonness for Service Selection on different Pages
6. show Service Total in first Step, this on total Click, Service Selection Popout will open

initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by Avinash-ecb** [comment]
There is not read role for customfield setting page then also we can see customfield 
![image](https://user-images.githubusercontent.com/46588125/204744790-158a886e-906f-43c6-be96-b860f0a977ac.png)
![image](https://user-images.githubusercontent.com/46588125/204744844-daca7a13-2489-40af-80ab-65ae061d745d.png)
![image](https://user-images.githubusercontent.com/46588125/204744873-c75ba85d-43f8-4f42-92ee-a1aa8494a1e7.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/221804873-17eb1240-c2d7-4d2c-b02f-a9fff3f7df34.png)
