### ISSUE TITLE
Project Custom Field - Add Setting in Popover

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1534]
as #1532 suggested
This is sub Issue to Track Individual Progress

Problem-

Move existing Custom Field Setting Page in side Popover on Project Custom Field List Page
Design

Settings will come in side Popover
1. No Role Change - Role will be - Custom Field Role
2. Apply To Option is not Required, as this setting is for Project & Project -Service Setting, Although Project OR Project-Service 
    selection is Required, (Selection box - 1. For All Project (Project) 2. Service-wise(Project-Service))
3. For Service-wise Selection Services need to be Selected
    Design for Service Selection will be
         Service List Popout
            Sort - Alphabetical ascending
            Selection - Selected Service
            Filter - No filter option
            Grouping - No Option
            Paging - 20
            Beyond Selection- selection should hold selected service when Paging changes
           So end user can select / change Service
4. Design should be as same as Company Page Service Selection to simple design and commonness for Service Selection on different Pages
5. show Service Total in first Step, this on total Click, Service Selection Popout will open

initiated by @vinpahilwani
Verified by @mitulpanch

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/204780847-9afbfab1-5211-456b-ae49-70f4760a515a.png)
![image](https://user-images.githubusercontent.com/46588125/204780728-7837296d-5069-43a4-8332-836d76b87cb6.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/221792111-ee4ddf77-09f9-4b3d-a977-62c3ca68e016.png)
