### ISSUE TITLE
Contact Custom Field Page - Add Setting in Popover

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1535]
as #1532 suggested 
This is sub Issue to Track Individual Progress

Problem-
1. Move existing Custom Field Setting Page in side Popover on Contact Custom Field List Page

Design
1. Settings will come in side Popover
2. No Role Change - Role will be - Custom Field Role
3. Apply To Option is not Required, as this setting is for Contact

initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by Avinash-ecb** [comment]
User does not have customfield page read permission then also user can see setting page customfield
![image](https://user-images.githubusercontent.com/46588125/204714568-1c5d366a-9adb-4838-b84c-aa372d677b20.png)
![image](https://user-images.githubusercontent.com/46588125/204714596-5960a9de-d334-49c4-8578-aa377a3910a5.png)
https://www.berrycast.com/conversations/5f19825a-2e14-5077-8a43-dffb011594cb

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/221787332-ea06ac4b-4f0b-49a1-b637-e8b638797d0c.png)
