### ISSUE TITLE
Company Contract - Auto Billing for Recurring Service - Change Auto Suggest Service Behavior

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1537]
Current -
1. Auto Billing "+Attach" currently suggest Service that are in manner Recurring (on Service Page) and Project for respective service exist in Past 3 Year
     ie. System gets Project in Past 3 year for Recurring service for Client
2. This was build in mapping with "+Attach" Service in Per-Project Billing

Problem
1. The Service that Currently not Offering also comes in suggested Service when We click "+Attach" on Recurring Service Auto Billing
2. These services were offered in past but as per current setting these services wont be offered anymore, so not required in suggested service

Suggested Solution-
1. if Service Scheduler has services that are offered to Client, then bring services that are present in setting
    ie.  Services offered to Company on Contact Page, set for auto Create Project
2. only apply current login when no Setting Present for Service Scheduler
3. this gives better filtrations who are using both modules, and service they don't offer now wont come to suggested service list

initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by vinpahilwani** [comment]
I am satisfied with the suggested solution except point number 2 in suggested solution

**Comment by mitulpanch** [comment]
@vinpahilwani sir Do you need 2nd point or We need to remove that?

**Comment by mitulpanch** [comment]
Initial +Attach was created based on whenever Project Created then Auto Add Service in Auto Billing module was requested, but this would lead to too much overhead for each project action, so + Attach Button suggested with same effect but only after Click.

**Comment by mitulpanch** [comment]
Behavior-
1. Only give Service that are present on 1st step of Recurring Service Offered to Company
2. If nothing present on Recurring Service, and user asking for Suggestion give past 3 year Recurring service Company has taken , as suggestion that these are the services you offered to Company in past

Meaning of +Attach is to give Suggestion to user, what kind of service Company is taking
