### ISSUE TITLE
Contact Page - when create contact first email  and contact check box should be check By Suresh Sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1546]
**Describe the bug**
- when we create contact first email and contact should be already checked for sending email and SMS

![image](https://user-images.githubusercontent.com/46588125/186070069-e41c43cc-ac78-4c82-bf2a-ff526d3d208e.png)

**Comment by mitulpanch** [comment]
#1708 clash with this

**Comment by mitulpanch** [comment]
so ignoring this issue in favour of other issue

but i take this a input to provide some easiness to take consent from client
