### ISSUE TITLE
Company Page - Transaction Create should Auto Fill Company Name

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1548]
Problem -
1. user flow - on Company Page - Ledger View - open Company Details (Transaction list with Company Filter) - Click Create new Transaction (opens Transaction create window)
2. End User expects that Company is selected, but they need to select Company again

Suggested Solution-
1. Auto Fill Company when possible

Technical Problems-
1. CRId and Name needs to be passed between popovers, that is not implemented everywhere
2. This need 2 hours of time every where this needed

Currently suggested for above flow only
Create Possibility to set for other places but completes only when required by end user

Reported by - @vinpahilwani
Verified by @mitulpanch

**Comment by vinpahilwani** [comment]
yes rquired

**Comment by sureshsirvi** [comment]
ok. currently we need it only on above suggested pages.

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/e20ebe1d-ffc7-5cdf-b7e9-937a84744ae7
