### ISSUE TITLE
Trasaction Page - Create Transaction Receipt Payment Mode Auto complete should take typed input

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1549]
Problem-
1. User types "cash" in Auto complete, and saves, but its saved as different entry, then "cash" and "Cash" are different

Suggested Solution-
1. Typed input should be taken

Technical details
1. Autocomplete plugin dont accept typed input, it takes that as new Entry, Selection of existing entry will prevent this
2. Payment Mode selection- is case Sensitive, so "cash" & "Cash" is different
3. If we want this to be implemented, user typed case ie "Cash" will lose its case and will become something fixed case, ie "cash", "Cash", "casH" all will become "Cash", "Bank-DRAFT" will become "Bank-draft", this is required to stop duplicate entries

**Comment by mitulpanch** [comment]
Initiated By @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
![image](https://user-images.githubusercontent.com/5259926/186177142-73f3fe84-4461-430a-84b4-7fdb45ff0290.png)

**Comment by vinpahilwani** [comment]
yes this is required

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/6ac43294-1708-5bfc-9e00-c6314f72d83f
