### ISSUE TITLE
Company Page - Showing 20 service instead of 23 service  By Suresh sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1553]
**Describe the bug**
- there is 23 service but only showing 20 service 
![image](https://user-images.githubusercontent.com/46588125/186824242-0292466c-bc4a-44e4-8517-c1568e9dcaef.png)
https://www.berrycast.com/conversations/8a6a84b0-502f-5559-b857-13b65fe806fc

**Comment by mitulpanch** [comment]
Problem Statement?
Kisko chahiye?
Any other Option?

**Comment by mitulpanch** [comment]
dont merge 2 different issue in 1
23 service ke jagah 20 aa rahi he? ye kya he?

dont just add issue, check background, if any details,

**Comment by mitulpanch** [comment]
Create Different issues with details

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/8a6a84b0-502f-5559-b857-13b65fe806fc

**Comment by mitulpanch** [comment]
Error Details-
Multiple Company Selection  -> Add Service -> gives only 1st Page , 20 Services,

paging required

**Comment by mitulpanch** [comment]
Initiated By @sureshsirvi 
Verified by @Avinash-ecb

**Comment by Avinash-ecb** [comment]
When adding multiple service there is showing all service which are recurring and non recurring , recurring service should be there and user can not change that "have recurring filter"
![image](https://user-images.githubusercontent.com/46588125/187346023-b4144dd0-7796-47a6-87cf-1ab51900607f.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/188542084-d2e2ce34-92a6-4e24-92b8-4ace4e171149.png)
