### ISSUE TITLE
Company Page - required project status change button in project view By Suresh Sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1555]
**Describe the bug**
required project status change button
![image](https://user-images.githubusercontent.com/46588125/186824098-95484a3c-d92d-4ff6-af02-7326c5b39909.png)

**Comment by mitulpanch** [comment]
over to @vinpahilwani

**Comment by mitulpanch** [comment]
Problem Statement Missing!!

**Comment by mitulpanch** [comment]
We have not provided Multiple Action Button to any Popovers

**Comment by mitulpanch** [comment]
Please Provide Scope to where this need to come ? with Which Roles?

**Comment by vinpahilwani** [comment]
@sureshsirvi samajh me aaye aisa likho

**Comment by vinpahilwani** [comment]
@mitulpanch plz help me understand

**Comment by mitulpanch** [comment]
> @mitulpanch plz help me understand

Multiple Action button required here, as shown in above image, in side popover

**Comment by sureshsirvi** [comment]
Problem Statement:
1. User deficultiy is when user comes to project popover from company page during the presence of clients .. then their is multiple projects pending for such client and all are on lead .. but it the time of meeting with clients it comes to in knowledge that we have received all documents but project status is not updated and now we wants to update all projects. here we required Action Button.
2. In the same above issue we also need it to add Multi TAG on projects for project popover page.

**Comment by mitulpanch** [comment]
#1712 can solve this

**Comment by mitulpanch** [comment]
Closing this issue in favor of #1712 
Both are same
