### ISSUE TITLE
Pabbly Connect - Intigration

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1556]
Problem - 
To Create new Funnel for onboarding Company and Staff new push required

Solution-
Push Company Create / Staff Join event to Pabbly webhook

initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by vinpahilwani** [comment]
@Avinash-ecb i need your help in this

**Comment by mitulpanch** [comment]
2 different workflow given - on pabbly
