### ISSUE TITLE
Company Page - Contract Quick Settings - Design Changes

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1557]
Following changes are suggested.
1. We need click on "Total Annually Fees" to add service.

![Image](https://user-images.githubusercontent.com/46813198/186825132-ec3223e1-c1e4-41de-9e5d-8df53c97e41b.png)

2. We need "Clear All" Button to remove all present schedule.
3. In "Quick Setting" When we select a particular date then all monthly or Quaterly schedule should be repeated on selected date.

https://www.berrycast.com/conversations/5031b7f7-a2dc-509d-9ad6-f219f4cbad4a

_Originally posted by @sureshsirvi in https://github.com/Fammeo/EasyCloudBooks/issues/1520#issuecomment-1228054896_

**Comment by mitulpanch** [comment]
Creating Same thing on different button makes things difficult to manage in terms of development, as future changes ke time ye nai yad rehta

**Comment by mitulpanch** [comment]
over to @vinpahilwani and @sureshsirvi

**Comment by vinpahilwani** [comment]
agar date 10/06/2012 aisa liya hai and phir woh monthly kar raha hai toh kya hoga? 12 mahine kaise pure honge?

**Comment by vinpahilwani** [comment]
uski jagah aisa karo ki upar se jab woh monthly, quarterly, half year aisa click kare toh udhar hi next step puche data and once he does that automatically hum dates create kare

**Comment by mitulpanch** [comment]
Initiated by @sureshsirvi

**Comment by sureshsirvi** [comment]
**Requirement:**

1. We need selection of date to repeat scheduler for each month.
2. When we select monthly option then irrespective of date or month already passed the scheduler must be created for all 12 months. Example if we select date 10/09/2022 and select option monthly then schedular must be created from 10 April to 10 March.

Over to @vinpahilwani

**Comment by vinpahilwani** [comment]
Yes nice. but only issue is mujhe invoice next month me karna hai toh? matlab april ka may, may ka june tab. Likewise first quarter ka invoice mujhe next quarter me toh? @sureshsirvi

**Comment by sureshsirvi** [comment]
> Yes nice. but only issue is mujhe invoice next month me karna hai toh? matlab april ka may, may ka june tab. Likewise first quarter ka invoice mujhe next quarter me toh? @sureshsirvi

I agree with vinod sir.. 
As we Select particular start date  then ther after all 12 months schedule to be created for the year.

**Comment by mitulpanch** [comment]
Clear All Button Required?

**Comment by vinpahilwani** [comment]
Yes clear required
