### ISSUE TITLE
Company Page - Per Project Billing - Auto Add Service

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1559]
Problem-
1. Current structure don't have problem, just enhance if someone wants to auto add service to per project billing
2. Per-project in a manner is no recurring services, but some client use Auto Billing to full potential, they might want to add services to Client if Project Created is Non-recurring then to per-project Billing.
3. This is only applicable if client is using scheduled Auto-billing for All Recurring Services and want to Auto-bill Per project for all remaining services. (in a way ECB will handle all billing)
4. This feature (Auto Add non recurring Service to per - project)  will automate billing for Client

Solution Suggested -
1. Auto Add Service to per-project Billing when Project is Created for a non-recurring Service with Service default Price
2. Remove Approved (Reviewed) state from Company Per-Project Auto Billing, so user can understand what is changed an take action on non-approved contracts

Technical Details-
1. finding Contract Year is difficult, as Project may have year / not, then Project Year belongs to 2 different Contract Years, we need  logic to overcome this
2. If someone don't want to auto add to Per-project Service than they don't have Option
3. If this happens, then Project Billing will start Automatically for project, this may create problem for user who don't want
4. More fine tuned rules required, to implement

Workaround
1. +Attach Option gives this, not Automatic only for whom they require

Initiated by @vinpahilwani 
Verified by @mitulpanch 

![image](https://user-images.githubusercontent.com/5259926/187028161-b461b137-cdcc-422e-ad63-ff2f85e0ac63.png)

**Comment by vinpahilwani** [comment]
one more enhacement needed is FOC service i.e. service for which there is not going to be any invoice. eg. client project related to refund enquiry and office admin project for eg. payment of monthly bills etc.

**Comment by sureshsirvi** [comment]
> one more enhacement needed is FOC service i.e. service for which there is not going to be any invoice. eg. client project related to refund enquiry and office admin project for eg. payment of monthly bills etc.

I agree with above requirement. 
There are some services for which billing is not required. These services are non billable service. it should not appear in unbilled project list.

**Comment by vinpahilwani** [comment]
1. Humko auto contract me add karna hai current year me
2. On off button hoga

**Comment by Avinash-ecb** [comment]
After discussion with @mitulpanch sir on phone it will show in company per project billing with untick and showing number in per project billing number
https://www.berrycast.com/conversations/1e9a2f26-68fe-5ef3-9085-4f2d2da8678c
