### ISSUE TITLE
Document Page - Migrate to new Theme

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1560]
Problem - 
1. Plugin which we are using is outdated, or not possible to migrate in new theme
2. We need Customized Paging in File list, Current Plugin do not support this
3. We need new Inline popover to View Related File, that is not possible with Plugins
4. Other Sorting , Uploading File can be improved

Suggested Solution
1. New Design with Paging, Sorting Filtering
2. Support for Popover design
3. Support for Customized View, Filtered View

Technical details-
1. Extensive Time required to migrate / develop / test new design
2. new API structure Required for design
3. Paging Filtering is tricky part as Parent GCP do support in limited way

**Comment by mitulpanch** [comment]
Please all add your requirement here
@vinpahilwani @sureshsirvi

**Comment by vinpahilwani** [comment]
@mitulpanch what is my role in this?

**Comment by mitulpanch** [comment]
I remember you suggested that, Popover of this page should come under Project Detail for Company documents without redirect

anything like this should be covered here

**Comment by mitulpanch** [comment]
There are 4 total Views
1. Company View - which requires Company Id to open
2. Common View - Common Files anybody in company can access
3. Vault View - shows some Private files with Roles
4. Public View - Any file saved here is Public to Internet, mostly used in Website section , File Uploads, Blog Images etc, bascially all files which are required with public url without login/ authentication

I suggest there should 3 Menu for documents 
1. Company and Common, as they both required at same time
              Common view has some common files that needs to share between all Companies
2. Vault View - for user who can access vault 
3. Public View - show all files used as public role

**Comment by mitulpanch** [comment]
Design -
1. Design will not have old plugin
2. Following theme


![Image](https://user-images.githubusercontent.com/5259926/187160047-68cde606-29c5-4680-809d-b50b109205ca.png)

This is good example

**Comment by mitulpanch** [comment]
3. Not suggesting any other plugins, just plane design will give as advantage to use it on any page
4. Multiple select and Copy, Cut Paste action will be good
5. Search , filter ,sorting, paging all present to search file easily

**Comment by mitulpanch** [comment]
6. Company selection will be at top and required, for Company view
7. On Project Section , Company view will be auto opened if no heavy plugins used

**Comment by vinpahilwani** [comment]
Kindly show who added this file i.e. added by

**Comment by mitulpanch** [comment]
not possible - that is going to Log entries

> Kindly show who added this file i.e. added by

**Comment by vinpahilwani** [comment]
Ok

**Comment by sureshsirvi** [comment]
Requirement:

1. Documents section is required on project page.
2. To maintain project wise documents, we need project wise folder / TAG to find out project related documents. Mean Whenever we open the project we can get documents relating to such project.

to @vinpahilwani

**Comment by vinpahilwani** [comment]
I had discussion with mitul and he says if I allow project files then project files will not be displayed in files section which will create confusion among users. 

I asked him then we should remove file section and only allow files on project, he does not agree with this idea also. 

Considering these things will confuse users i do not approve this

**Comment by vinpahilwani** [comment]
I had discussion with mitul and he says if I allow project files then project files will not be displayed in files section which will create confusion among users. 

I asked him then we should remove file section and only allow files on project, he does not agree with this idea also. 

Considering these things will confuse users i do not approve this

**Comment by mitulpanch** [comment]
https://github.com/Fammeo/EasyCloudBooks/issues/1560#issuecomment-1243229464

past comments are not valid anymore,
we have now developed new File Section like Custom Field called Custom File. with discussion with @vinpahilwani and @sureshsirvi

**Comment by mitulpanch** [comment]
still no discussion about this documents section,
I strongly believe that documents section is still required for Common Files, Vault, Public , Website related sections
