### ISSUE TITLE
Project Page - Project manager can update all working paper By Suresh Sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1562]
**Describe the bug**
- If one staff create working paper then project manager has right to update working paper 

**Suggestion**
- who create working paper he only can update working paper others can not update working paper created by him

**Comment by vinpahilwani** [comment]
this is what the intention is. No body can change working paper of another person even the owner of company or project manager

**Comment by sureshsirvi** [comment]
> this is what the intention is. No body can change working paper of another person even the owner of company or project manager

I agreed.

**Comment by sureshsirvi** [comment]
BUG

Currently if we add any user as Project Manager then it is allowing to change working .. that is to be restricted.

**Comment by Avinash-ecb** [comment]
Currently other user can not change working paper

https://www.berrycast.com/conversations/720eda34-4cf1-5313-8a8c-bf029ab877f5
