### ISSUE TITLE
Company Page - Auto Billing - Suggest Service Change Behavior

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1563]
Problem-
1. +Attach Service only appends services to list
2. User need to remove previous services, which are not offered from Service Scheduler attached service to Company

Suggested Solution -
Remove Service which are not present on Service Scheduler on company

Technical Details
1. We have not developed any thing for removing, 
2. Initial was to suggest service

This change #1537 again

**Comment by vinpahilwani** [comment]
approved
