### ISSUE TITLE
Service Page - Recurring / Non Recurring Option change

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1564]
Problem-
1. Currently this option decides that 1st step on Company page (Recurring Service / Service Scheduler), if this option is ON (Recurring Service) then service will be available in 1st step(Recurring Service), and 2nd step (Auto Billing - Scheduler)
2. If some use want to create project in schedule basis and doing billing in Per-Project basis, then this going to give them problem

Suggested Solution-
1. Change this Option to 3 Option Selection - 1. Scheduled Billing 2. Per-Project Billing 3. Non-Billable Service
2. "Scheduled Billing" this option will give Service Selection option in 2nd step of Company (Auto billing- Scheduled)
3. "Per-Project Billing" this option will give Service Selection option in 3rd step of Company (Per-Project Billing)
4. "Non-billable Service" this will prevent service to be available in any of the steps, basically this is free service and no project will be billed related to this service
5. 1st step of Company Page (recurring Service / Service Scheduler) will have different Option depend on Recurring Scheduler Added or not, now onward this Option will not contribute to 1st step

Technical Detail
1. this will change lot of things, 1st , 2nd , 3rd stage of company page, service now requires api changes
2. 3rd option (Non-Billable Service) this needs to added to wherever Billable Project Logic is applied, some of them are - 1. Transaction Page - Unbilled Project, Project List - Unbilled Project, Query Builder - Unbilled Project query and more, This will take lot of searching time

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
Design - 
Instead of On/Off button,
this will be Selection Box with 3 Options
1. Scheduled Billing
2. Per-Project Billing
3. Non-Billable

**Comment by vinpahilwani** [comment]
approved

**Comment by mitulpanch** [comment]
#1559 also has this in discussion

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/c86843b3-b107-5134-ad7d-c69d80eb007e
https://www.berrycast.com/conversations/d79e6642-1a19-5055-8e24-0f5366c15e30
![image](https://user-images.githubusercontent.com/46588125/190964685-2ce5ceba-9812-417e-b5c9-5750f4c9c177.png)
