### ISSUE TITLE
Company Page - Service Page - Recurring Service / Service Scheduler - Change Behavior

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1565]
Problem -
1. Currently Service which are Selected as Recurring on Service Page comes to This
2. But That settings is now dedicated to Billing related details
#1564 Issue is partially related to this

Suggested Solution-
1. Bring Services which have at least one Scheduler added to Service Scheduler on Service Page

Technical Details
1. 1st Step of Company Page requires new API changes

**Comment by mitulpanch** [comment]
Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by vinpahilwani** [comment]
approved

**Comment by sureshsirvi** [comment]
ok

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/87f05b7b-a548-5dd8-9c9e-e8ad2cdf2be8
