### ISSUE TITLE
Company Page - Custom Field for Non recurring Service - No Possible way to add

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1566]
Problem -
1. Before "Company Page" Auto Billing changes
2. Company Services (now "Recurring Services") Field was accepting All Service which a Company is Taking (Recurring / Non-Recurring)
3. Project are scheduled if Service has Scheduler and Company is attached for Service
4. Now after Auto billing -
    1. Company Services is now "Recurring Services" and not accepting any Services which are non-recurring 
    2. so any user who are providing non-recurring service to Company , and have custom field set for Service for Company, are not accepting or no option at all
    3. there should be any way at least

Suggested Solution
1. None

initiated by @mitulpanch 
verified by @vinpahilwani

**Comment by mitulpanch** [comment]
My take on this
1. There should at least Option to support Other type of User
2. If Process Flow can create Project of any Service (Recurring / Non recurring) beyond any settings, this will make things worse for Automation friendly Customers
3. Any kind of Third Party integrations will require this
4. A User create Project in No of manners, not only straight way every time
5. Software should have All easy Option without Ignoring Advance Users
6. Process Flow is the Future, when we integrate with Other Software this will lead to lot of Problems, because of non support of  advance structures

**Comment by vinpahilwani** [comment]
I think this is taken care by 
1. Company custom fields
2. Company custom fields based on legal structure field (new feature as suggested by me)

**Comment by sureshsirvi** [comment]
> My take on this
> 
> 1. There should at least Option to support Other type of User
> 2. If Process Flow can create Project of any Service (Recurring / Non recurring) beyond any settings, this will make things worse for Automation friendly Customers
> 3. Any kind of Third Party integrations will require this
> 4. A User create Project in No of manners, not only straight way every time
> 5. Software should have All easy Option without Ignoring Advance Users
> 6. Process Flow is the Future, when we integrate with Other Software this will lead to lot of Problems, because of non support of  advance structures

We can have alternate sollution for Point No 2 for Project Creation...is that we can provide ADD Service and REMOVE service  via process flow. It will help in creation of projects.

**Comment by mitulpanch** [comment]
No possible solution, Closing now
