### ISSUE TITLE
Company Page - When adding service to all company it should redirect to job task page 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1575]
**Describe the bug**
- when we adding service to all company it should redirect to job task page so we understand that all service are now added if there is more company it takes some time so we know that process is now completed of adding service

![image](https://user-images.githubusercontent.com/46588125/188391045-dd38dcb1-7901-42e0-8b23-989f09181c08.png)

**Comment by mitulpanch** [comment]
kisne bola ? kyu bola sab dalo
so pata chale

**Comment by Avinash-ecb** [comment]
@mitulpanch sir me ne hi notice kiya. jab service add karte hai and 3000 jaisi company ho to kitna time lagega pata nhi chalta and refresh kare to kuchh service add hui hoti hai and kuch me nahi hui hoti

**Comment by mitulpanch** [comment]
ok, testing complete hone pe sir ka view le lenge ispe
jab live hota tub

**Comment by mitulpanch** [comment]
I dont think we need to redirect, because user ka flow break ho jayega

still @vinpahilwani / @sureshsirvi  please provide you views

**Comment by vinpahilwani** [comment]
Not Required
