### ISSUE TITLE
Contact page - custom field is not saving for date type

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1577]
Date is not getting saved

http://url8861.mail.berrycast.com/ls/click?upn=Zo0BXBpUj-2BIJjFT-2BLjFJJWLP8EZJDosXmhifLW-2BRv2pV7aaVe0SJlrbLcEbK-2BPA0Vf5bB-2FWvlic-2F3f2IYL48iQnRm9HaVwlPIbbQjJ-2BlC3ta0a-2BqMks7TLv1kXYfNxsemNO3EcGDFdo7LN5Q-2B3uzbprV3HbLBifIY6XQoMSoV-2B3oJh-2F8f-2BhwuVP8tbKoFvXMlANzZfQ16yHa5YGB-2BlkMy8JZNe-2FRSElXecQWTaNI0PW03nVWhtCJhzF4qlGZh4vZirE6YdwFboHnYs2toFeuEQ-3D-3DIGHf_1ZQZ4RHrsVG7KXvL3lcQ2Yc-2BPjIoLB9fTNQEuTqfhx1pOuAVqPizUJGOxzFkQv5HmFhjaeWLQUN8VgGuXF-2Fosjx2ZNDuF8D1tStGcMhvBZYsM7zn-2BJEPd2di8ZUOafFIUUnWsKFqbLQl7Ujj1i0BiBMom9NGIo1r7SlAtvGni0TTCimBVwGf8x4oQ9XeQ2B4I4uqxWhVq1-2BsrGxIYq2WZbwa7peUmrV9qioIRI3vgCAhH4qF8Ux0j5hJFvNfAuY8OACAJGtUh36A8nhcyIlzM56je7ya19wR4SM8GZ-2B69WeKxCZS-2BsvGIOm-2FF3TkXdhIaG0OdH1hC4ViqLP-2Frjb7j9o4U-2BEgyPXQyGh-2F2bmMbdd1X8H18nhPOwTi4lDYtB8F

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/88faa5dc-b185-56c2-be50-b197fde8e9d7
