### ISSUE TITLE
Company Page - Contract View - Remove Create Company button

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1578]
![image](https://user-images.githubusercontent.com/5259926/188812569-f7371ded-be39-4ad4-9db0-29c820dee3b4.png)
+Create is not required in this View

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/190599081-27c5c881-feec-4f3a-993b-1241e39b8e5d.png)
