### ISSUE TITLE
Document Page - Date is not followed by date format setting 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1579]
**Describe the bug**
- In document page date is not follow date format setting from setting page

https://www.berrycast.com/conversations/fbd7f1b5-fad3-5861-b7d1-31256fa2890f

![image](https://user-images.githubusercontent.com/46588125/188819684-9aa15e35-9f4e-4254-83bb-d970960dc2a6.png)
![image](https://user-images.githubusercontent.com/46588125/188819761-ab8fd172-b2aa-434c-ad80-8ac61b071318.png)

**Comment by dharmendraecb** [comment]
Setting Date Format Sample (Wed, Sep 7, 2022) but Document List In Date format Sample (Wed, Sep 7, 2022 1:22 PM) Time include

**Comment by mitulpanch** [comment]
Not applicable now, as this column is removed
