### ISSUE TITLE
Document Page - Folder name should be match in select folder and display label

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1584]
**Describe the bug**

- Both name should be match

![image](https://user-images.githubusercontent.com/46588125/189032748-6f8a5a39-ddeb-427e-a830-1aa5874926b9.png)

![image](https://user-images.githubusercontent.com/46588125/189032628-49dd8c0b-086b-4065-9c2b-26bb6d702cd3.png)

**Comment by mitulpanch** [comment]
not  required
