### ISSUE TITLE
Document Page - Reset company option is not working

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1585]
**Describe the bug**

- we can not go to other company document, we have to refresh all page
https://www.berrycast.com/conversations/84c85e41-ce4e-56d0-8818-01b90e57d585

**Comment by dharmendraecb** [comment]
AutoComplete Cancel Button (Removed).
This Modal Only Change Folder Option . Can't Fill Data And By Default Selected.
