### ISSUE TITLE
Company Page - Contract Mode - Design Change

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1588]
Problem -
1. No such problem, just better design available
![image](https://user-images.githubusercontent.com/5259926/189090917-be9426bd-2276-4d44-a199-275c3a2a6174.png)

Suggested Solution by @vinpahilwani 
1. Make design as available in Custom Field View

Technical Details
1. Custom Field is self made design, as Column and Row bit are dynamic
2. This design is very costly in terms of loading
3. Future changes to this is difficult
4. Current Designs are from Theme, and follow all guideline required for Tablet friendly view, messing this will create future alteration problems

**Comment by mitulpanch** [comment]
My take-
1. We should follow theme, where ever possible, to make space for future changes,
2. Custom Design only used when nothing is possible in terms of structure from Theme, 
3. I have 1080p Full HD monitor, which common now a days , and it gives perfect view without scroll, we should not do any alternation at cost of responsive view from theme

**Comment by mitulpanch** [comment]
Time required-
1. 2 Full days with Testing
2. Multiple select and other Multiple action may required additional time, this is not common design

**Comment by vinpahilwani** [comment]
We can postpone but we need to do it because i want to offer consistency in the use
