### ISSUE TITLE
Project Page - Query Builder Filter - Design Change

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1589]
Problem-
No need to show days used in auto complete

![image](https://user-images.githubusercontent.com/5259926/189092842-80cb3de8-b29f-4b7b-a26f-920d6a803a8e.png)

Initiated by @vinpahilwani 
verified by @mitulpanch

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/190853892-9b6dedbf-e240-4bae-9d6d-7843038cf74e.png)
