### ISSUE TITLE
Project Page - Data Upload Button required on Detail Section

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1591]
Problem - 
Data Upload is available on List page
User want to Upload Json File from Project Detail Section

Solution
Implement Upload File button on Detail section

Technical Detail
1. Data Upload will open in side popover as it is opened on list page
2. Just Trigger button required on Detail Page

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
No comments added from @vinpahilwani / @sureshsirvi

**Comment by mitulpanch** [comment]
Moving forward to Development

**Comment by dharmendraecb** [comment]
Please Approve!
@vinpahilwani @sureshsirvi 

![image](https://user-images.githubusercontent.com/46588108/189892186-49d203d9-1fa8-4f0d-85d2-d0cb330e9b3f.png)

**Comment by vinpahilwani** [comment]
Yes required

**Comment by mitulpanch** [comment]
if you have any suggestion for design please provide @vinpahilwani @sureshsirvi

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/b673b185-cf63-51f6-b0bb-0799ea0a1721
