### ISSUE TITLE
Document Page - when we open page volt folder should not open by default

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1598]
**Describe the bug**
- when we open document page volt folder should not open by default
- everyone has not permission to view this

![image](https://user-images.githubusercontent.com/46588125/189475480-eabe37d1-23dd-4b03-9b3a-955e36433145.png)

**Comment by mitulpanch** [comment]
this is going to change after testing 
Default is Common Folder
