### ISSUE TITLE
Project Deviation Page - Remove create button , show only project deviation , increase budget and time column width By Vinod sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1604]
**Describe the bug**

**Suggestion**
- Remove create button
- show only that project which has project deviation
- increase budget and time column width so we can see clearly

https://www.berrycast.com/conversations/991d7fa5-113e-5b32-b8c6-4aaffbc0cf0c

**Comment by mitulpanch** [comment]
Some things are not possible
