### ISSUE TITLE
When attaching ledger to email template it's shows blank pdf in email.

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/EasyCloudBooks#1605]
**Describe the bug**
Create a Template LedgerPDF File to send mail to the company but PDF file Data Blank

**To Reproduce**
1. Go to '(https://rajassociates.easycloudbooks.com/user/template/email/list#)'
2. Click on Create new LedgerPDF file
3. then select a company to send mail of ledger pdf file.
4. but the mail sent has been blank PDF.

**Expected behavior**
last year's all data has been pdf ledger file

(https://www.berrycast.com/conversations/cbc04949-1b92-532d-8982-fe881303e6b6)

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/079fe88e-b02c-57bc-83a3-7c33df3d78d4
