### ISSUE TITLE
Document Page - after copy or cut paste button color is not highlighted

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1606]
**Describe the bug**
- When we copy/cut a folder or file we can not see any change in that file or folder (UI change) 
- If there is ui change then we can easily identify the difference 
- 
https://www.berrycast.com/conversations/0e02ebf9-4b85-573d-9ff1-4ac28d31aab0

**Comment by mitulpanch** [comment]
Please Color Change to highlight if not done

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/191670663-aa9cd88e-97ca-4f9a-8d74-00f2885a3f42.png)
