### ISSUE TITLE
Company Page - Ledger Mode- Add Send Email / SMS / Notification Action

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1609]
Problem
1. User wants to send Email to Client, Multiple action has no email sending option

Solution
1. Add Email /SMS / Notification to Multiple Action

Initiated by @vinpahilwani 
Verified by @mitulpanch 

https://www.berrycast.com/conversations/3717d2a9-6a4a-5136-ac4a-67dd119fd112

**Comment by mitulpanch** [comment]
We do not have direct send Ledger button,
Flow is
1. Select "Send Email"
2. Select Ledger Template
3. Send Email

**Comment by vinpahilwani** [comment]
can you show me video how to do that ??
