### ISSUE TITLE
Contact Page - Separate Change Tag to Create Tag / Remove Tag

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1610]
Problem-
1. Currently Change Tag functionality doing all in one section
2. this is not proper for some users
Solution
1.Add Tag / Remove Tag required in different Mode
2. Not sure about Change Tag is required or Not

Initiated by @vinpahilwani 
Verified by  @mitulpanch

**Comment by mitulpanch** [comment]
Make 3 Different Section
1. Add Tag - add only
2. Remove Tag - remove only
3. Change Tag - remove all and add new tags

**Comment by vinpahilwani** [comment]
Done

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/0dced9d4-8fee-55ef-a010-97ac5c9f6cf8
