### ISSUE TITLE
Company Page - Ledger Mode- Show Unbilled project when clicked on Count

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1612]
Problem-
User want to see Project which are unbilled, when clicked on Unbilled project count

Technical error
Project may be on any stage, like Completed, Review , Finished 
so matching of Count can not be done, so was not created initially

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
Transaction Page has Unbilled Project list, but that solely can not be opened on any page, as 
it is sub module of Transaction Page, and has interlinked functionality on Transaction Page

**Comment by vinpahilwani** [comment]
Hum yeh dikhate hai transaction page pe udhar koi problem nahi hai? wohi humko idhar dikhana hai side se

**Comment by mitulpanch** [comment]
> Hum yeh dikhate hai transaction page pe udhar koi problem nahi hai? wohi humko idhar dikhana hai side se

because its part of transaction page, if you want to show some where else its needed as independent module , to open in side popover

**Comment by mitulpanch** [comment]
This requires new Module, If you want to proceed then this will take about 2-3 days for design / Api requirements

**Comment by vinpahilwani** [comment]
Ok We can postpon it for some time, No Hurry

**Comment by mitulpanch** [comment]
Closed for now
