### ISSUE TITLE
Company Page- Archive Button Required

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1615]
User wants to Archive Company to make Inactive

Solution
1. Create "Archive" button to make company Inactive in View Mode
2. Role is Edit Company
3. Remove all Attached Service
4. Stop Contract Transaction auto Creation
5. Stop Service Scheduler for Project
6. Manual Transaction can be created for Archived Company
7. Manual Project Creation is not clear - @vinpahilwani / @sureshsirvi please elaborate

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
This is just Company Page Design
Effect of this will take some time to develop

**Comment by vinpahilwani** [comment]
done

**Comment by mitulpanch** [comment]
Please dont move issues sir

**Comment by mitulpanch** [comment]
Effect Coding -
1. Stopping Service Scheduled Project Creation Trigger, No new Project gets triggers for Auto Creation from Scheduler, although Previously pending Project creation will clear que and create All Pending Project. 
2. Stopping Auto Bill Creation from Scheduler - No new Bill get triggered for Auto Creation from Scheduler, although Previously pending Transaction creation will clear que and create all pending Transaction.
3. Stopping Auto Bill creation from Per-project Mode - No new Transaction for any Project event, although Previously triggered event will clear transaction create que 
4. Company Page - Contract View - Dont show Archived Companies

**Comment by mitulpanch** [comment]
Design -
Header is required
"This Company is in Archive Mode"

**Comment by mitulpanch** [comment]
No Comment from @sureshsirvi
