### ISSUE TITLE
Company Custom Field - Data is not trim when saved in company custom field

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1619]
**Describe the bug**
- when we are saving custom field if there is extra space then it also saved in company custom field 
- Extra space should be trim when save data 

![image](https://user-images.githubusercontent.com/46588125/190059060-a04e5d49-8fa3-49c6-af0a-ac4191617511.png)
https://www.berrycast.com/conversations/55787b9c-0ae0-5963-a269-06d88303a474

**Comment by mitulpanch** [comment]
data do not trim on custom field, this are space , case sensitive data
