### ISSUE TITLE
Company Custom Field - When remove text from 'company-service' type custom field then also it shows text

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1622]
**Describe the bug**
1. Add text custom field of company  service type 
2. remove all service from that company
3. remove text from that custom field then it shows text it is not changing

https://www.berrycast.com/conversations/59485540-d18e-5578-9f99-273d1bfc5784

**Comment by mitulpanch** [comment]
I think this is like,
Not able to remove Custom field value, it is not related to any other issue i guess

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/3e3d645e-653d-5ff0-be77-f63722038f53
