### ISSUE TITLE
Email Template Page - Decrease width of filename column so we can see remove button

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1623]
**Describe the bug**
- First when we added any attachment by mistake we can not see any remove button to remove that attachment 

**Suggestion**
- so decrease width of filename column so we can see remove button 

![image](https://user-images.githubusercontent.com/46588125/190307643-3de6f1b3-b8c7-4a10-b8ec-893ff9ecc0eb.png)

https://www.berrycast.com/conversations/564b553a-22b1-5b38-afae-b602999dabc6

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/195069589-34db50a1-280e-4761-8f91-3e0a86485a34.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/195790567-59c1dbad-10d1-4cba-ba9d-ed301cae8fc0.png)
