### ISSUE TITLE
Company custom field - Showing two same group in custom field with small and capital letter

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1624]
**Describe the bug**
- In custom field view there is showing two group first 'group2' and second 'Group2'.
- when we adding custom field we can see a group is 'group2' but in table it is showing like 'Group2'

![image](https://user-images.githubusercontent.com/46588125/190315716-d37a3f84-229e-4aa8-bd3a-e9809f077a2d.png)

https://www.berrycast.com/conversations/63fdb41b-78c4-51ad-a6ee-f65ca8492847

![image](https://user-images.githubusercontent.com/46588125/190315825-d6628e9f-eb8b-4113-a172-57d800533c5d.png)
![image](https://user-images.githubusercontent.com/46588125/190315864-0e60aa4c-65bc-4141-aae6-d1ee481a942b.png)

**Comment by mitulpanch** [comment]
cant do anything for Past values
Please Test with some new values providing same value lowercase and uppercase
I guess this is already solved for new values
