### ISSUE TITLE
Company Page - Contract View - Change Contract "Approved" to "Checked"

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1625]
Problem-
User may take different meaning for "Approved"

Solution suggested by @vinpahilwani 
Change Name to "Checked"

initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
![image](https://user-images.githubusercontent.com/5259926/190571317-edfcf549-adea-4d49-8fc1-17aa3418ba32.png)

Please provide word for before and After approval
@vinpahilwani

**Comment by vinpahilwani** [comment]
Yes and Also Required filter for checked and unchecked

**Comment by mitulpanch** [comment]
> Yes and Also Required filter for checked and unchecked

yes different issue for that
#1629

**Comment by mitulpanch** [comment]
@vinpahilwani Please Provide English for "Checked" / "Check It!"

ie "Approved" / "Approve It"

**Comment by vinpahilwani** [comment]
Button : Approve
Par filter me woh Approved hoga

**Comment by mitulpanch** [comment]
"Checked" / "Check It!" ye chalega?

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/194806348-bf17e138-23dc-4ffb-a01a-88e59e8eedde.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/194806382-95f880d1-037c-4eb1-aa84-85ea9599ed15.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/200524628-6f992289-2eb2-43e1-a256-c8b7c72d8c94.png)
![image](https://user-images.githubusercontent.com/46588125/200524699-28e70e57-e8e7-4592-9172-899a1b71f7c1.png)
