### ISSUE TITLE
Company Page - Contract View - Per Project Billing - Design Change

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1626]
Problem -
Billing Mode name change Required

Solution
Change to "Billing Event"

![image](https://user-images.githubusercontent.com/5259926/190570299-602a0d48-40bf-4ebb-b4ac-c9e0cab74581.png)

initiated by @vinpahilwani 
verified by @mitulpanch

**Comment by mitulpanch** [comment]
"No Service Found" to "No Service Attached"

**Comment by vinpahilwani** [comment]
Yes

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/191455046-a0876fdf-590f-4c93-afa7-92895be15554.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/191944100-fbba5ff9-36b3-4ea3-b800-14a9ceee1417.png)
