### ISSUE TITLE
Company Page - Contract View - Per Project / Auto Billing - Tax Setting auto complete design Change

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1627]
Problem -
1. User want to see Total Tax Percentage in Tax Autocomplete in Per project and Auto Billing Tax Selection Autocomplete

Solution 
1. Show Tax percentage along with Name

Design

1. if Tax is 9% cgst and 9% sgst then => GST (18%)
 show Total Tax Percentage
2. if tax is 10% with 150 Rs amount => GST (10% + 150)

initiated by @vinpahilwani 
verified by @mitulpanch

**Comment by mitulpanch** [comment]
![image](https://user-images.githubusercontent.com/5259926/190571169-97973b1a-a702-4492-9ca1-a4793eed0d32.png)

**Comment by mitulpanch** [comment]
API changes are also required to do this

**Comment by vinpahilwani** [comment]
yes

**Comment by mitulpanch** [comment]
This value is not for search, Search will be for Name only

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/191453884-881a9a63-3fb8-4a88-b3d2-8c2863724186.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/192978422-a63c42f3-41ea-49cd-9e87-bec6358ab40c.png)
![image](https://user-images.githubusercontent.com/46588125/192978581-c73af51f-f7d0-4388-a7d5-e7d1d8a2a714.png)
