### ISSUE TITLE
Company Page - Contract View - Auto Billing -Show Pre Service Count

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1628]
Design Change Required

![image](https://user-images.githubusercontent.com/5259926/190571675-e8dfbb8d-c98d-4d55-8aeb-e0e8ae4259c6.png)

Show service count with "Total Annual Fees"

Initiated by @vinpahilwani 
verified by @mitulpanch

**Comment by mitulpanch** [comment]
"Pre Contract Service" count that selected inside "Annual Fees" as first stage

**Comment by vinpahilwani** [comment]
yes

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/194804394-50ec2487-c193-4aac-af35-151696fc42bd.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/201609686-3267a5fc-a154-4898-aa4d-cf6b32265bcf.png)
![image](https://user-images.githubusercontent.com/46588125/201609865-16e47880-cc0c-4d39-b1e6-4e766ca25339.png)
