### ISSUE TITLE
Company Page - Contract View - Checked Contract Filter Required

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1629]
User wants to see which Company Contract view need Checking

Solution 
Add Contract checked "Is Checked" Filter for Contract View only

This should not come to Other Views

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
@vinpahilwani 
Please Provide Title for "Is Checked" Filter Title

**Comment by vinpahilwani** [comment]
Contract Check :  [] Yes  []No

**Comment by mitulpanch** [comment]
contractchecked new parameter into API for this

If Yes => Both Schedule Billing and Per-Project Billing contract is Approved
else NO => Any of Schedule OR Per-Project Contract is not Approved

**Comment by dharmendraecb** [comment]
Check Box Not Possible 

![image](https://user-images.githubusercontent.com/46588108/191454010-0e299b90-cd31-46ea-924a-73bf3e035724.png)

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/c9e631bb-8652-5d27-bd15-ad60af94f82e
