### ISSUE TITLE
Through Camera option should be there in uploading contact image request by suresh sirvi

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/EasyCloudBooks#163]
![2021-01-26_11-24-06](https://user-images.githubusercontent.com/77724114/105806665-622bc400-5fca-11eb-88e1-86539e49434c.png)

If user want to upload his/her image through web camera , so this option should be there.

**Comment by mitulpanch** [comment]
@ajayrajecb Test on Mobile App, Escalate if Required
