### ISSUE TITLE
Company Page - Contract View- Create Customized new Filter Area

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1630]
Problem-
User dont want additional filter in this Area,

Solution
Create New Filter area for this View

Technical Detail -
Currently We have not created any special filter area for Different Views,
If this is required than new section needed 

Design
@vinpahilwani Please Provide how many filters required in Contact View

Time Required - 0.5 - 1 Day

**Comment by vinpahilwani** [comment]
We can wait its not urgent "Not Required Now"

**Comment by mitulpanch** [comment]
coding for different view Show / hide is time consuming so leaving for now
