### ISSUE TITLE
Company Page - All View - Filter - Shift Rows count to Last

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1631]
@vinpahilwani suggested to Shift Row count to Last of Filter

initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by vinpahilwani** [comment]
Yes

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/191911235-ced2f295-25a1-4a0c-a423-c9755a2bb412.png)
