### ISSUE TITLE
Company Page - Contract View - Per Project View - Change Check Box to ON / Off button

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1632]
Problem-
Check box is used to switch OFF auto Billing for Per Project Billing, 
instead of this ON / OFF switch button required for better understanding

Discussed over Phone with @vinpahilwani 
![image](https://user-images.githubusercontent.com/5259926/190583268-d04a2eed-83fc-41d4-ba83-e65e7295a765.png)

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
ON / OFF switch is difficult designing, I suggest better to stick with checkbox, on Check box check / uncheck
"Auto Billing for 8 Service"  section auto changes for user understanding

**Comment by vinpahilwani** [comment]
We can postpone not urgent

**Comment by vinpahilwani** [comment]
We can postpone not urgent

**Comment by vinpahilwani** [comment]
We can postpone not urgent

**Comment by mitulpanch** [comment]
I think we have enough Service Name space, as @vinpahilwani suggested to write 
"Service Name (Auto Billing)" for checked service
and "Service Name" for unchecked Services

before i though that there is not enough space on some side views , but looks like it would fit correctly

**Comment by mitulpanch** [comment]
ON / Off plugin not required as discussed over phone, instead text "Auto Billing" needed on Service Name

**Comment by dharmendraecb** [comment]
![Image](https://user-images.githubusercontent.com/46588108/191201539-2899aabb-2f12-4c4b-b80f-00d512b1d5da.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/193397123-c4e49d92-516e-47af-809d-ef7093f16be9.png)
- in some service we can not see (Auto Billing)

**Comment by Avinash-ecb** [comment]
After discuss with @dharmendraecb It is ok
