### ISSUE TITLE
Project Page - Custom Field View - Role Required

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1633]
Problem -
1. Previously "Report" was Role name that provides Role requirement to this functionality
2. Previous design Menu name was Report for All Custom Field View for Contact , Company, Project so Role name was Report
3. After "Report" role removal, Project Custom Field List Role is missing
4. so New User can not assign Role for This page
5. Company and Contact Custom Fields are aligned with Company / Contact Edit Role, so no problem for them, They also previously had Report Role, but now using Edit Role

Solution-
Bring back Report Role for Project only, as Company / Contact works correctly, they do not require any further change

Technical Details-
1. New Role / API changed required to accommodate this

initiated by @mitulpanch 
verified by @vinpahilwani

**Comment by vinpahilwani** [comment]
Yes Role is Required

**Comment by vinpahilwani** [comment]
Yes Role is Required

**Comment by vinpahilwani** [comment]
Yes Role is Required

**Comment by mitulpanch** [comment]
Please give suggestion for Role name and Sub type?

I suggest this should be independent Role -
ie. Project Custom Field -> Read , Edit

Please provide your View, Placement should be just below Project Role

**Comment by vinpahilwani** [comment]
Matlab?

**Comment by mitulpanch** [comment]
Project Custom Field -> Read , Edit 
ye role bana du?

**Comment by vinpahilwani** [comment]
Yes aisa hi

**Comment by mitulpanch** [comment]
Showing All Unfinished Projects,
So any body with Project Custom Field Read / Edit Role can process custom field page

No Project Member . Manager etc role required

**Comment by mitulpanch** [comment]
Project Page roles do not apply here,
This page have 2 role,
Project Custom Field => read
Project custom Field => Edit

**Comment by mitulpanch** [comment]
Project Page roles do not apply here,
This page have 2 role,
Project Custom Field => read
Project custom Field => Edit

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/194805467-1891734b-7c0c-45cd-8dcd-587874202c26.png)

**Comment by Avinash-ecb** [comment]
**Describe the bug**
- User has read and edit project custom field role but user can not edit project custom field 
- create button also not display

![image](https://user-images.githubusercontent.com/46588125/195503915-7ab53fef-d4ac-4595-8107-cd0ad4316138.png)

![image](https://user-images.githubusercontent.com/46588125/195503860-46e9bc3a-b0c1-4563-859b-f05cb93300c1.png)


https://www.berrycast.com/conversations/16ce6c63-5592-5e56-a905-391d81d20625

**Comment by Avinash-ecb** [comment]
User has not customfield role so it is not working
![image](https://user-images.githubusercontent.com/46588125/195522382-df8bb6a5-ee49-4ba6-9ff6-d12610308c5d.png)
