### ISSUE TITLE
Company Page - Custom Field View - Custom Field Name - Display (space) instead of -(dash)

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1636]
Problem -
User wants to see space instead of -(dash) for Custom Field Name.

Technical Error-
1. Space is not allowed for Custom Field Name, due to multiple usage of name
2. Custom fields are identified by name at no of place ie. Email template, Keys, Print section, All Templates 
3. So allowing Space will create lot of problem, considering this Space was never allowed for custom field name instead -(dash) is used

Suggested Solution-
1. @vinpahilwani suggested to display space instead of -(dash) at display areas, to ease users.
2. We can do this, but i think displaying something which is not actual, may lead to different kind of problems
3. User will think that custom field has space and may create different keys with spaces instead of -(dash)

initiated by @vinpahilwani 
verified by @mitulpanch

**Comment by mitulpanch** [comment]
@vinpahilwani suggested to display Space instead of -(dash) at Custom Field List view, and Filling area

Other area will continue -(dash) to stop key problems

**Comment by mitulpanch** [comment]
1. Custom Field List
![image](https://user-images.githubusercontent.com/5259926/190995692-54bd0a5f-ac43-4f02-a374-7f72c97cf376.png)

2. Custom Field side popover
![image](https://user-images.githubusercontent.com/5259926/190995789-3d0b3a9d-29a0-418e-a8c8-4cea8648409e.png)

Only these 2 area will have space instead of -(dash)

**Comment by vinpahilwani** [comment]
description client ko instruction me dikhayenge so that client ko aasani ho custom field ka meaning kya hai

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/201256656-860c8c86-5ebc-4138-8cd0-b2ba50489055.png)
![image](https://user-images.githubusercontent.com/46588125/201256728-80c61dce-e363-4cdd-a8a7-5f1506bab815.png)
