### ISSUE TITLE
File Module - New Requirement

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1637]
New Module-
Requirements
1. EasyCloudBooks should know which files are missing, and which are complete
2. Contact Person (clients of PGRT Company) should be able to easily upload Files
3. Staff should be able approve / reject files

Solution Discussed over Phone with @vinpahilwani 
1. File Module requirement same as Custom Field, Custom Field can not store Files so new module is required
2. Total 6 Types of Files
     a. Contact Files
     b. Company Files
     c. Company-Service wise File
     d. Project Wise File
     e. Project-Service wise File
     f. Staff Files
same as Custom Fields
3. User will provide Files list, as currently provided for Custom Field, 2 option, either on Service Page, OR Different page like Custom Field Setting to provide File Settings
4. These Files wont be visible on Company Documents, These files will be available inside Company / Project / Contact section, same as Custom field but with Different Design
5. How to Search file? same as searching Project / Custom Field
6. Sending File? A module inside Client Area / App will solve this problem,  No need to send file just send link to open App / Client area so Contact can access / Download File
7. Staff will Approve file, Approved files can not be changed by Client
8. **Task Module** required to get Staff Attention if files are added to Files Module
9. One File can take Multiple files, Client can upload as many he requires, but after approval Client can not change file
10. Client can download files through app / Client Area
11. May be configuration required if Client can see all files or not (like Custom field)
12. These files are visible only inside sub modules ie Company / Contact / Project / Staff, there is no common place where all files can be seen
13. Clients need Additional Module in App / Client Area to easily upload Files, this should be Project wise, if Client has 10 Projects then show all project which needs files, project should be grouped as (Service / Year), so client can easily upload, Client can upload multiple files to each File Object. 

Initiated by @vinpahilwani 
verified by @mitulpanch

**Comment by mitulpanch** [comment]
14. Staff needs to Approve file Object as whole, by seeing all files inside File Object Folder, so easycloudbooks can understand what is complete
15. we can say that File Object taken is kind of Folder managed by easycloudbooks, there will be multiple files inside one file object
16. Task module will create task if something changed inside Folder, so somebody can attend that task
17. There will be multiple files inside on folder(file object), so need design to show all files inside one folder, and as combine staff can approve whole folder

**Comment by mitulpanch** [comment]
19. Not sure how to move file between different folders, this needs discussion, as technical thing for moving file requires too much logic, if required, only then we should proceed with this

**Comment by mitulpanch** [comment]
@vinpahilwani @sureshsirvi 
both of you please provide your views, requirements, problems

**Comment by mitulpanch** [comment]
One more thing that i see as a problem,

@vinpahilwani wanted that Client will provide some file witch are shared between projects, this kind of setup is not available to custom field

Detail view-
Lets find out type of Types with Example
1. Pan card - Company level common, this is required only once in lifetime, may be asked for update / KYC but in lifetime this is required only once - called with type **Company** - Required on All Companies
2. GST Number Certificate - Company Level Common - but with twist that this applies to only GST Service Clients, If Gst type service is applied then only this kind of files required, basically not required for all clients (ie. Not Required for ITR) - called with Type **Company-Service**(if service is applied to Company then required, but required only once in lifetime)
3. Project Level Files - basically these files are required on each Project Applied to All Service Projects , called **Project** Level Files
4. Project Service Files - these files are required on Project for Particular Service Project, not on All Projects, - called **Project-Service** Level Files 

These are 4 basic Types of Custom Fields currently easycloudbooks offers.
I can see 5th type as "Project-Period-wise"
This File is shared between Project with same Period, so if Project(Service GSTR-3B) with File Bank Statement with Period 2021-22-Q3 have File, 
then same file will be auto filled for Other Project (Service GSTR) with Bank Statement with Period 2021-22-Q3, 
So Files are shared for Project having same Year-Period and Company beyond Service

**Comment by mitulpanch** [comment]
As discussed with @vinpahilwani over phone
Only 4 Types Required
1. Company - Once in lifetime File
2. Company-Service - Once in lifetime File but required only when Service is attached to Company
3. Company-Legal-Structure - (new Mode) - Once in lifetime File but required only when Company's Legal structure is having some Value
4. Project-Service - (Meaning- Project-Service-Yearwise) - (new mode) - Project wise but shared on Year-Period basis, 
ex. This File is shared between Project with same Period, so if Project(Service GSTR-3B) with File Bank Statement with Period 2021-22-Q3 have File. Then same file will be auto filled for Other Project (Service GSTR) with Bank Statement with Period 2021-22-Q3. Full Year-Period is required to Auto Fill File. Only Year check in not possible. If Full Year-Period combination is matching then only file will autofill. (This is not Project-Service as described on Custom Field , this has different logic.) This File need to attached on Service, so Files for All Project is not this one.


File Mode removed
1. Project - File that available for All Project regardless of Service - not Required by @vinpahilwani 
2. Project-Service - File that available for All Projects depend upon Service -not Required by @vinpahilwani (Above specified in Required Type, is not this one, above one meaning for Project-Service is different)

**Comment by mitulpanch** [comment]
Flow 1-
1. Client Opens App , ECB AI auto suggest Task , There may be a task of File Missing on Project,
2. Client can click on task , and that will lead to File Upload Module
3. Client Uploads Multiple Files to different File Section
4. Design of File module is like Company File, Project wise File with Grouping Possible, but i suggest paging should be there instead of Grouping

**Comment by vinpahilwani** [comment]
- company files are one time file
- project files are period wise files i.e. it depends upon period

**Comment by mitulpanch** [comment]
New Requirements -
1. Need to Track Approve / reject on Client Uploaded files
2. Approval means File is OK, and no further attention needed
3. Rejected means Delete File

ex. Companny - Mitul company is client of PGRT Accountant company
Mitul Company has 3 Custom File requirements
1. PAN
2. GST Certificate
3. Adhar card

Client uploads files inside PAN - suppose 3 PAN card copy inside PAN card custom file section
so 3 file should come with need approval tag because files uploaded by client

Staff will see, need attention icon on Mitul Company on Company Custom Field page
Staff will click on Mitul Company that will open Mitul Company's Folders on side popover,
Now staff will see, PAN card folder with need attention icon,
Staff will click on PAN card , will open new side popover will all files inside PAN card.
Now staff will see 3 new files inside all file list with new attention icon
Staff will click on any file for preview, 
preview will have 2 buttons , Approve / Reject if need attention is set for File
Approve will remove attention icon, Reject will delete file

in this way staff can complete all files 1 by 1 and finish work

I have not planned for this, but will do this shortly

confirmed over phone with @vinpahilwani

**Comment by mitulpanch** [comment]
Staff Uploaded files do not require Approve / reject

Approving Pan card folder will auto approve all inside files

**Comment by mitulpanch** [comment]
NO notification needed for any thing from staff
Task will be created once we create Task module, whenever client uploads a file

**Comment by sureshsirvi** [comment]
> One more thing that i see as a problem,
> 
> @vinpahilwani wanted that Client will provide some file witch are shared between projects, this kind of setup is not available to custom field
> 
> Detail view- Lets find out type of Types with Example
> 
> 1. Pan card - Company level common, this is required only once in lifetime, may be asked for update / KYC but in lifetime this is required only once - called with type **Company** - Required on All Companies
> 2. GST Number Certificate - Company Level Common - but with twist that this applies to only GST Service Clients, If Gst type service is applied then only this kind of files required, basically not required for all clients (ie. Not Required for ITR) - called with Type **Company-Service**(if service is applied to Company then required, but required only once in lifetime)
> 3. Project Level Files - basically these files are required on each Project Applied to All Service Projects , called **Project** Level Files
> 4. Project Service Files - these files are required on Project for Particular Service Project, not on All Projects, - called **Project-Service** Level Files
> 
> These are 4 basic Types of Custom Fields currently easycloudbooks offers. I can see 5th type as "Project-Period-wise" This File is shared between Project with same Period, so if Project(Service GSTR-3B) with File Bank Statement with Period 2021-22-Q3 have File, then same file will be auto filled for Other Project (Service GSTR) with Bank Statement with Period 2021-22-Q3, So Files are shared for Project having same Year-Period and Company beyond Service

We do not need 5th type as "Project-Period-wise" ... However we need option to see same period document for "Project-Period-wise". in Project.

**Comment by mitulpanch** [comment]
Project-year-service (shared) custom file - 
are complex to process

I need different API to structure them

I think it better show them in different grouping on Custom File View due to different API requirement


I have explained this to @vinpahilwani

**Comment by mitulpanch** [comment]
New Requirements over phone with @vinpahilwani 

---

5th Type

Name - **Company-Specific** 
attachment Logic-
(Company and Service wise as relation) - for creation -
attach Custom File to Company when a Project comes for particular service

File share structure -( Company - year - period wise)
Files are shared between Custom Files when same period file exists for Company

Visible on Projects , Project Custom File Page

---
Create Custom File Design -

Type - Company-Specific
Services - Select services for custom file is applicable
Company Selection - (Optional) - Select Company for which this Custom File is attached

In this way system can see which custom files are applicable to which Company
Custom File with - no company attached will not come to any project, as system cant see custom file attached to any company, service is attached but without company attachment this Custom file wont come to any project

So in order for any Custom file to come to Project, must have Service of Project and Company of Project attached.

---

Bank Statement is ideal example for this
Mitul Panchal(Client) has 3 bank Account, in that cases Staff working on Project Custom File may not know actual bank statements
So this Custom File has 2 relations - Service wise and Company wise

Staff will create Bank-Statement-HDFC, Bank-Statement-ICICI as convenient, from project redirect flow OR from Project Custom File Page flow
Then need to attach Custom file to Client for particular Service, so system will create Blank custom File for company, visible on Project Custom File view

---

**Comment by mitulpanch** [comment]
Flow requirements -

---

Ideal Flow -
 
1. Create Custom File with specific names like - 
         a. Bank-Statement-HDFC 
         b. Bank-Statement-ICICI 
         c. Bank-Statement-PAYTM
2. Then need to Attach Custom Files to Services while creation, on which service this is Applicable like 
         a. GSTR 
         b. GSTR-3B 
         c. GSTR-2
3. Then attach Companies for which Custom File is applicable like - 
         a. Bank-Statement-ICICI is appliable to Mitul Panchal(Company),
         b. Bank-Statement-HDFC is Applicable to Vinod Pahilwani(Company), 
         c. Bank-Statement-ICICI and Bank-Statement-PAYTM is applicable to Suresh sirvi(company)

Reset / Processing is required to see effect

**Comment by mitulpanch** [comment]
Project Manager Flow -

Attachment of Company-wise Custom file should be easy

---

1. On Project Details - Project manager opens custom file view and he/she realizes Bank-Statement-HDFC is not taken for Project , so  he can attach Custom File from Past creation of Custom Files. I am considering some new design for this according to past created Designs nothing special
2. Attach should be easy, like side window open to attach Company-specific Custom File.
3. if No Custom File found, then according to role Project Manager can create new Custom File on new Tab, if possible Side window is preferred
4. After attachment new Custom File will be visible after Reset or Background Processing

**Comment by mitulpanch** [comment]
Bank-Statement Generalized Custom File is required for new Client as PGRT may not know actual Bank of Company, 
but for Company have bank details , and still using BANK-Statement generalized Custom files are strongly discouraged

Common Custom file for Company-specific Custom File will create lot of confusion on long term. specific Custom file should be used with correct specifical names, Common attribute is discouraged

for first Project - Common Bank-Statement should be used, once PGRT knows correct bank - Correct Attachment (ie. BANK-STATEMENT-HDFC) should be done immediately to remove confusions

**Comment by mitulpanch** [comment]
I have explained all of above thing to @vinpahilwani , His reply is awaited
I also welcome @sureshsirvi for his views

**Comment by vinpahilwani** [comment]
yes I agree on this

**Comment by mitulpanch** [comment]
API almost ready, waiting for Design time / Testing related changes

**Comment by sureshsirvi** [comment]
Company Custom File: During Creation of Custom file .. TYPE i.e. Input, Output and Process .. are not required. 
<img width="1440" alt="Screenshot 2023-01-03 at 12 49 13 PM" src="https://user-images.githubusercontent.com/46813198/210314280-fba2da58-f76f-46ee-9ef7-0b503472b1d8.png">

**Comment by mitulpanch** [comment]
https://github.com/Fammeo/EasyCloudBooks/issues/1693#issuecomment-1272245622

I guess this was the reason given to me over phone,

**Comment by sureshsirvi** [comment]
In Upload File section "Cloud", "Physical".. selection is not required .. 
<img width="1440" alt="Screenshot 2023-01-03 at 12 52 09 PM" src="https://user-images.githubusercontent.com/46813198/210314585-b6d52e7d-5aaa-44b9-a333-b446aae06cfd.png">

**Comment by sureshsirvi** [comment]
Reason for requirement:

Some files only required on companies like when its Legal Structure is Partnership Firm / Private Limited / Limited / HUF / Individual .
Example :
in case of Partnership firm, Partnership deed is required but at the same time in Individual or company .. Partnership deed is not required.


 **Company Custom file Page**

in APPLY TO we need following more options

1. Company Legal Structure
2. Company Industry Type

<img width="1440" alt="Screenshot 2023-01-04 at 8 17 12 AM" src="https://user-images.githubusercontent.com/46813198/210475521-fce46c64-4849-4cbe-bf63-47057e085d4e.png">

**Comment by sureshsirvi** [comment]
**Description** is required for Custom file name .
