### ISSUE TITLE
Company Custom field Page - Show company name when change custom field view

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1638]
**Describe the bug**
- We can not find which company's custom field we are changing 
- Show company name in custom field view
![image](https://user-images.githubusercontent.com/46588125/191167513-a09ac138-54cb-45fc-9f21-65b0e2aa70d5.png)

https://www.berrycast.com/conversations/ab258956-295c-50eb-8315-a02cbb6b9df4

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/191204756-4f065667-4116-4d11-be4e-e5d0e36ad884.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/191692040-09b959eb-252a-4e87-bb1b-ec9cd6d7ab82.png)
