### ISSUE TITLE
Company custom field page - Action is not available when we select multiple companies

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1639]
**Describe the bug**
- when we select multiple company action is not showing 

![image](https://user-images.githubusercontent.com/46588125/191167957-20f44174-e28f-436e-bfba-2e25ed25e55a.png)

https://www.berrycast.com/conversations/e9354922-6a9c-5cd6-b0df-2c2f9f5f6907

**Comment by mitulpanch** [comment]
Adding Email / SMS / Notification to action
OR removing Action button

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/191718177-5332249e-619f-481a-b38b-659a12c6d987.png)
![image](https://user-images.githubusercontent.com/46588125/191718247-62fcf805-9521-4d62-8193-8481619593e3.png)
