### ISSUE TITLE
Company custom field - Change create company button to create company custom field 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1640]
**Describe the bug**
- when we click on create button it opens company create view
- There should be company custom field button instead of company create

![image](https://user-images.githubusercontent.com/46588125/191168385-6934fd3a-617c-4eb4-9ac9-a26dcb7112b8.png)

https://www.berrycast.com/conversations/bada4804-fd34-5b43-bbcd-3c6f5b24f5cb

**Comment by mitulpanch** [comment]
Already in development
