### ISSUE TITLE
Company custom field Page - create custom field button not working in custom field detail view 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1642]
**Describe the bug**
- when we try to change custom field there is create button which is not working

![image](https://user-images.githubusercontent.com/46588125/191173307-28fbbf16-3837-4889-a5cb-4893c89b30a4.png)

https://www.berrycast.com/conversations/355afe33-6b6c-5d6f-8dc1-a4bc714a24ce

**Comment by mitulpanch** [comment]
it was migration, so was not created at that time.

Its working fine
