### ISSUE TITLE
Payment - Change Design

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1645]
Design Change
1. Accountant Company Logo , Name Required on top
2. Shift Type Invoice , Receipt as 1st Column, date to Second
2.1 Provide Link on Transaction row to open Print view on new tab
3. Give Total and Pay button in right side window, on top
3.1 Give Accountant Company Details like Name, Address, Phone, Email, GSTNumber below Pay button on Right side above Terms

![image](https://user-images.githubusercontent.com/5259926/191222964-ed975ea9-7479-455b-8d50-6313fa7d5a7d.png)

**Comment by mitulpanch** [comment]
Other Changes Added by @vinpahilwani -

1. Transaction is not Compulsory, 
2. Unique Id is Required , and Click of Print Preview should be changed to UniqueId, UniqueId design should be in Blue, clickable hand hover
3. Column Order change - 1. Date 2. UniqueId 3. Type

![image](https://user-images.githubusercontent.com/5259926/191671103-bd29e956-5dc1-4292-bc3e-afba70f0012c.png)
4. Payment Amount => Total Amount Payable
5. Payment Amount- extend it to Full Page Width
6. Payee Detail should be above Terms

**Comment by mitulpanch** [comment]
7. Note to Company => Message
8. Place holder - "Please Provide Note"

**Comment by mitulpanch** [comment]
9. Shift Pay Directly - Details to Right Side
and Terms , Payee Details to Left Side

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/191893493-f806302b-7164-4fd5-bd43-4d227cbbc927.png)

![image](https://user-images.githubusercontent.com/46588125/191893626-0deecb39-47bd-4a3d-b32d-89faa953e58b.png)
![image](https://user-images.githubusercontent.com/46588125/191893371-790cc41b-46a6-47f5-be89-0fcc795904fe.png)
UniqueId design is not showing in blue

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/195493859-899b2caf-e1f9-428c-95a8-17f325cae2d3.png)
