### ISSUE TITLE
Company Page - Custom Field View - Required How many fields remaining count

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1646]
Problem-
1. Users cant understand what is remaining
2. They can see design for Remaining Field but Count will be handy

Solution-
1. Process data of Custom Fields Empty can solve this problem
2. This needed to process at each alteration OR we can create Process Button which can take background task for All Companies
3. Companies can be sorted by Custom Field Remaining Count

Technical Detail
1. Get count for each Company will take time, so background task is good option
2. 
Initiated by @vinpahilwani 
verified by @mitulpanch

**Comment by mitulpanch** [comment]
@vinpahilwani agreed for Button to Trigger refresh count, but any Company will update only once in week,
this will be background Task

**Comment by vinpahilwani** [comment]
Yes right

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/372ba735-5bb8-5bcc-a06c-772b540c5da6
![Uploading image.png…]()
