### ISSUE TITLE
Project Custom Field - Filters Required

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1647]
Side Panel Filter required
1. Year Period - Default - Current Year - All with Year
2. Service - Default - First one - All with Service
3. Contact 
4. Company
5. Status - All

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
Year default filter Idea is dropped, because of Company wise filter required beyond all year,
All filters are in side panel,

**Comment by vinpahilwani** [comment]
yes agreed

**Comment by dharmendraecb** [comment]
- Remove All Default Filter
- Default Filter Filter Pending

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/202418435-287e5374-0633-4b63-a5c9-f17193f62cdc.png)
![image](https://user-images.githubusercontent.com/46588125/202418488-afa3b3c5-eb4c-4fc8-bbe9-c2a96602a687.png)
