### ISSUE TITLE
Company Page - Archive Filter - Required

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1648]
Problem-
1. User dont want see Archived Companies by default

Solution
1. Provide Filter for Archive / Active on Company Page
2. Default Value for Filter is Active
3.Total 3 Options - Active / Archived / All

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
Filter Section will show Archived if Filter is Checked, no additional Heading Required anywhere, Filter Section detailing is enough

**Comment by mitulpanch** [comment]
When Active is selected Filter Section will not show anything, its default filter,
All / Archived will be visible in Filter Section

**Comment by mitulpanch** [comment]
"archived" new Filter API ready

**Comment by vinpahilwani** [comment]
Yes right

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/94918fa6-1d67-5c0c-a4b2-e4d0c209c9b3
