### ISSUE TITLE
Company Page - Multiple Action - Archive / Activate button

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1649]
User want to Archive / Activate Multiple Action at a time

Solution
1. 1st Button Archive Button
2. 2nd Activate Button

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by vinpahilwani** [comment]
Yes

**Comment by vinpahilwani** [comment]
Yes

**Comment by mitulpanch** [comment]
Api ready

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/4404f8e9-d800-5c9a-b45b-120093108be0
