### ISSUE TITLE
Company Page - change label none->unselect By Vinod sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1652]
**Describe the bug**
- change label none->Unselect
- 
![image](https://user-images.githubusercontent.com/46588125/191700886-dd536137-12cd-49ec-9f9f-9380d2e74a1d.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/194806723-8db0cc41-ff6e-4a2a-8d0e-1562466148ac.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/195496825-97e6bf0f-6bfc-4f9d-91ed-fcbe703d6477.png)
