### ISSUE TITLE
Payment - Transaction Created - Design Change

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1653]
Transaction which gets auto created by Online payment should have additional details

1. Ref No - Add Transaction Number auto generated by Payment should be here
2. Payment Type - razorpay OR paytm
3. Note - Add Note added by Client while Payment (Note to Company)

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/191903314-71ce6b1b-a0c2-403b-ab6d-e45d9985cd71.png)
