### ISSUE TITLE
Tax Setting Page - Remove tax type field from create  tax setting page and remove create date from list

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1655]
**Describe the bug**
- currently we are not using purchase entry so tax field should hide/remove from create page
- We only show output tax while using
- remove/hide create date column from tax setting list
- user can not understand meaning of count column so show some text on hover

https://www.berrycast.com/conversations/24ae299b-060a-55f6-bd07-bf8b99231d22

![image](https://user-images.githubusercontent.com/46588125/191890032-bef37772-b7e9-47ad-8062-3cda9d959346.png)
![image](https://user-images.githubusercontent.com/46588125/191890061-81d95ffa-9bc9-417a-8f7c-aff9e04554de.png)

**Comment by dharmendraecb** [comment]
Tax setting Count (Company and Process Flow inner Use Tax setting)

**Comment by mitulpanch** [comment]
Count is of => Company's Tax Setting for Auto billing OR Per-Project Billing + ProcessFlow tax selected

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/197322296-0411b437-2d6f-42fb-8ab7-666a412c7013.png)
![image](https://user-images.githubusercontent.com/46588125/197322303-98e95f4b-67b0-4c3b-918c-bdce9604a654.png)
