### ISSUE TITLE
Custom Field - New Structure Required

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1658]
Problem -
This is not related to End Users, Majority part is Technical
1. User wants to do many actions with Custom Fields, but current structure limits them in many manner
2. How data is saved?
    Custom Fields are given by Clients, and Type is also decided by Client, So Database for this kind of structure with Custom Filter is very complex. We create Row for each Custom Field Value provided by client, for (Company - Custom Field) combination. So we can say, We only create row if Custom Field value is filled by Staff. for Empty entries we do not create any entries into database. This kind of structure has some advantages like
    a. We do not need to Create Entry when ever staff edits any custom Field setting. We just show custom field possible on Company page, but in background no rows saved for company, if and only if staff fills value to custom field then only we save to database.
    b. Custom Field Immediately available for Staff to fill, because we do not need to add / remove custom field from company
    c. Database footprint is very low, we save many resource
And have some disadvantages
    a. Finding What need to be filled from Query / Database side is very difficult, because we do not have entry for Applicable Custom Field.
    b. Conversion is also little difficult in terms of Type or category change

Solution
1. Create new Structure for saving Custom Field around Searchability of Custom Field Values
2. When ever Custom Field setting changes We need to add Custom Field to Company / Contact / Project, so searching what is empty,  remaining can be done easily.
3. This king of structure needs heavy resource at time of setting change, each Project / Contact / Company kinds of Objects need to process to align with Custom Field setting changes
4. so we can gain searchability with cost of Setting change overhead
5. in basic words, we add due dates to project when project gets created, so each project gets their own due dates, data is copied from master data of due date.

    like wise, for Custom Field,
    We will add Custom Field to each Company, when ever Company gets created OR any master data for custom field changes. 
    This is very overhead but Our Background engine can handle this.

**Comment by mitulpanch** [comment]
Flow-
1. Staff Creates Company, We will trigger Task for Custom Field reset for particular Company. This will execute immediately.
2. Staff Add new Custom Field
    Staff Change Custom Field Services
    Staff Delete Custom Field 
    We will trigger Background Task for All Related Objects (Company / Contact / Project) to reset Custom Field. for  new custom field system will add new blank row for each objects. like wise for other events. 
3. We will process 50 objects at a time. 
4. Staff Import Companies -   We will trigger Background Task for All Related Company  to reset Custom Field. for  new custom field system will add new blank row for each company. like wise for other events. 
5. Staff Import Contacts -   We will trigger Background Task for All Related Contacts to reset Custom Field. for  new custom field system will add new blank row for each contact. like wise for other events. 
6. Staff trigger Multiple Projects creation -   We will trigger Background Task for All Related Projects to reset Custom Field. for  new custom field system will add new blank row for each Project. like wise for other events. 
7. Custom Field master data change will not reflect immediately to All object, background task will process them one by one.
8. We will provide Reset Custom Field button over all object to fasten process, for single object, if Immediate custom field required for any object. We can process 1 company immediately on API server without background task.

**Comment by mitulpanch** [comment]
This will give better searchability / query of Custom Fields.
We may further elaborate other custom field issue using this structure. like changing Category ie. Project to Project-Service, Company-Service to Company.

**Comment by vinpahilwani** [comment]
I think this is technical issue i dont have much to say.

**Comment by mitulpanch** [comment]
New Rules - suggested by @vinpahilwani 

Conversation  Required-
Company To Company-Service
Project to Project-Service

In All Other cases data should not be retained
suggested over phone and Google Sheet
We should not copy data in any other mode - due to multiple object involvement

Company / Company-Service to Project / Project-Service  - dont copy data - company has multiple projects ,so dont copy data
Project / Project-Service to Company / Company-Service - dont copy data - company has multiple projects ,so dont copy data

Company / Company-Service to Contact  - dont copy data - company has multiple contacts ,so dont copy data
Project / Project-Service to Contact - dont copy data - Project's Company has multiple contacts ,so dont copy data

Contact  to Company/ Company-Service   - dont copy data - company has multiple contacts ,so dont copy data
Contact to Project / Project-Service - dont copy data - Project's Company has multiple contacts ,so dont copy data

**Comment by mitulpanch** [comment]
![image](https://user-images.githubusercontent.com/5259926/192749803-9cc8e6d3-d2c0-4d54-b9ea-eb122e71b60d.png)
this was the sheet explained to me over phone

**Comment by mitulpanch** [comment]
> Conversation Required-
Company To Company-Service
Project to Project-Service

Some flow problem in this conversation
When user change Company custom Field to Company-Service
then system starts conversation and custom field dont have services,
so eventually all data get lost 

User tends to take time in attaching Services also, so i suggest we should implement Data prevention on removed Custom field
that can solve all problem for all scenarios

**Comment by mitulpanch** [comment]
Currently Engine Flow-
We check Object (Project / Company / Contact ) for Custom Field from Master Data
Then system adds new Custom fields possible
Then remove previous custom field only when any other custom field has same name, we keep all custom field unique respect to name
other wise hold data, because no other custom field requires same name, so user can attach service to custom field
in a way system prevents data loss by this flow

This apply to all custom field, system hold data until necessary to delete

**Comment by mitulpanch** [comment]
I dont see any other flow to correctly convert above requirements, for data migration

**Comment by mitulpanch** [comment]
Now - Other Point-
What happens to data when we delete Custom Field
There is 2 group one says, 
1. Previously field was applicable, and we have finished projects using that data, so now onward field is not required, but previous data is required, this is applicable for both Company / Project
2. Delete Custom Field means delete all previous data with Field

I suggest we should hold data when ever possible with option to remove all data option if someone required
OR we can ask remove all data when user is removing custom field.

This same flow also applies when user converts Custom Field to other Apply to. We do not delete data to give user's possibility to attach service to custom field. ie Company to Company-Service, Project to Project-Service

Now this may be problem to2nd type of users. but we can solve this problem with slight design change for not attached custom field

**Comment by mitulpanch** [comment]
All above things about Custom Field Remove logic is revoked, as @vinpahilwani suggested simpler logic for Custom Field,

Not attached / Deleted Custom Field are going to be removed after 30 days

released on 06-10-2022 on live, after all changes

**Comment by mitulpanch** [comment]
#1681 
this will change this if agreed
Remove custom Field value logic change

**Comment by mitulpanch** [comment]
No of thing changed with this Module

1. We have new Structure
2. Now we create company Row for possible Custom Field , processed whenever required on events based engine run
3. Custom field Created on Master setting takes times to reflect on Company / Contact / Project / Object Page, (Point 2)
4. Same way ant changes on custom Field Master Setting takes time to reflect on Respective Object Page
5. we have now Empty Custom field Count / sort / filter , possible due to new structure, now live on each Object Page, (cf_empty)
6. Custom field Settings migrated to respective Object Pages
7. Apply To / type changes possible with potential Data Loss
8. Project Custom Field has new Role, Project Custom Field => Read / Edit, **not** linked with Project Role
9. Company / contact Custom field has Edit Custom Field / Read Custom Field Role, available from Past Roles, **no** new Role
10. Export functionality available, Changed from Previous structure, same sheet can be imported back
11. Import Custom Field, detached from Company Import, This is now Import Custom Field Only Mode, Sheet sample will be created by @vinpahilwani , Support team. with structure 
Columns a. Company Name
               b. Pan Number
               c. GSTNumber(text)
               d. Date-of-incorporation(date)
               e. Is-NRI(bool)
               f. Yearly-Tax-Amount(number)
               e. secret-code(password)
               f. website(url)
               g. Type-Client(select)
               h. Custom-field-name (type)
These bracket types (number) are keywords, dont change, or system will ignore them
date format should in Company setting input format (dd/MM/yyyy OR MM/dd/yyyy)

12. Import will be working on Job structure, so will take some time in execution.
13. Contact Company import is given priority, so company import will execute first.
14. This import will not create Company, if Company exists then only custom field will be added
15. This will create Custom field if not exists with same name

**Comment by mitulpanch** [comment]
![image](https://user-images.githubusercontent.com/5259926/212235732-25b5b564-bbc3-4fe0-b32b-9031ab7f5d58.png)
Conversion Data validation
