### ISSUE TITLE
Company Page - Archive Effect - Auto removing Services from 1st stage (Service Scheduler) will remove Custom Field Data

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1660]
Effect Coding -
1. Stopping Service Scheduled Project Creation Trigger, No new Project gets triggers for Auto Creation from Scheduler, although Previously pending Project creation will clear que and create All Pending Project. 
2. Stopping Auto Bill Creation from Scheduler - No new Bill get triggered for Auto Creation from Scheduler, although Previously pending Transaction creation will clear que and create all pending Transaction.
3. Stopping Auto Bill creation from Per-project Mode - No new Transaction for any Project event, although Previously triggered event will clear transaction create que 
4. Company Page - Contract View - Dont show Archived Companies

_Originally posted by @mitulpanch in https://github.com/Fammeo/EasyCloudBooks/issues/1615#issuecomment-1250695162_

**Comment by mitulpanch** [comment]
Problem -
Archive Button - 
When we archive Company
EasyCloudBooks removes all services from Company's Attached services from service scheduler.
This was requirement for Archive Button.

Service Scheduler Services are not just used for Creating Project.
Custom Field attachment also depends on this.

So removing Service scheduler attached service will remove data from Custom Field as well. because Company no longer have service attached.

**Comment by mitulpanch** [comment]
Initiated by @mitulpanch 
verified by @mitulpanch

**Comment by mitulpanch** [comment]
I seek urgent attention from @vinpahilwani , @sureshsirvi

**Comment by mitulpanch** [comment]
Also #1566 - **Company Page - Custom Field for Non recurring Service - No Possible way to add** 
having same king of problem, We need some better way to attach custom Field
I have raised concerned for Per-Project service Custom Field too

We need some firm logic that support all kind of users

**Comment by mitulpanch** [comment]
https://github.com/Fammeo/EasyCloudBooks/issues/1566

**Comment by vinpahilwani** [comment]
toh solution hai - humein per project services bhi link karke dikhani padegi toh uska link company se dikhega and we can know konsi service link hai.

**Comment by vinpahilwani** [comment]
archive karne se services unlink hoti hai and isliye hum service ki custom field nahi dikha pa rahe. toh solution : kya hum service unlink nahi karein aisa ho sakta hai?
- hum project nahi banana chahte and auto billing nahi karna chahte woh rakhte hue agar archive ho toh service unlink na kare toh custom field hum retain kar sakte hai - agar possible ho - I m not forcing

**Comment by mitulpanch** [comment]
We can stop unlinking Service from Recurring service (1st stage) if all agree
@vinpahilwani @sureshsirvi

**Comment by mitulpanch** [comment]
New not removing Custom Field value, will keep data in removal of Service too.
So no new changes required i guess

If we keep data for filled custom Field regardless of Service attached / detached
no new development required in this issue

forwarding to @vinpahilwani , @sureshsirvi  to get their final comment for confirmation, so i can close issue

**Comment by mitulpanch** [comment]
#1681 Custom Field - New Logic for removing Custom Field Value
this development overpass this issue's errors

**Comment by mitulpanch** [comment]
still no solution for #1566 , i consider its not required

**Comment by vinpahilwani** [comment]
@mitulpanch kya naya hai isme mujhe samajh nahi aa raha hum discuss karke is card ko khattam karein?

**Comment by vinpahilwani** [comment]
1. Service agar unlink hoti hai and usme value hai toh woh value rahegi 
2. par agar custom field delete hoti hai toh woh value delete kar deni hai
3. agar service delete hoti hai - toh bhi value bhari hui hai woh rahegi

**Comment by mitulpanch** [comment]
This is live now, 
I have explained to @vinpahilwani  non schedule Service Custom Field problem.
but not interested for that. sol closing this now
