### ISSUE TITLE
Company page - When we change list view to default status filter show all option default

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1661]
**Describe the bug**
- when we go other view from company view using list view and come back to default view status view show all option 

**Suggestion**
- when we come back to default company list view then status should select active by default

https://www.berrycast.com/conversations/509a0d83-5660-5b64-92a3-1e6eca352f56
https://www.berrycast.com/conversations/59da4c83-b45f-5997-aa1a-9751af03dfe2

**Comment by mitulpanch** [comment]
This have some technical difficulties, so not possible to achieve


so considering , to drop Change view Option
