### ISSUE TITLE
Company Page - Showing archive & active option in action but user has not company edit permission

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1662]
**Describe the bug**
- User can see company archive and company active option in action view without any permission

**Suggestion**
- IF user has not company edit permission then hide active and archive option from action view

https://www.berrycast.com/conversations/247b67a4-b507-5117-832e-b24cd3eb1df3

This is working correctly
![image](https://user-images.githubusercontent.com/46588125/192199126-595ff925-ee9b-4486-96a4-6f49e1420503.png)

This should be hide if user has not company edit permission
![image](https://user-images.githubusercontent.com/46588125/192199181-a8577867-3921-4317-a0fa-eda7b4fe9984.png)

**Comment by mitulpanch** [comment]
Aligning Archive button with Edit Role
anyone with Edit role only can Archive / Unarchive

**Comment by Avinash-ecb** [comment]
Without edit role permission
![image](https://user-images.githubusercontent.com/46588125/197155526-48f4cbc4-c27a-4cca-9a58-85a22d3f8371.png)
