### ISSUE TITLE
Company Page - Hide add, remove and change service option in action in archive filter view

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1664]
**Describe the bug**
- when we apply archive filter then if we try to add, remove or change service it is not working so it should be hidden

![image](https://user-images.githubusercontent.com/46588125/192689894-a85e7a8b-4d1a-47c3-8665-1db3bde851c0.png)

**Comment by mitulpanch** [comment]
Filters and Action are used on multiple pages
this changes like dependencies on Filter will make lot more worse for this things to handle

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/195797129-cec68a59-5c18-4706-a619-e604033babfe.png)
