### ISSUE TITLE
Transaction page - When searching company in create invoice error message shown

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1666]
**Describe the bug**
- when we try to create invoice and type some text in search company textbox it showing some error message 
- This is not occurring every time when search, It shows only some time
- I think slow net issue

![image](https://user-images.githubusercontent.com/46588125/192934207-ea992dbf-733d-4aa4-a4ad-8b9c3bc49c37.png)
![image](https://user-images.githubusercontent.com/46588125/192934260-37ed2588-6756-4de9-b0f0-9a2d0502c4be.png)

paylod
![image](https://user-images.githubusercontent.com/46588125/192934311-6b117c8f-dbc9-41f0-8472-83a7f0e9ece8.png)

preview
![image](https://user-images.githubusercontent.com/46588125/192934353-e1a23614-b07a-4016-862d-e18a6051d389.png)

**Comment by mitulpanch** [comment]
This is temporary issue. if persist then reopen
