### ISSUE TITLE
Document Page - Send SMS Icon should be change & change hover text on email and SMS 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1668]
**Describe the bug**
- change hover text on email -> Send Email
- change hover text on SMS -> Send SMS
- change SMS icon
- 
![image](https://user-images.githubusercontent.com/46588125/193399271-bfb8ef47-9fb1-4a3c-b98a-6408f4e13def.png)
![image](https://user-images.githubusercontent.com/46588125/193399304-63401413-1ab4-46a7-9104-f011f62f10bf.png)

**Comment by Avinash-ecb** [comment]
@dharmendraecb this SMS icon is not changed

**Comment by mitulpanch** [comment]
nothing else available so not changed
Its all right, we had searched for other icons

**Comment by Avinash-ecb** [comment]
Ok @mitulpanch sir so other things are done so closing this issue
