### ISSUE TITLE
Company Custom Field - Show custom field in group wise in setting page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1671]
**Describe the bug**
- show all custom field in group wise in setting page like showing in company custom field detail page

https://www.berrycast.com/conversations/bdd69dc8-4868-5f15-a55b-14aa8f91d411

**Comment by mitulpanch** [comment]
Duplicate

**Comment by mitulpanch** [comment]
https://github.com/Fammeo/EasyCloudBooks/issues/1682
