### ISSUE TITLE
Document Page - File Sharing Email Improvement Required

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1673]
**Describe the bug**
- No need of get in touch link
- improvement required of email design
![image](https://user-images.githubusercontent.com/46588125/193524175-3618c02f-72b1-4048-be17-0eaa2c3a692a.png)
![image](https://user-images.githubusercontent.com/46588125/193524497-7a0097e6-076d-43de-ac31-1ad566ff73f7.png)
- change accountant company name location
- can we remove google cloud plateform
- change footer fammeo to easycloudbooks
- remove mail us option from footer
https://www.berrycast.com/conversations/d208629a-ef66-554d-9cbf-a70f615d9851

**Comment by mitulpanch** [comment]
Email Template is common for all types of email,

Removing this with remove header footer from all Client Email to their clients,

We have created this template common for all client, and replacing field from company settings,

If all field are filled then this looks good.

Unsubscribe can not be removed, its required by third party providers.

**Comment by mitulpanch** [comment]
If further changes required then Please upload photo with changes, so will forward to developer

**Comment by mitulpanch** [comment]
#1684 created another issue for Preview Section

**Comment by vinpahilwani** [comment]
what is my role in this ?

**Comment by mitulpanch** [comment]
over phone, 
Remove get in touch if company's email is not coming

I guess its already Company's email, ECB not in picture anywhere
moving to Testing to confirm

**Comment by Avinash-ecb** [comment]
It is goint to company website
https://www.berrycast.com/conversations/18cb70a0-7f2a-5013-94db-599277ed68bb
