### ISSUE TITLE
Company/Contact Custom Field Page - Show full custom field name on hover in custom field list in setting page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1674]
**Describe the bug**
- When we open company/contact custom field page setting view there we can not see full custom field name 
- Show full custom field name when we hover that custom field

![image](https://user-images.githubusercontent.com/46588125/193731547-afeb4f40-8284-43b6-8b6e-6626b66191d6.png)

https://www.berrycast.com/conversations/40004522-fc6e-5d25-94ff-da42adddd822

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/194822706-c2d7ce4c-b8d7-4f1a-9228-623aeaf7979e.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/197332067-9ef42835-210b-47ec-9bc7-57c219397dcb.png)
![image](https://user-images.githubusercontent.com/46588125/197332135-0ea161a8-eb2c-449c-8d5f-48f0bd45f8df.png)
