### ISSUE TITLE
Transaction Page - When printing any transaction required bill no

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1675]
**Describe the bug**
- When printing invoice there is not any bill no clients want this bill no

**Suggestion**
- If we consider unique id as bill no then print unique id in invoice print
- they also want to change pattern of unique id, currently it is in bug mentioned below

**Github issue**
[ #1407](https://github.com/Fammeo/EasyCloudBooks/issues/1407)

![image](https://user-images.githubusercontent.com/46588125/193763968-5a3db30e-fb36-44e1-900f-4125ab69be1f.png)

**Comment by mitulpanch** [comment]
I guess this can be done from Print section on Settings Page, with keywords

**Comment by mitulpanch** [comment]
Sorry, This functionality is now removed, to get Multiple Print of Transaction, and Standardization

Now we do not take separate Header for Invoice, receipt etc.
we take Common Header,  so adding for Invoice is not possible.

This can be developed if required.

**Comment by mitulpanch** [comment]
over to @vinpahilwani

**Comment by vinpahilwani** [comment]
mujhe yeh samajh nahi aa raha plz aap log hindi me likho issue kya hai

**Comment by Avinash-ecb** [comment]
@vinpahilwani sir client ko bill (invoice) number chahiye,
 jo pahle other setting me transaction print me keyword add karke ho jata tha
 abhi multiple invoice print karne hote hai so ek comman header le liya hai and comman header me transaction unique id ka functionality remove kar di hai 
so vaha se abhi ye manage nahi hota

**Comment by Avinash-ecb** [comment]
abhi bill number ka solution nahi hua hai Sirvi Associates ke staff ko chahiye tha 
over to @vinpahilwani

**Comment by vinpahilwani** [comment]
unique number chahiye compulsory

**Comment by mitulpanch** [comment]
#1726  issue created for this issue
Closing this
