### ISSUE TITLE
Company Page - When setup(import) first time company and contact for new company It is slow By Suresh Sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1676]
**Describe the bug**
- when sales team gives demo to new client then he imports company and contacts to his company then it takes little long time like half an hour

**Suggestion**
- This process should be fast when first time sales team import company and contacts 
- Priority should be high

**Comment by mitulpanch** [comment]
This is fastest that we can support,

I dont think, without upgrading hardware this is possible.

**Comment by vinpahilwani** [comment]
mujhe isme konse sawal ka jawab dena hai?

**Comment by mitulpanch** [comment]
@vinpahilwani apko batan tha ke kuch develop karna he or current speed is ok?

**Comment by mitulpanch** [comment]
anyway agar kisi ke pass better idea he to process contact company import load then 
Please provide Logic here
@vinpahilwani , @sureshsirvi

**Comment by vinpahilwani** [comment]
i dont have any idea how we can speed up the import process.

**Comment by mitulpanch** [comment]
typical example of speed
Type | CreateDate | Finish Time | no of objects
---| --- | ---
Company Multiple Service Remove | 2022-10-16 16:31:12.47 | 2022-10-16 16:39:07.043 | -
company-contact | 2022-10-18 08:34:55.705 | 2022-10-18 08:47:48.475 | 600 Company / contact
projectimport | 2022-10-11 15:55:36.091 | 2022-10-11 16:00:13.092 | 22 Projects

**Comment by mitulpanch** [comment]
| Type | CreateDate | Finish Time | Time | no of objects |
|---|---|---|---|---|
| Company Multiple Service Remove | 2022-10-16 16:31:12.47 | 2022-10-16 16:39:07.043 | 8.5 minute | - |
| company-contact | 2022-10-18 08:34:55.705 | 2022-10-18 08:47:48.475 | 13 minutes | 600 Company / contact |
| projectimport | 2022-10-11 15:55:36.091 | 2022-10-11 16:00:13.092 | 4.5 Minute | 22 Projects |

**Comment by mitulpanch** [comment]
This is original example, in new company, i think this is good speed, lets wait for some time and see more examples 

I agree with @sureshsirvi, for a company waiting time happened due to some error, but in 95 % speed is great

I keep this issue open, and i have given some more priority to contact /company import lets take some more sample for other companies, then will do something

**Comment by sureshsirvi** [comment]
Sometimes when we onboard the new company ... Company-contact .. import takes around 1 hr to import for 500 Records.. I will post here latest example if any again observed the same issue.. till time i request to keep it open for few days.

**Comment by mitulpanch** [comment]
Additional Priority assigned for Company Import

Closing this for now

will reopen if issue persists

**Comment by mitulpanch** [comment]
Now Company Import has top 10 priority, along with New Company Setup, Payment Confirmation, and Other more critical things
