### ISSUE TITLE
Company/Contact custom field page - Label should be change Delete Custom Fields -> Deleted Custom Fields

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1677]
**Describe the bug**
- Label should be change 

**Delete** Custom Fields -> **Deleted** Custom Fields

![image](https://user-images.githubusercontent.com/46588125/193986598-50c3d8b8-6520-4e4c-bab5-ef98365fab5f.png)
![image](https://user-images.githubusercontent.com/46588125/193986633-e36583d5-8e1d-4f69-853a-e20caccf718c.png)

**Comment by mitulpanch** [comment]
done

**Comment by mitulpanch** [comment]
Deleted Custom Field (showing Past values for 30 Days)

changed to above title
