### ISSUE TITLE
Company Page - Custom Field - Remove "Deleted Custom Field" Module

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1678]
Problem -
User do not want to see this module

Details
1. This module is showing Values for Deleted Custom Field
2. There is not action or revert available, not possible to develop
3. This was requested by Client, who accidently deleted custom field, and want to get values again, Reverting was not possible so he insisted to at least show previous values, so he can recreate field and fill data from deleted custom field.
4. We had discussion and created this module 6 months back. module show Custom Field value which are deleted in past 1 month. 
5. These are deleted custom Field. just showing past values

Developed after discussion with all members. **this is not module related to current Migration of Custom Field Section in any manner**

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
My views on this module

1. It is good functionality
2. In past we have received Call from Clients for mistake by staff, Mistakenly removed Custom Field which had data filled, No of time.
3. This gives second change to user who want data back
4. There is not way any action available to this, as Custom Field, Create Delete is very complex logic of Creating and Removing. So we can not provide any action

**Comment by mitulpanch** [comment]
We have not changed any logic regarding this Module

**Comment by mitulpanch** [comment]
this is not new module, it was created 4-6 months back, since then nothing changed

**Comment by vinpahilwani** [comment]
I think hum yeh discuss kar chuke hai ki custom field delete hogi jab field delete hogi and agar service unlink hoti hai and custom field me value bari hui hai toh woh delete nahi hogi

**Comment by mitulpanch** [comment]
Ok so i take this as, Show this module no change required
