### ISSUE TITLE
Company/Contact Custom Field - Full column name is not displayed

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1679]
**Describe the bug**
- Show full column name on hover

![image](https://user-images.githubusercontent.com/46588125/194034271-da054caf-6ab4-4cb4-bdd9-cc493fc81281.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/194815798-4a22ed30-911e-4338-b06f-7f5a4c7f47f5.png)

**Comment by dharmendraecb** [comment]
Text in Hover

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/197323855-90907bff-abbb-4d4f-b12c-d24d007c5ca5.png)
