### ISSUE TITLE
Custom Field - New Logic for removing Custom Field Value

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1681]
Problem -
1. User provides Custom Field Values to Company over period of time
2. Custom field Attachment depends on a. Company Apply to Custom field b. Company-Service Custom Field Apply to
3. Company Custom Field stays with All companies
4. Company-Service Custom field comes to Companies where Service is attached, (Company Page - 1st step , Recurring Service)
5. Over period of time, user decides to Unlink Services from 1st stage of company, So eventually Custom Field related to Service also gets disconnected and goes to "Deleted Custom Field" flow, and gets deleted after 30 days of detachment from Service

Solution
Dont delete Custom Field values for Valid Custom Field, 
Delete Custom Field only when Custom Field Master setting gets Deleted.
Detaching, Attaching Service should not delete Custom Field Values from any object(Project, Company, Contact)

Initiated by @vinpahilwani
verified by @mitulpanch

**Comment by mitulpanch** [comment]
I have attempted this before, also changed all Database for this.
then @vinpahilwani said Its difficult to teach this logic to Clients , providing Support for this is difficult
so eventually i have removed / revoked all coding / changes created for this

So if this is required please write down, why this is required now
I am ready to re do everything again

Previous comments on this issue

https://github.com/Fammeo/EasyCloudBooks/issues/1658#issuecomment-1271063164
https://github.com/Fammeo/EasyCloudBooks/issues/1658#issuecomment-1260726686

**Comment by mitulpanch** [comment]
If this is passed
new Logic would be like
1. Delete Custom Field Value only when Custom Field Master Setting gets Deleted
2. Dont delete any other values from company as long as Custom Field is not deleted.
3. Service removing from Custom field , OR service detach from Company (1st step) will not delete Custom Field value from company
4. Delete Value only and only when Custom Field Removed from Master Settings

**Comment by mitulpanch** [comment]
as discussed over Phone @vinpahilwani => 
sir wants to keep custom field for Service Unlinked, but dont want to show them
-----
ex. 1. PAN cand attached to Accounting Service at first. Then taken data from Client, Filled Custom Field on company Page- PANCard with value "ABC"
2. Then after some time , user though that pan card is attached to Service "ITR" not accounting. 
3. so user removed service from pan card but didnt attach "ITR" service to custom field, stating Client has not came yet for "ITR" service
4. so system in background thought Lets delete custom field because it not relevant for Client any more.
5. User want to keep Custom field data, without attaching another service to Client, but dont want to see custom field data on Company page
above thing explained to me over phone @vinpahilwani 

I have no of problem on above structure,
Point 4. System process data on regular basis, and find what is relevant or not, keeping data but not showing is difficult to understand, and other system module will treat this data as correct, because system takes data from Database, showing / hiding do not matter to them
Point 5. we provide 30 days time to attach another service, then we think that this data is not relevant to remove it permanently. other option is to keep data and show to user, if data is important, we should not delete / hide data from user, as it was taken from them. hiding and keeping data is not good solution


------


but this is not possible in terms of this data is used over no of other things, and will create other dependent module more problem, instead just keep custom field has more value to it, and more understandable structure

above i have explained that only possibility is keep or delete, Keep and dont show is not good thing to do

**Comment by vinpahilwani** [comment]
Summary -
Agar custom field delete ho to hi data delete karna hai
Service unlink ho  toh bhara hua data delete nahi karna hai

**Comment by mitulpanch** [comment]
Delete nai he woh sare Custom Field , above section me dikhenge,

Show all custom Field, which are valid
I have confirmed this over phone

**Comment by mitulpanch** [comment]
Approved by @vinpahilwani

**Comment by mitulpanch** [comment]
> If this is passed new Logic would be like
> 
> 1. Delete Custom Field Value only when Custom Field Master Setting gets Deleted
> 2. Dont delete any other values from company as long as Custom Field is not deleted.
> 3. Service removing from Custom field , OR service detach from Company (1st step) will not delete Custom Field value from company
> 4. Delete Value only and only when Custom Field Removed from Master Settings


@vinpahilwani agreed for all of this, i have confirmed over phone, do not need to hide custom field which are not applicable,
if data is present then keep Custom field. 

Delete only and only when Master Custom Field gets deleted

**Comment by mitulpanch** [comment]
If custom Field is not attached , and dont have value then we will remove custom field. as it not applicable and not filled

**Comment by mitulpanch** [comment]
This is applied to All Pages, Company , contact , Project Custom Field, common functionality
