### ISSUE TITLE
Custom Field - Master Settings - change sort order to Group

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1682]
Problem-
User wants to see Custom Field Master Settings with Grouping, so same custom Fields could be edited quickly

Solution
Grouping is not possible along with paging, 
so just sorting with group names is passed

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
This is for All pages,

Company Custom Field , Settings
Contact Custom Field , Settings
Project Custom Field , Settings

Sort Order => groupname

Previous Sort order was SO from custom Field

**Comment by mitulpanch** [comment]
This is not same as Sorting inside 

company => fill values of Custom Field sort
Sort inside value is like-
Get All Custom Field with SO
then Group them with SO as first priority
1st group will be having top Custom Field SO, then that group will show all custom field with same group regardless of SO of Custom Field

This kind of logic is not possible in Master Setting as that have Paging structure

So finally agreed to jjust sort according to group, not like values so

I have explained this to @vinpahilwani over phone

**Comment by mitulpanch** [comment]
I consider this as granted permission over phone, so forwarding this to development

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/201570459-0fe451a7-54a3-4e2e-b340-09de3a9e616a.png)
![image](https://user-images.githubusercontent.com/46588125/201570503-3881a021-8d60-4564-89a3-1f0aa46a135f.png)
![image](https://user-images.githubusercontent.com/46588125/201570592-c9d2d9fc-a8e2-4a03-8feb-e42a1336dbc2.png)
