### ISSUE TITLE
Document Page - New design for Company Selection

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1683]
Show Company Full Name instead of just Icon

Common for Common Folder

Initiated by @vinpahilwani 
verified by @mitulpanch

**Comment by mitulpanch** [comment]
![image](https://user-images.githubusercontent.com/5259926/194463257-c42c13d6-1fa0-4fc0-88de-b7dda2b7dfdf.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/194820864-6a0a38d3-112b-43b6-9003-512903a0db80.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/201455423-fb50a5b1-e93f-488b-9b7a-b90a06ba8736.png)
