### ISSUE TITLE
Document Preview - change Layout

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1684]
![193524497-7a0097e6-076d-43de-ac31-1ad566ff73f7](https://user-images.githubusercontent.com/5259926/194474181-af944dc8-771c-4157-8164-df4dba6074e0.png)

**Comment by mitulpanch** [comment]
1. Move Company name to Top
2. remove Google Cloud Platform
3. Copyright easycloudbooks
4. If possible remove Column name from bottom
5. remove if you have any query option

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/194842338-49a4770e-f781-402d-beb0-72393deed47f.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/200256353-cc045038-7b1b-4b42-b7cb-c680ec41c32f.png)
