### ISSUE TITLE
Company Page - Search by staff filter required in company page By Aziz

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1686]
**Describe the bug**
- clients want to filter company by staff like project page

![image](https://user-images.githubusercontent.com/46588125/194487889-731d14b3-d42c-42f5-a8f7-a20914f97c67.png)

**Comment by mitulpanch** [comment]
Not sure whats this?
I guess by Company relation manager

**Comment by vinpahilwani** [comment]
haan wohi hai relaitonship manager wala usko bahar chahiye

**Comment by mitulpanch** [comment]
Please confirm dena he?
There are already 8 filters, and more 3 filter which are hidden but visible on other modes
This can be done from Query Builder

**Comment by mitulpanch** [comment]
Timing -
Frontend - 2 hours
backend - 30 minute

**Comment by vinpahilwani** [comment]
Put this on hold for sometime we will deal with it later

**Comment by mitulpanch** [comment]
Closing to clear board
