### ISSUE TITLE
Transaction Page - Ledger Preview comes with invalid Date

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1688]
https://eccpl.easycloudbooks.com/transactionprint?crids=E6zdqStmU0yN90CepTcmdQ&startdate=2022-08-25T00:00:00&enddate=2022-10-02T23:59:59&mode=0

Startdate for above link should be in utc.
above link comes with 0 hours, gives un expected Transactions in list

Initiated by - @vinpahilwani - Deepa Pahilwani
verified by @mitulpanch

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/201577464-80c1147a-38e3-4a75-abab-68247d1b9872.png)
https://rajassociates.easycloudbooks.com/transactionprint?crids=uAvuD_gHykyJBSlwbzZx6Q&startdate=2021-03-31T18:30:00&enddate=2023-03-31T18:29:59
