### ISSUE TITLE
Contact page - Status filter is not working in contact position page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1689]
**Describe the bug**
- When we filter company list in position page with status filter it does not applies that filter and not working

![image](https://user-images.githubusercontent.com/46588125/194523862-851f63ab-ec0e-413e-949b-11faa54d4ed9.png)
https://www.berrycast.com/conversations/389a3a1c-7932-5650-9430-d6a020106992

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/389a3a1c-7932-5650-9430-d6a020106992
In contact page position view there is not also working please check

**Comment by mitulpanch** [comment]
Removed status filer ,as api was not supporting that

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/196156436-01758da7-6384-4239-817b-4d5cac77c370.png)
