### ISSUE TITLE
Project Page - Make due date column value (-) center align  

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1690]
**Describe the bug**
-When there is not any value in due date column there is showing - (dash) make that dash center align

![image](https://user-images.githubusercontent.com/46588125/194526913-856e5bcc-5a5c-49c5-9968-7743044d6692.png)
https://www.berrycast.com/conversations/744e0d1c-e99e-5d94-b7df-212f1e7d8158

**Comment by vinpahilwani** [comment]
No need to do this

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/196159779-e0fb573c-ed2b-4a9f-8810-0d8c35968581.png)
