### ISSUE TITLE
Project Custom Field - Remove default Service Filter

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1691]
Problem-
when User work on this page, 
it is very difficult to find project for Pending Custom Field by going to all service

Solution
Remove Default Service Filter
Remove Default Current Year Filter

Add Default filter for Pending Status

verified by @mitulpanch 
approved by @vinpahilwani

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/197319897-3e694cdf-4db3-4243-a4fe-7b2694cd27fd.png)
![image](https://user-images.githubusercontent.com/46588125/197319912-a62d4f47-88b4-478b-b52d-d71a3a354a9d.png)
