### ISSUE TITLE
Custom Field - Give Reminder date with Note option on different Objects

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1692]
Problem-
When user works on any object like Company, Contact , Project Custom Field Page
they usually call Client and try to take data from Clients.
Some times clients says please call after 5 days etc
So User get confuse that what need attention and what's already done

Solution-
1. Provide Option to give reminder Date with Note on each Page
2. Adding Column for Reminder on main list. to sort accordingly
3. Default sort order will be Reminder Date
4. This is not related to any other module
5. Log for no of attempts is not required as i have discussed with @vinpahilwani 
6. Just next reminder, with note required
7. Filter required for Objects with empty custom field count > 0

Technical details
1. Adding Column for Reminder Date. not sure about default value
2. Need to add 2 new columns
3. Planning to add temp value, not keeping data for Past values for Comment and reminder date.
4. Sorting will be okay for reminder date
5. after Object gets all custom field, reminder date and comment get removed automatically
6. Adding Filter for Custom Field Values => All, Empty, Filled (@vinpahilwani please provide english)
7. Default filter will be empty count > 0

Initiated by @vinpahilwani 
verified by @mitulpanch

**Comment by mitulpanch** [comment]
We keep only one value for Note, so no previous note will be present on system
We just update same field with new note and new reminder date
and delete after All custom field completes

**Comment by vinpahilwani** [comment]
done

**Comment by Avinash-ecb** [comment]
Next reminder date picker not working
![image](https://user-images.githubusercontent.com/46588125/195756749-33d2ac98-3f73-4387-a119-b338fb50119b.png)
![image](https://user-images.githubusercontent.com/46588125/195756695-97eb9cc0-0525-4153-bbc1-6728b90067ff.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/200527924-a7fbb0ca-9e7d-4f8c-b16c-6e1f10b7efb3.png)
![image](https://user-images.githubusercontent.com/46588125/200528167-788dd86c-a9f6-4694-9042-f7ac86c78418.png)
