### ISSUE TITLE
Custom File Module - New Functionality

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1693]
Problem -
1. Taking Files from Clients is pain
2. User dont have any functionality that covers this on ECB
3. New Module like Custom Filed can solve this problem

Brief -
1. Custom Files module requires list of Files like Custom Fields
2. Apply to will be same as Custom Field - Company, Company-Service, Contact, Project, Project-Service, Currently these are enough, later we can add more
3. Project Custom File is a page like Project Custom Field with Role => Project Custom File => Read, Edit (keeping it same as Custom Field, and Roles are separate from Project, so others can use this)
4. Company Custom File, Contact Custom Files => Role will be => Company => Read Custom File, Edit Custom File, and same for Contact
5. All 3 will have their separate Page like Custom Field, and Setting will be on that pages for Master Settings
6. Reminder date / Note structure required for User to identify whats done, this is not log entries, just one entry with next reminder date and note
7. Project member can change files from Project Page
8. File approved / remove required to complete File requirement
9. 1 Custom File can take multiple Files , only approve can finish Custom File requirement, until then its incomplete with potential files
10. File of files can be approved without file, in view of Physical file received. User may need to select Option from dropdown
11. Custom File can be approved without  file OR physical file in view of Not applicable for some clients / projects
12. single File of particular Client / Company / Project is not possible, only attach through Custom File Create and attach service options available, in favor of standardization, easiness of module keeping it same as Custom Field
13. These files wont be visible anywhere else, except to respective section ie, Company Custom Files will be visible at Company Details section and Company Custom Field Page(like Custom Field)
14. Custom Query Builder will be available for Query to find No of Files empty, complete, etc to trim down on searching objects with files
15. Micro management is required on File approval / rejection because of multiple files inside 1 custom file

**Comment by mitulpanch** [comment]
Sections =>
Custom File -
1. Name, Description (optional), Apply To, Sort Order , Group
2. Role - Create / Edit => Custom File => Create
3. Role - Delete => Custom File => Delete
4. Paging - 25, Sorting => Group Name
5. Apply To can be changed => data persists only on => Project to Project-Service OR Company to Company-Service or vice-versa
6. Type not required

**Comment by mitulpanch** [comment]
Section => 
Object Custom File  List View (Contact / Company / Project)
1. list of Objects same as Custom Field list , Company list, Contact List , Project List with Pending default filter 
2. Custom File list with approved status (check green icon)
3. click will open side window like custom field, 
4. Default sort => reminder date asc, need to work should be first
5. Default filter => empty file count > 0
6. keep as same as custom field possible
7. max 100 custom files per object row
8. custom file column sort will be create date of custom file master settings, older first
9. Project Custom File => default filter Pending Projects
10. Sorting possibility => file empty count, reminder date, object parameters ie. Company => Company Name, Contact => Contact Name, Project => Company Name, Year, Service

**Comment by mitulpanch** [comment]
Section => 
Object Custom File Detail side popover (Company / Contact / Project)
1. 2 possibilities =>a. List of Files with 
          columns => Name, Approved?, Mode(Cloud file, Physical, Not Applicable), Last Update, Update By
                b. Folder like view => Name and Approval icon
2. Usability wise List of file view would be good to understand for user
3. Approval required on each custom file folder, to mark as complete
4. dropdown required for status => Physical file OR Not Applicable OR Cloud File
5. Upload more file can be done regardless of file status, in some case Physical File and part cloud required, so i dont want to set any rules, anyone can upload files and set approval with any options
6. User can remove / Delete files from any folder, removing file will reset Approval Status
7. Removing Approval status of any approval file will trigger Reminder date reset to today
8. No special note available to each file, instead common note feature can be used to give any note
9. Client Update of any file will trigger reset of Reminder Date to today for user
10. No notification is considered yet, Task Module will help in this regards for any immediate attention from Project Manager / Client
11. if all files complete then Project will give File Complete Badge over List view with Team Pending badges
12. Not Applicable files also need approval, User need to set Not applicable then need to approve file to complete custom file
13. Click on any Custom File will open another side view popover =>
     a. List of files with Columns => Filename, Upload Time, Upload By, action (delete button)
     b. Above in header => Approve button / Refuse button
     c. More header button with arrow dropdown to set Not Applicable / Physical File => this will set status of file with
         Physical / Not applicable mode => this will remove any of uploaded files and Custom File will Auto approve
     d. Upload button will open side window to Upload new files, same as other upload sections
     e. Changing to Physical File Mode will remove already Uploaded Files

**Comment by mitulpanch** [comment]
I guess i have completed all aspects of this module, but please give your views @vinpahilwani, @sureshsirvi  on Module will give more direction

**Comment by mitulpanch** [comment]
Future planning =>
Client can upload Input type of Files from Client Portal

**Comment by mitulpanch** [comment]
Custom Files have 3 types => Common for All Objects (Company / Contact / Project)
1. Input File => Required to start project OR Client can upload this files 
2. Process File => General meaning - Client dont want / can not see this files, but incase of Project- Project Manager need to add this file at time project on going (any kind of Processed data)
3. Output File => Required after Project Completion, not sure meaning of Company / Contact Module

These are common types, will come to all objects, separate coding / types of object will make this very difficult to code and understand

**Comment by mitulpanch** [comment]
I guess i have completed all aspects of this module, but please give your views @vinpahilwani, @sureshsirvi on Module will give us more direction

**Comment by mitulpanch** [comment]
This module donot change any existing functionality on any module, everything is new

**Comment by mitulpanch** [comment]
No Comments from @vinpahilwani , @sureshsirvi 
I consider this as approved, as everything is api ready now, and discussed over phone

**Comment by Avinash-ecb** [comment]
After discuss with @mitulpanch sir on phone 
Project custom file page apply to logic
- Custom file disiplay logic
1. company specific : It will show custom file field to those company which is matching with service and company which is attach to custom file when creation of custom file 
2. project service : It will show custom file field to those company which is matching with service only which is attach to custom file when creation of custom file 

- Uploaded custom file share logic
 After uploaded some file to custom file field it will share only to that company project which match same year and period only in both custom file type
