### ISSUE TITLE
Company/Contact/Project custom field - We have to click 2 times to on/off custom field value

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1694]
**Describe the bug**
- when we try to make customfield value on/off then we have to click 2 times 

![image](https://user-images.githubusercontent.com/46588125/194688377-fe212a59-02a8-42d6-a114-40545817fd24.png)
![image](https://user-images.githubusercontent.com/46588125/194688386-e8d0328f-bf4b-4604-8554-3642f9de5271.png)

https://www.berrycast.com/conversations/d97e3cd8-1334-506d-9af5-ab0a16aa2fec

**Comment by mitulpanch** [comment]
This is not a issue
First we only load value, on click we brink status changes action plugin ON/OFF
on click of plugin value changes

this behavior can not be changed
