### ISSUE TITLE
Contact Page - Custom Email with Multiple Action

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1696]
Problem -
User wants to send custom random email from contact page with multiple action

Solution-
1. Select Multiple Contacts
2. Select Custom Email from Action menu
3. Type Subject, Email Content
4. Send

Technical -
1. This is common email to all contacts, Key replacement is not part of this
2. This email can not be personalized (like Hi Vinod Pahilwani,)
3. Common Email to all.

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by vinpahilwani** [comment]
Ok

**Comment by mitulpanch** [comment]
This is required for -
1. Contact 
2. Company
3. Project
4. Transaction

Works in Background
Confirmed over Phone with @vinpahilwani

**Comment by mitulpanch** [comment]
Api ready
