### ISSUE TITLE
Company Fees contract Page - Show total annual fees in blue color 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1697]
**Describe the bug**
- Show total annual fees in blue color so user can know it is clickable

![image](https://user-images.githubusercontent.com/46588125/194795181-2d289250-d8ca-4747-ba11-678b66858d0d.png)

https://www.berrycast.com/conversations/1c43393c-4399-51a4-94f2-7a87dbadb7d2

**Comment by mitulpanch** [comment]
This does not look good, in terms of theme

This does same thing as  +Service button just above it

still do you want to add color to it! please approve

**Comment by vinpahilwani** [comment]
chahiye

**Comment by mitulpanch** [comment]
over phone, Ignore theme, just give blue color

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/207242679-3d989212-5c4b-42fc-9c47-b117cb6e5093.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/222635110-c7f7be2f-93b0-4a69-90a2-05619a512bb7.png)
