### ISSUE TITLE
Service Page - Change label in filter Is Scheduler-> is Recurring?

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1698]
**Describe the bug**
- Change label in service filter Is Scheduler-> is Recurring?

![image](https://user-images.githubusercontent.com/46588125/194795425-8b111d26-3162-4a7c-90dd-2ce81ca0b6c5.png)

**Comment by mitulpanch** [comment]
List => HaveScheulder => Is Recurring ?
Filter => Is Scheduler => Is Recurring ?
when filter applied => Is Scheduler => Is Recurring ?

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/195770872-6010f31c-24f6-4a49-a46f-9c517bc7c7b2.png)
![image](https://user-images.githubusercontent.com/46588125/195770900-e6b07d25-d0e5-467b-82ac-b25f0f54def5.png)
