### ISSUE TITLE
Project Page- When change pagination selected project get unselected By Sirvi Associates Staff

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1700]
**Describe the bug**
- When we select multiple project and change pagination previous selected project is unselect

![image](https://user-images.githubusercontent.com/46588125/194816723-0041f39a-c8b4-4e4e-a3d7-65410dff2b3f.png)
![image](https://user-images.githubusercontent.com/46588125/194816841-a7c8701c-12ca-42ba-82ff-fd8bcd44710e.png)

**Comment by mitulpanch** [comment]
that is no bug, paging change complete context , so we dont keep previously selected
