### ISSUE TITLE
Company Page - Custom Field View - Sort Order of Custom Field Column should be Group Name

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1701]
Problem -
User wants to see Column in group Name sort order

Technical Detail-
This is not Grouping, 
We can just sort with Group name, All custom Field in group are not coming
Custom Field Column comes in dynamic way, if company has custom field then only system gets custom field column
This is no way similar to Inside view of Custom Field Data fill popover, that has different sort order

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
This is applied to All Custom Field Pages, Project, Company, Contact Custom Field

once again Sort order for this is not same as Inside Data fill popover, i have explained this to @vinpahilwani ,and he agreed with terms

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/204513674-11cc23a8-16e1-43e6-86cb-0b265adc9209.png)
![image](https://user-images.githubusercontent.com/46588125/204513887-439719e7-5331-4bee-8b8f-42faf7ce5414.png)

![image](https://user-images.githubusercontent.com/46588125/204513574-ebff0648-2682-4c85-91b6-e53a6de0c148.png)
