### ISSUE TITLE
Project Multiple Import - Show All services - Assign Project Manager according to Custom logic

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1703]
Problem -
Currently user can only see Services who have project manager,
User wants to create Projects from here for All Services

Project Manager Logic-
1. Copy Last Project if Possible
2. Then Service Managers
3. else Owner
4. Or System will find someone, from own logic

Technical -
This was not initially supported, as this module is for New Companies
But some companies still use this as a regular practice

but to ease load Service managers was coming directly to Project instead of searching Last Project and other Logics
Adding Too much of Logic will impact speed to system, we have provided this logic to standard Project Create Method, we wanted to encourage user to use other methods, so this was limited at first, allowing only 500 Projects at a time, but that too removed ,
now 5000 projects getting created will give more problems

All user will use this feature to create Project instead of other methods

No doubt that this will impact Speed of Project Creation, and i need to create other mitigation for no of project handling for system

**Comment by mitulpanch** [comment]
This is confirmed over phone

**Comment by mitulpanch** [comment]
We do take price from Other Automated Method, 
I remember @vinpahilwani stated this should be free as it is triggered by user, at time of limit increase from 500 to 5000
So revenue will hit too if this becomes regular usage

**Comment by vinpahilwani** [comment]
chahiye

**Comment by mitulpanch** [comment]
After discussion over phone @vinpahilwani 
We agreed on 
1. New Company will get this feature as free for 1 month from Create Date
2. All other Project after grace period (1 month), projects will be charged as same rate as Scheduled Project

**Comment by mitulpanch** [comment]
Pricing is still need to be developed
I will create new Issue for that

**Comment by mitulpanch** [comment]
This is issue is solved in terms of giving custom Login in Project Import logic
#1738 Start Pricing Issue for above requirement

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/205032994-2a62a260-b7f1-49aa-8a30-4671de878a75.png)
