### ISSUE TITLE
Contact - Multiple Delete Action

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1704]
Problem-
User wants to Delete Multiple Contact At a time

Technical Detail-
1. This is heavy Task on background
2. anything more than 20 should go to background Task
3. System will take order to Delete contacts on Background Engine
4. Once Triggered Task can not be stopped
5. Contacts will be visible on Contacts Page, until system processes it
6. Contact will be valid and working until system removes them
7. This also depends on Load from other Engines

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
1. anything from Multiple action will go to Task
2. Priority will be dependent on other task pending execution
3. Need to Create Background Task for this

Time required - 2 hours for Background Task
1 Hour for Design Validations

**Comment by vinpahilwani** [comment]
chahiye

**Comment by mitulpanch** [comment]
API Ready

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/42f5cb2e-c282-5ffc-9318-cd8bb81aa325
