### ISSUE TITLE
Company Page - Multiple Delete Action

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1705]
Problem-
User wants to Delete Multiple Company At a time

Technical Detail-

1. This is heavy Task on background
2. anything more than 20 should go to background Task
3. System will take order to Delete companies on Background Engine
4. Once Triggered Task can not be stopped
5. Companies will be visible on Company Page, until system processes it
6. Company will be valid and working until system removes them
7. This also depends on Load from other Engines

Initiated by @vinpahilwani
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
1. anything from Multiple action will go to Task
2. Priority will be dependent on other task pending execution
3. Need to Create Background Task for this

Time required - 4 hours for Background Task
1 Hour for Design Validations

**Comment by vinpahilwani** [comment]
chahiye

**Comment by mitulpanch** [comment]
API Ready

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/e2bc5ba3-cfab-5f93-b445-395c85f478c9
