### ISSUE TITLE
Transaction Page - Multiple Delete Action

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1706]
Problem-
User wants to Delete Multiple Transaction At a time

Technical Detail-

1. anything more than 20 should go to background Task
2. System will take order to Delete Transaction on Background Engine
3. Once Triggered Task can not be stopped
4. Transaction will be visible on Transaction Page, until system processes it
5. Transaction will be valid and working until system removes them
6. This also depends on Load from other Engines

Initiated by @vinpahilwani
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
1. anything from Multiple action will go to Task
2. Priority will be dependent on other task pending execution

Need to Create Background Task for this
Time required - 3 hours for Background Task
1 Hour for Design Validations

**Comment by vinpahilwani** [comment]
chahiye

**Comment by mitulpanch** [comment]
API-Ready
