### ISSUE TITLE
Transaction Page - Payment Mode required on List

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1707]
Problem -
New Column required

Design-
This page opens on side pane on some places
additional column may give design errors, some mobile , tablet view issue due to tight design spaces

Initiated by @vinpahilwani 
verified by @mitulpanch

**Comment by mitulpanch** [comment]
Time Required -
15 minute

**Comment by vinpahilwani** [comment]
done

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/202846354-29d5d9b3-5fbd-462e-9107-225afbc3da4f.png)
