### ISSUE TITLE
Contact Page - can we display count of companies he is holding position in

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1709]
**Describe the bug**
- can we display count of companies in column of contact list he (Contact) is holding position in it

![image](https://user-images.githubusercontent.com/46588125/194993033-e69d04cd-a74c-44e6-87b8-19d14c52f7b8.png)

**Comment by mitulpanch** [comment]
Yes it is possible.
but i guess next step would be Open Position window on click
That i dont want to do because of difficulties on popover inside Contact Edit / View Mode
Without that no problem

**Comment by mitulpanch** [comment]
Time -
30 minute design
10 minute backend

**Comment by vinpahilwani** [comment]
I think we should provide this

**Comment by mitulpanch** [comment]
popover coming?

**Comment by mitulpanch** [comment]
with popover -
design - 3-4 hours
20 minutes - backend

**Comment by vinpahilwani** [comment]
popover coming matlab?

**Comment by vinpahilwani** [comment]
nahi theek hai nahi aayega

**Comment by mitulpanch** [comment]
Over phone
I have explained difficulties in developing this, because of multiple page mode,
and this is already available inside contact view

Closing this as it is not required

**Comment by mitulpanch** [comment]
Over phone
I have explained difficulties in developing this, because of multiple page mode,
and this is already available inside contact view

Closing this as it is not required
