### ISSUE TITLE
Contact Page - We should show actions on contact view page which is available in actions button

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1712]
**Describe the bug**
- jo action hum list view pe contact me dete hai woh humein contact ke detailed view pe bhi deni chahiye jaise send app notification, send email, send sms etc

![image](https://user-images.githubusercontent.com/46588125/194995564-9020a514-fccb-4d97-9374-ded7ac2be8fe.png)

**Comment by mitulpanch** [comment]
i consider this a new concept
I welcome this suggestion

This is very complex action available logic, what is available , whats not depends on selection
bringing this requires new logic for single object selection

Time Required -
1. New compact button design in Menu style over all object preview
2. Role check mechanism
3. Api calls for signle object

considering all this Time would be around 6-8 hour - frontend work
0-30 minute - backend work

**Comment by mitulpanch** [comment]
After discussion with @dharmendraecb 
This will take about 2 days
