### ISSUE TITLE
Company Custom Field - New Reminder Date with Note Required

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1713]
Problem -
User who works on this page, they can not work efficiently without difference between whats done and what needs attention

Solution-
1. Reminder Date with Note option on each object will solve this problem
2. Reminder date is from tomorrow to next 1 month max date
3. once All Custom Field Complete this will be cleared
4. Only 1 note is present at time, no history, log entry available for this
5. Note max 500 characters, with sentence case validation
6. anyone with Edit Custom Field role can change this
7. There is no Clear Button, user can only complete all custom field to Clear this
8. We have default filter, of show only remaining object will help in this regards
9. only available through Company Custom field change Value for Company view will have this popup. in order to change value user needs to open custom field data view for single company and then add note with reminder date
10. Reminder date column will be available to list of objects, default sort will be reminder ascending, oldest first

initiated by @vinpahilwani 
verified by @mitulpanch

**Comment by mitulpanch** [comment]
This will remove default sorting of empty custom count, because of reminder date sorting

**Comment by mitulpanch** [comment]
Time required - 
backend - 6-8 hour
frontend- 4-6 hour

Contact =
backend - 1 hour
frontend - 1 hour
Project =
backend - 1 hour
frontend - 3-4 hour

**Comment by mitulpanch** [comment]
i have explained this over phone to @vinpahilwani

**Comment by mitulpanch** [comment]
This also applied to 
Contact Page - Contact Custom Field - Reminder note
Project Page - Project Custom Field - Reminder note
1. for Project -> Role => Project Custom Field => Edit
2. from Inside Project / on Project Page => Member Role

**Comment by mitulpanch** [comment]
already live, leaving for @vinpahilwani to comment

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/eef466f2-3f77-54ca-97ae-9db59454f739
