### ISSUE TITLE
Company customfield page - company-service type customfield is creating without service

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1715]
**Describe the bug**
- when we create company-service type it shows required but it is creating/updating without service

![image](https://user-images.githubusercontent.com/46588125/195014342-2fd6ee81-9f6f-43f5-b1b7-1d17ce1a2d1e.png)

**Comment by mitulpanch** [comment]
That is not a problem,
User can attach service at any point of time

**Comment by mitulpanch** [comment]
There are other ways like import will create service without services attached

**Comment by Avinash-ecb** [comment]
then service has red star it should remove

**Comment by mitulpanch** [comment]
ok removing star

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/195049005-1356e53b-0cdf-46fa-8af5-16c3fa27bfa2.png)

**Comment by Avinash-ecb** [comment]
![image](https://github.com/Fammeo/EasyCloudBooks/assets/46588125/16eefafb-ef1e-44f1-8d86-5b616276e6eb)
