### ISSUE TITLE
Project Custom field - When create customfield it shows already exist

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1717]
**Describe the bug**
- when we try to create customfield name "test project to company" it shows Duplicate Key Name already Exists
![image](https://user-images.githubusercontent.com/46588125/195060049-f394b764-e704-44ad-8623-d7bd579d82ea.png)

https://www.berrycast.com/conversations/e041398f-da45-57a7-9573-dde6c7ec2337

**Comment by mitulpanch** [comment]
![image](https://user-images.githubusercontent.com/5259926/195107684-95b6569c-852d-4423-8cc9-8832064f830f.png)
its already exist
