### ISSUE TITLE
Company Custom Field - Set All in single button

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1718]
Set "Export" button inside Import Menu

![image](https://user-images.githubusercontent.com/5259926/195100176-65928907-3e28-48b1-832b-8095ebed8173.png)

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
This applies to 
Contact Custom Field also

**Comment by mitulpanch** [comment]
approved over phone by @vinpahilwani

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/197329999-7bd3b2e9-714a-4ace-8587-94be2fe1f3bf.png)
