### ISSUE TITLE
Company Custom Field - Remove Processing Button

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1720]
Problem -
@vinpahilwani dont want to show this to user

Brief-
System works in background to update custom field
If we dont show this, User might think that this is error

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
![image](https://user-images.githubusercontent.com/5259926/195261057-af3f4151-011f-45da-b979-f8269afc5ccd.png)
Remove Processing

**Comment by mitulpanch** [comment]
System will work in background, just dont show user

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/197123481-ec89913b-55fa-418d-8d8f-5fac29c7bf16.png)
![image](https://user-images.githubusercontent.com/46588125/197123592-8a1a94c1-31c2-471e-be78-8f777f222153.png)
![image](https://user-images.githubusercontent.com/46588125/197124089-37cfd5ff-42c0-41b6-bef4-229be26fe4c0.png)
