### ISSUE TITLE
Project Page - Add Badge for All Custom Fields complete

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1722]
Problem -
User cant find Project to work with, with all Custom Field requirement complete

![image](https://user-images.githubusercontent.com/5259926/195289157-e7010c4b-f016-49c6-a28f-f85f60311679.png)

solution -
1. Add new badge beside Team Required icon
2. So Project manager from List can see badge to get Project Status about Custom Field
3. Along with this Query Builder will be available to Get All projects with 100 % custom Fields

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
API ready

**Comment by mitulpanch** [comment]
All things explained to @vinpahilwani 
No comments received so moving to production


This is based on Project Custom Field count
Company Custom Field is no way related to this

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/203698383-c346099d-0b5c-4818-812f-16a8d9e51b09.png)
https://www.berrycast.com/conversations/c89009aa-060d-52e0-8d0a-17e1a1fce1fe
