### ISSUE TITLE
Email Preview - Change design

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1723]
Problem -
Old design gives lot of problem-
and no migration possible

Solution-
Change UI and set Api based Preview
New Design required

Initiated by @mitulpanch

**Comment by mitulpanch** [comment]
API - /api/other/getemailpreview

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/202360280-d54c7326-cea0-4d1e-8e7a-0fe0f9afe4ff.png)
