### ISSUE TITLE
Role Page - Edit project custom field role not working in role page 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1725]
**Describe the bug**
- User has read and edit project custom field role but user can not edit project custom field 
- create button also not display

![image](https://user-images.githubusercontent.com/46588125/195503915-7ab53fef-d4ac-4595-8107-cd0ad4316138.png)

![image](https://user-images.githubusercontent.com/46588125/195503860-46e9bc3a-b0c1-4563-859b-f05cb93300c1.png)

https://www.berrycast.com/conversations/16ce6c63-5592-5e56-a905-391d81d20625

**Comment by Avinash-ecb** [comment]
https://github.com/Fammeo/EasyCloudBooks/issues/1633
duplicate

**Comment by mitulpanch** [comment]
Custom Field Role check hota he,
Project Custom Field nai
