### ISSUE TITLE
Contact Custom Field - Issue while type conversion from text to number 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1728]
**Describe the bug**
- After conversion it showing text if we edit and added a number or remove text then also shows old text 
- After conversion if we edit blank customfield and added a number then also it shows blank 

![image](https://user-images.githubusercontent.com/46588125/195969629-38bae90d-cac1-49b2-aaa7-159d6184e8b5.png)

![image](https://user-images.githubusercontent.com/46588125/195969610-a3c59865-b00e-4b6f-99ac-a1689cef8a4d.png)

https://www.berrycast.com/conversations/dce19a7f-8bc4-5ab1-ab69-27c6da4c7d18

**Comment by mitulpanch** [comment]
I believe this is fixed, but not moved
