### ISSUE TITLE
Contact Customfield page - Issue while conversion from text to boolean

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1729]
**Describe the bug**
  - After conversion it showing text if we make it on then also it shows old text
  - After conversion if we make on blank customfield it does not show on text

![image](https://user-images.githubusercontent.com/46588125/195970245-219c164e-c9aa-409b-ac1e-41f449d8133f.png)
![image](https://user-images.githubusercontent.com/46588125/195970266-960d760f-56c8-4904-abf8-03c5f187b97d.png)

https://www.berrycast.com/conversations/445b7122-5f17-55d9-b900-f6edd5c6e759

**Comment by mitulpanch** [comment]
I believe this is fixed, but not moved

conversation takes some time to execute, till then old values are displayed
