### ISSUE TITLE
Project custom field - False company badge details 

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#173]
### Project custom field - False company badge details 
![2021-01-27_16-40-15](https://user-images.githubusercontent.com/46882964/105984365-02174980-60c0-11eb-95cd-b0fd06b46649.png)

**Comment by ajayrajecb** [comment]
badge me accounts billed , unbilled abhi bhi galat aa raha hai

**Comment by mitulpanch** [comment]
accounts billed?

**Comment by ajayrajecb** [comment]
> accounts billed?

both, billed , unbilled, 
vijay sales pe mouse over kr k unbilled pe jayiye.

**Comment by mitulpanch** [comment]
unbilled projects?

**Comment by ajayrajecb** [comment]
> unbilled projects?

yes, badge pe count hai, but on click accounts k page pe 0 hai

**Comment by mitulpanch** [comment]
badge reload hone me time lagta he, ek bar hover karke thode time bad page reload karke dekho

**Comment by mitulpanch** [comment]
akshay & gst wala company me mene thik kiya he
