### ISSUE TITLE
Contact Custom Field Page - Issue while type conversion from text to date

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1730]
**Describe the bug**
- After conversion from text to date type if we edit filled customfield value it shows old value
- After conversion if we edit blank value and we added date then also it shows blank

![image](https://user-images.githubusercontent.com/46588125/195973110-691531ae-4f67-4597-bcf3-9e530bdf55b1.png)
![image](https://user-images.githubusercontent.com/46588125/195973118-7098ff40-c0bf-440c-97b9-271f978255af.png)

https://www.berrycast.com/conversations/63d81fd9-e449-52ee-8525-db6a2ac827df

**Comment by mitulpanch** [comment]
I believe this is fixed, but not moved

**Comment by mitulpanch** [comment]
Revert back if still error
