### ISSUE TITLE
Contact Customfield Page - Url type custom field accepting number and text values

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1731]
**Describe the bug**
- When we create a customfield of type url then it displays in contact page 
- We can added in that customfield text and numbers it should allowed only url

![image](https://user-images.githubusercontent.com/46588125/195973623-750dc6d7-f1d9-4cb2-ab34-3f2fce68e295.png)
![image](https://user-images.githubusercontent.com/46588125/195973636-d48469c8-4d63-4d9f-b818-a8000060a963.png)

https://www.berrycast.com/conversations/5bde05cd-41cc-544f-b1d3-81fec5f4427b

**Comment by mitulpanch** [comment]
URL validation required

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/583f0fd0-8d70-54be-ab58-9c86c8cd99ac
