### ISSUE TITLE
Contact customfield Page - After removing email id from email type customfield it shows old email id

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1732]
**Describe the bug**
- After removing email id from email type customfield then also it shows old email id
![image](https://user-images.githubusercontent.com/46588125/195974465-ea4ea904-0270-4daf-883f-8ec0daa74039.png)
![image](https://user-images.githubusercontent.com/46588125/195974478-e106fdc3-c724-4ff2-9e86-0ec120259370.png)

**Comment by mitulpanch** [comment]
I believe this is fixed, but not moved

**Comment by mitulpanch** [comment]
This was not issue, just module was working in background
i have explained this ti @Avinash-ecb
