### ISSUE TITLE
Contact Custom field - Issue after type conversion from number to text 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1734]
**Describe the bug**
- after conversion of type from number to text field if we added text then it is not showing text value

![image](https://user-images.githubusercontent.com/46588125/195978215-739d2477-d670-4be5-92ff-30410d3c71c2.png)
![image](https://user-images.githubusercontent.com/46588125/195978226-6ed54081-0bdb-41a5-a6e1-8d6642bc2fae.png)

https://www.berrycast.com/conversations/327e19d4-af58-5bde-933a-a895235be821

**Comment by mitulpanch** [comment]
I believe this is fixed, but not moved
