### ISSUE TITLE
Contact custom field Page - After conversion from number to boolean it shows old values

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1735]
**Describe the bug**
- after conversion from number to bool if we change on/off then also it shows old values

![image](https://user-images.githubusercontent.com/46588125/195980047-79fdbd91-a018-4a1c-ab76-f324795b2e78.png)
![image](https://user-images.githubusercontent.com/46588125/195980067-dfca474b-c801-4c7d-ac3e-6998ed4cea50.png)

https://www.berrycast.com/conversations/6f9ca347-d43a-5d34-a7ac-8c84c8db7c04

**Comment by mitulpanch** [comment]
I believe this is fixed, but not moved
