### ISSUE TITLE
Contact custom field page - After conversion from number to date if we edit it shows old data

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1739]
**Describe the bug**
- After conversion from number type to date type of customfield, if we edit some customfield it shows old values

![image](https://user-images.githubusercontent.com/46588125/196085284-ce117fb3-234b-406d-9c43-6455bdcedf0e.png)
![image](https://user-images.githubusercontent.com/46588125/196085314-50206535-0ce0-45f3-bbb2-6e9dcf37b3fe.png)

https://www.berrycast.com/conversations/0e88a1fd-8c76-56a4-9a5e-5fae7102d9e3

**Comment by mitulpanch** [comment]
I believe this is fixed, but not moved
