### ISSUE TITLE
Contact Customfield Page - Display issue while customfield type conversion from number to url

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1740]
**Describe the bug**
- When we change customfield type from number to url then if we edit customfield then it shows old filled data not showing new filled data
![image](https://user-images.githubusercontent.com/46588125/196087074-b6d5bebb-1870-455c-843f-924fcc5c50a4.png)
![image](https://user-images.githubusercontent.com/46588125/196087284-2f126142-c104-4bd0-9507-b5a115cce632.png)

https://www.berrycast.com/conversations/b699c6c1-c23a-588d-b477-0d49c4fad989

**Comment by mitulpanch** [comment]
I believe this is fixed, but not moved
