### ISSUE TITLE
Contact Customfield Page - Display issue while customfield type conversion from number to select

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1741]
**Describe the bug**
- When we change customfield type from number to select then if we edit customfield then it shows old filled data not showing new filled data

![image](https://user-images.githubusercontent.com/46588125/196091658-a606a07d-1e76-4428-b7fc-d4ad5a8a951a.png)
![image](https://user-images.githubusercontent.com/46588125/196091690-531eacf3-69e0-4f21-8019-0867e546a2f5.png)

https://www.berrycast.com/conversations/d2550b8c-c921-5ddf-9459-c56631f5fcfc

**Comment by mitulpanch** [comment]
I believe this is fixed, but not moved
