### ISSUE TITLE
  Contact Customfield Page - Display issue while customfield type conversion from number to email

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1742]
**Describe the bug**
- When we change customfield type from number to url then if we edit customfield then it shows old filled data not showing new filled data
![image](https://user-images.githubusercontent.com/46588125/196094441-39fb1ca7-77d5-4734-a8c7-2b35a06324d1.png)
![image](https://user-images.githubusercontent.com/46588125/196094465-ede70b22-a9e7-46ee-88a0-c05f01ac21cd.png)

https://www.berrycast.com/conversations/7129c290-9009-564a-beaf-bee25b46060d

**Comment by mitulpanch** [comment]
I believe this is fixed, but not moved
