### ISSUE TITLE
Contact Customfield Page - Display issue while customfield type conversion from number to phone

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1743]
**Describe the bug**
- When we change customfield type from number to phone then if we edit customfield then it shows old filled data not showing new filled data

![image](https://user-images.githubusercontent.com/46588125/196097171-21cfdb78-67bd-48c9-9c6a-da2a8e7efd1f.png)
![image](https://user-images.githubusercontent.com/46588125/196097197-a73489be-a2e8-4e29-b4d1-594769218a01.png)

https://www.berrycast.com/conversations/859e3ff3-0162-52b2-b221-baa2825af402

**Comment by mitulpanch** [comment]
I believe this is fixed, but not moved
