### ISSUE TITLE
Contact Customfield Page - Display issue while customfield type conversion from number to password

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1744]
**Describe the bug**
- When we change customfield type from number to password then if we edit customfield then it shows old filled data not showing new filled data

![image](https://user-images.githubusercontent.com/46588125/196100179-c5f07fdc-9aa6-40aa-8ccb-b5a612e8a7f4.png)
![image](https://user-images.githubusercontent.com/46588125/196100222-67d5c41a-bf73-4101-8974-59f38cab56c9.png)

https://www.berrycast.com/conversations/9afe4471-a9d7-5d6e-a315-e024c3e58212

**Comment by mitulpanch** [comment]
I believe this is fixed, but not moved
