### ISSUE TITLE
Contact Customfield Page - Display issue while customfield type conversion from boolean to text 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1745]
**Describe the bug**
- When we change customfield type from boolean to text then if we edit customfield then it shows old filled data not showing new filled data
![image](https://user-images.githubusercontent.com/46588125/196102829-b4353cb2-269e-47bc-bfee-2e433109d0a2.png)
![image](https://user-images.githubusercontent.com/46588125/196102870-99410a98-bc4b-49d5-a7cb-345907fc4dad.png)

https://www.berrycast.com/conversations/e8a3d52b-7780-5be1-a80e-ee2c0ab56fbb

**Comment by mitulpanch** [comment]
I believe this is fixed , but not moved
