### ISSUE TITLE
Contact Customfield Page - Display issue while customfield type conversion from boolean to number

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1746]
**Describe the bug**
- When we change customfield type from boolean to number then if we edit customfield then it shows old filled data not showing new filled data

![image](https://user-images.githubusercontent.com/46588125/196107823-0f6599d0-c861-427e-beac-1962ae895360.png)
![image](https://user-images.githubusercontent.com/46588125/196107875-65a4ec90-fcac-4148-8cdc-2e7a810a4523.png)

https://www.berrycast.com/conversations/c085b199-4f8e-502c-a19f-cbff62c9a40c

**Comment by mitulpanch** [comment]
I guess this is solved, but issue was not moved
