### ISSUE TITLE
Company Custom Field - Export / Import Required

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1748]
Problem -
User wants to import Excel sheet without need of going to each company and fill custom field

Requirements -
1. Exported sheet should be in format to re-import with values
2. export needed with filter expression selected, whatever filters user have selected, same objects should be exported with export functionality
3. Import sheet will create Custom field if not present, if nothing clash with existing custom fields according to custom field creation rules
4. This will be background task, will execute in jobs, job page will show task, but without details of objects, if details required then that will be additional 1 day work
5. Import will not create object, only if present then add custom field, ie. this module will not create Company / Contact / Project, if 1 found then custom field values will be added to object
6. Company creation can be done through Company page import. here it is not supported due to speed , processing issues
7. import sheet requires custom field with type , so system can process custom field and type
    a. CustomFieldName(text) => sample
    b. GSTNumber(text) => ASV123ASDF
    c. AdharCart(number) => 123456897895
    d. YearlyIncome(number) => 1,2,3,0.5,-10
    e. IsNRI(bool) => true/false
    f. Website(url) => https://www.google.com
    g. ClientType(select) => options => GoldClass, SilterClass, Bronze Class

8. Field without type => (type) => (text) / (number) will be ignored by system, no default type is provided / developed, it is very complex as common sheet is processed for different import functionalities, we want keep sheet as common as possible that why not in favor to create default type => so, GSTNumber without any type can not be processed as GSTNumber(text) => User must provide type in order system consider column as CustomField Value
9. Custom Field with invalid cast type will be ignored
10. Custom Field with different type than System has will be ignored
11. No report is Generated for this Import, not developed in any manner, if required than additional - 3 days required to develop

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
This functionality is also required for Contact custom Field
Not required for Project (confirmed over phone with @vinpahilwani )

**Comment by mitulpanch** [comment]
Company / Contact matching works same as Company Contact Import logic

**Comment by mitulpanch** [comment]
type of Custom field can not be changed => these are hard coded casting => can not be changed

**Comment by mitulpanch** [comment]
Export sheet can be reimported without column - row changes
Blank values custom field will be ignored by system,
Only filled value are considered to be processed 
So emptying Custom Field value can not be processed by importing sheet

**Comment by mitulpanch** [comment]
Sample sheet for clients will consist of 1 type of custom fields,

I will create sheet with some common types
@sureshsirvi please provide some default custom field that applies to all customers so that we can provide import sheet (like company contact import)

Company contact import sheet can be used here but that do not consist sample custom field that shows import module functionality

**Comment by sureshsirvi** [comment]
Common Custom Field

1. PAN : regex = "[A-Z]{5}[0-9]{4}[A-Z]{1}"
2. Aadhaar : regex = “^[2-9]{1}[0-9]{3}\[0-9]{4}\[0-9]{4}$”
3. TAN : regex = [A-Za-z]{4}[0-9]{5}[A-Za-z]{1}
4. CIN  : regex = ^([L|U]{1})([0-9]{5})([A-Za-z]{2})([0-9]{4})([A-Za-z]{3})([0-9]{6})$
5. GSTN : regex = ^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$

**Comment by vinpahilwani** [comment]
yes for contact and company we require this feature
