### ISSUE TITLE
Custom Field - URL type- Validation Required

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1751]
problem-
Currently ECB takes url custom field as text without validation
some user just add values which is not correct url 
So validation is required on url field like email / phone

Solution
1. URL validation required
2. starts with http:// OR https:// 
3. add other validation that standard practice for url

initiated by @mitulpanch 
verified by @vinpahilwani

**Comment by mitulpanch** [comment]
Approved over phone by @vinpahilwani

**Comment by mitulpanch** [comment]
if we validate then we can use this somewhere as url,
just type url and value without validation will trigger other problem if used somewhere

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/207312128-6fc82c75-c802-44fa-8298-212d10486ae1.png)

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/c8dfe351-e52c-5111-b393-afd8e282bf99
