### ISSUE TITLE
Company Page - when we update relationship manager it is not reflect immediately

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1752]
**Describe the bug**
- when we add/remove relationship manager  we can not see any change we have to refresh the page to see change

![image](https://user-images.githubusercontent.com/46588125/196629993-378610e7-3fbe-4bbc-a508-bab43885fb90.png)

**Comment by mitulpanch** [comment]
@dharmendraecb api response required? agar kuch chahiye to batana

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/6b620b8c-f5c2-5589-ba96-9b40cd79dba6
