### ISSUE TITLE
Job Task Page - When import/finished company customfield job task show blank view 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1755]
**Describe the bug**
- When import/finished company customfield job task shows blank page
![image](https://user-images.githubusercontent.com/46588125/196852516-29ff40e4-c771-4d5a-926e-3a5c0ec5c03e.png)
![image](https://user-images.githubusercontent.com/46588125/196852549-fa236888-66db-4914-af50-8351aa84a328.png)
![image](https://user-images.githubusercontent.com/46588125/196852576-65456a5d-36fd-467d-8d19-f663d4953211.png)

**Comment by mitulpanch** [comment]
@dharmendraecb 
job type =Company-customfield he fir bhi company-contact ka popover call ho raha he, and api bhi

company-contact-import tabhi call hona chahiye jub, job type match kare
