### ISSUE TITLE
Company Page - New Service Link import Required

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1758]
Problem -
Linking Services to Companies is pain

Clients generally have sheet for every service, 
ie. 
ITR filling software give Companies list with PAN
GST filling software gives Companies list in PAN

this sheet can be imported to ECB

Solution-
1. Give to Import Option on company Page
2. Import sheet and then Select service for this sheet is applied
3. ECB will link Service to clients 

Initiated by @vinpahilwani, @sureshsirvi
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
Api Ready

This is Link Import
This will not create Company - This is just linking to a service

1. Create Import Sheet with Company Name, PAN card, either 1 is Required
2. While Uploading File, Service need to be selected, single selection
3. Job with import will be created for background Task

**Comment by mitulpanch** [comment]
still waiting for confirmation from @vinpahilwani , @sureshsirvi

**Comment by mitulpanch** [comment]
changes  required @sureshsirvi  
Multiple Service Link required for single Sheet
Optional GST Number Import also required with PAN details
Client will provide PAN or GST due to existing Software Export gives GST Number instead of PAN

**Comment by vinpahilwani** [comment]
Approved

**Comment by mitulpanch** [comment]
Only PAN is working now
GST work is pending
