### ISSUE TITLE
Company Page - Multiple Selection beyond Paging

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1759]
Problem -
Linking Service is problem on Company Page
Currently Beyond Selection is only work if All Selected

Selection should be kept on while page is changed
this will help doing multiple action like service link

Solution
1. I will ask @dharmendraecb about this selection
2. Time to develop is little high as this interact with all things

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/0610ac3e-d02d-5f80-a152-397063121f99
