### ISSUE TITLE
Company custom field notification click related issues

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#176]
### when i click on notification export page appear with this
![2021-01-28_17-48-03](https://user-images.githubusercontent.com/46882964/106138012-930a2580-6191-11eb-8522-a759e1add060.png)

### when i clear filter export disappered
![2021-01-28_17-48-24](https://user-images.githubusercontent.com/46882964/106138058-a4ebc880-6191-11eb-88ce-30477fa9d16c.png)
### edit krne pe ander ki fields bhi working nahi hain, so agar user se chupana hai functinality so hide it

**Comment by mitulpanch** [comment]
@dharmendraecb Hide All button is IsAuto is true
