### ISSUE TITLE
Company Page - When we try to change company industry type to other using action button it shows error message

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1773]
**Describe the bug**
- when we try to change industry type to other using action button it shows error message
- in edit view it is working perfectly
![image](https://user-images.githubusercontent.com/46588125/200794863-df8ca11c-8b61-420f-9f26-8527b2cac530.png)
![image](https://user-images.githubusercontent.com/46588125/200794969-6592c5f4-708e-43dc-9641-0f529ceb6426.png)
![image](https://user-images.githubusercontent.com/46588125/200795043-d5028911-41d4-4a7a-a912-b6b7762e8dcb.png)

**Comment by dharmendraecb** [comment]
Other Allow karna he @mitulpanch

**Comment by mitulpanch** [comment]
Ready for Other
This and Legal Structure too

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/18899c5e-86d4-5e88-a922-11bc2f6d57aa
