### ISSUE TITLE
Project Customfield page - Staff has permission to edit customfield but showing error message

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1782]
**Describe the bug**
- Staff has following permission but when staff edit any customfield value server side error message shows
![image](https://user-images.githubusercontent.com/46588125/201461145-3d36f532-f6ec-4eee-b14c-b3bd818f7555.png)
![image](https://user-images.githubusercontent.com/46588125/201461225-94c99155-0c42-4d94-9879-558b2580a3bc.png)

![image](https://user-images.githubusercontent.com/46588125/201461181-1bf464f0-d93f-4be5-97ab-0fbbacf45180.png)
![image](https://user-images.githubusercontent.com/46588125/201461193-0e07c499-0c6e-45d7-b3e5-46d8e96efd0b.png)

**Comment by mitulpanch** [comment]
API Ready

**Comment by mitulpanch** [comment]
Need to send Mode = Project / ProjectCustomField to set roles correctly

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/2f8eeb72-11d8-533e-853c-602be18ba839
