### ISSUE TITLE
Transaction - Edit from Action is not working correctly

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1784]
Problem-
1. Editing Receipt transaction gives Invoice Edit section

Initiated by Deepa Pahilwani
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
https://www.berrycast.com/conversations/d27f60ca-3011-535e-8c70-bdcd591ffc80

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/b5d34d42-7463-5d1a-938e-0fb03924bce6
![image](https://user-images.githubusercontent.com/46588125/231714110-055a17b3-f4c4-4767-acef-48b072bfd4ab.png)
