### ISSUE TITLE
Document Page - Give File Name

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1785]
Requirement -
Give File name on top title

like -
washing machine samsung.pdf - Preview
in below image

![image](https://user-images.githubusercontent.com/5259926/201888218-0f621f09-45e0-4155-b08b-8ea36d4ea6ef.png)

**Comment by mitulpanch** [comment]
initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
All preview comes with File name
![image](https://user-images.githubusercontent.com/5259926/201889325-19567f35-3e61-441f-903e-238cc4d83bb6.png)


on above image also filename is visible

Do you still need this? @vinpahilwani

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/215261962-1ac26b6b-6901-48ff-8367-56f65df5851f.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/231704838-c190001c-9880-47dc-aadc-98a62c167e23.png)
