### ISSUE TITLE
Service Page - Is Online Available switch always showing off By kamlesh gehlot

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1787]
**Describe the bug**
- When client want to show some service on his website then he makes 'Is Online Available switch' on and saves service but again he opens service switch shows off
- When change online price then also it shows 0 price after saves and open service

![image](https://user-images.githubusercontent.com/46588125/202633364-1b4e7b31-67b6-4981-b7cc-a163b759f08e.png)

**Comment by mitulpanch** [comment]
I think save works correctly , showing on again is having error

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/58470300-2187-5c5e-8741-f66fe60ca364
