### ISSUE TITLE
Easycloudbooks Theme - Clients want to update service menu order & hide blog menu By kamlesh gehlot 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1788]
**Describe the bug**
- Clients want to change service menu order and also wants to hide blog menu from his website
![image](https://user-images.githubusercontent.com/46588125/202634614-55efce16-c016-482f-8cdc-ef8c2c8b0adf.png)
![image](https://user-images.githubusercontent.com/46588125/202635058-ad2dee7f-9be3-4b0f-ac6e-03fd49a06c38.png)
![image](https://user-images.githubusercontent.com/46588125/202635166-17b510e5-c7df-4859-976d-beceb0e2a296.png)

**Comment by mitulpanch** [comment]
menu sort order depends on Sort Order on website section of service

**Comment by mitulpanch** [comment]
both of thing possible from design changes on theme

**Comment by mitulpanch** [comment]
No work required on Server Side, Website engine already processing all options

**Comment by mitulpanch** [comment]
Blog Hide -
`<ecbmodule type="visible" data-type="companyrelation" data-filter="{Field:'companyrelationblogany',Operator:'=',Value:'true'}">
                                    <ecbtemplate>
---html----
</ecbtemplate>
</ecbmodule>
`
