### ISSUE TITLE
Timer related issue- at a time 2 status appear in every page, many times refresh but its still appeared

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#179]
### Timer related issue- at a time 2 status appear in every page, many times refresh but its still appeared
![2021-01-29_21-57-46](https://user-images.githubusercontent.com/46882964/106301894-46504880-627e-11eb-8a7c-0e0ec6fba719.png)

**Comment by mitulpanch** [comment]
if this happens again, connect me over anydesk
