### ISSUE TITLE
Custom File - Change icon for Need Attention

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1809]
Changing icon due to confusion / easiness for user

Change Attention icon from '-' to Green Trick
when attention required then "Explanation icon" with yellow color

![image](https://user-images.githubusercontent.com/5259926/205423727-3a34c9c4-00bd-499c-a62c-962911119c46.png)

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
On Folder view nothing is required as explained to me over phone by @vinpahilwani

**Comment by mitulpanch** [comment]
This is only for Files list not for folder view

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/230312078-e1c89dde-da92-4bdd-833a-c114b923ad74.png)
![image](https://user-images.githubusercontent.com/46588125/230312578-74cc1607-73a2-473f-8661-56bb15c219a5.png)
