### ISSUE TITLE
Contact Page- Email verify and sms verify links is not working

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#181]
### mail sample screen shot
![2021-02-01_16-02-07](https://user-images.githubusercontent.com/46882964/106447166-2b145180-64a7-11eb-8e27-d0ccf195af75.png)

### Alert from Raj Associates OTP is 1612 for verification. You can verify this by clicking https://ac-74.fammeo.in/vs/327370?c=1612 or forward this sms to 8460001275

link is not working

**Comment by mitulpanch** [comment]
s1 needed 
https://ac-74.s1.fammeo.in/verify?c=1612&t=s&id=327370

**Comment by ajayrajecb** [comment]
https://ac-74.s1.fammeo.in/verify?t=e&command=email&guid=74-eceff297-04c5-4b46-b1ad-b50af272f28b-20210219

Invalid request aa raha hai sir . mail, or sms both me.

**Comment by ajayrajecb** [comment]
SMS working fine, Email me invalid aa raha hai.

**Comment by mitulpanch** [comment]
both working now
