### ISSUE TITLE
Custom File - Change "Status" to "Mode"

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1810]
for user convenience change "Status" with values "NotApplicable", "Cloud", "Physical" to Mode

Initiated by @vinpahilwani 
Verified by @mitulpanch 

![image](https://user-images.githubusercontent.com/5259926/205424746-12231dc6-65e3-4ab2-b729-8aed7a56c962.png)

**Comment by mitulpanch** [comment]
Also change
"NotApplicable" to NA
this requires API changes

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/231940647-6a2467c9-5837-445a-a38f-ed50f6bc8b19.png)
