### ISSUE TITLE
Contact Custom file Page- When we try to delete uploaded file it shows error message

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1813]
**Describe the bug**
- When we uploaded wrong file and try to delete file then it shows error message that "you do not have enough priviledge"
![image](https://user-images.githubusercontent.com/46588125/206103279-0730becf-6035-45bb-b6e6-34baf2229f4c.png)
![image](https://user-images.githubusercontent.com/46588125/206103567-60318ac3-28a6-4243-b8db-50c16fb0d29c.png)
![image](https://user-images.githubusercontent.com/46588125/206103575-df8eae5a-213e-4fda-b2bc-f4a77724bc5b.png)

https://www.berrycast.com/conversations/10791fb8-561a-54ae-b238-49342c21540f

**Comment by mitulpanch** [comment]
please give payload

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/206107319-bd0f32c6-2d20-4cb7-a519-d2ef5ca4ee9e.png)

**Comment by mitulpanch** [comment]
solved - check again

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/aca4cb0e-6ac9-566b-82bf-702d11b3bd33
