### ISSUE TITLE
Ip Address Restrictions - New Module

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1835]
Requirements -
1. Ip Address based restrictions
2. Time based restriction required

Solution
1. this should be on Role page, basically Restriction is Role based, so no of Users can be restricted based on their role
2. Design
    - New Column on Role Page "Restrictions"
    - On Click - Opens new Drawer with Setting for Ip Addresses & Timing
    - Ip Address - Upto 10 Ip Address Selection new to add 1 by 1
    - Timing - Sunday to Saturday with StartTime and EndTime with Disable Option
Possibilities from Above Options
1. Ip Mode Only- 
        Restrict Users based on only Ip address / available on All Days, only allowing from specified Ips
2. Day mode Only-
        Restrict User based on Time only - like Disable on Sunday / Saturday, enable on Monday to Friday with 9 to 5 time, No Ip restrictions
3. Ip And Day both
       Restrict User on Ip with Time day configuration 
       like Allow on Monday to Friday with Ip address restrictions

Initiated by @sureshsirvi 
Verified by @mitulpanch 

Approved over phone by @vinpahilwani

**Comment by sureshsirvi** [comment]
Device based restriction is also required.

**Comment by mitulpanch** [comment]
from @vinpahilwani 
English Changes =>

Device Approval Requirement => Device Base Restriction
IP Allowed => IP Based Restriction
Time Allowed => Time Based Restriction

Add Table title to Time Allowed

Dont show Setting by default => if time based in then only show  Time Table , like wise for IP

Show Unlock icon outside, with Lock icon for Restriction

Restriction Page =>
Change text =>
Device OR IP based Restrictions applied. Please contact your Admin Staff

**Comment by Avinash-ecb** [comment]
For IP Based Restriction
117.228.101.32/32
32 -> For 1 IP address
31 -> For 2 IP address (last digit 0,1)
30 -> For 4 IP address (last two digit 0, 1)

https://www.ipaddressguide.com/cidr
