### ISSUE TITLE
Company custom file page - After change custom file type to physical file it does not remove uploaded files

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1838]
**Describe the bug**
- There is some file are already uploaded and custom file type is cloud after changing file type uploaded file are not removed

![image](https://user-images.githubusercontent.com/46588125/208023719-9c5ad4ce-ed62-4f2c-ad8d-957f9c0b2bb4.png)

https://www.berrycast.com/conversations/379d1182-99af-5e46-b06e-6a05aea6c746

**Comment by mitulpanch** [comment]
Not required

**Comment by Avinash-ecb** [comment]
Not required by @mitulpanch
