### ISSUE TITLE
Query Builder - Legal Structure Auto complete Required

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1851]
Problem -
1. Remove Dynamic / Static Section
2. Give Auto Complete

What Leaded to this?
Continuous changes to Legal structure database made this problem

Initiated by @vinpahilwani 
Verified By @mitulpanch

**Comment by mitulpanch** [comment]
Not giving Priority to this, whenever free @dharmendraecb can pick up

**Comment by mitulpanch** [comment]
https://www.berrycast.com/conversations/a9de6ed2-8aed-5430-856d-1a8d54aa06c2

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/b0a97b7b-c269-513a-a2d0-4a330c1d9c34
