### ISSUE TITLE
Company Page - Swap Position / Contact Positions on Menu

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1852]
Change "Position" Menu on 3rd Position
Change "Contacts" Menu on 4th Position

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/222325543-a5bc4d2e-ced3-403a-af71-5d0b6d94cbf7.png)
