### ISSUE TITLE
Auto Execution Roles

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/EasyCloudBooks#1855]
We need to provide auto roles (without need of access roles settings)
1. Relationship Manager - 
-can view to Company page 
-view companies on which he is relationship manger and he can
-add services to companies
- prepare and change fees contract
- can view company page 
- can se projects of company on which he is relationship manager

2. Service Manager
- can view services on service page
- can edit the settings of service
- can view projects for which he is service manager
- manage projects on which he is service manager

3. Service Reviewer
- can view service review page
- can review project on service review for which he is service reviewer

**Comment by mitulpanch** [comment]
on hold, not required till sales modules improvement
