### ISSUE TITLE
Timer Side window not required.

### ISSUE THREAD

**Issue by sureshsirvi** [Fammeo/EasyCloudBooks#1863]
On the project page screen. When we start timer side window is open and again we need to click on start timer button we want to remove the sidebar window.

https://www.berrycast.com/conversations/c8a6def9-10d2-5229-8399-e6ab279e21fd

**Comment by mitulpanch** [comment]
over to @vinpahilwani

**Comment by vinpahilwani** [comment]
yes it makes sense

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/d15e5aa9-9ded-5d40-a9e6-90fa987a63e3
