### ISSUE TITLE
Company page- service attach count should be capital or bold so that its highlighted

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#187]
### Company page- service attach count should be capital or bold so that its highlighted
![2021-02-02_23-22-37](https://user-images.githubusercontent.com/46882964/106642618-98f77080-65ae-11eb-8601-a8c033e533a6.png)

**Comment by dharmendraecb** [comment]
![Uploading Screenshot_2021-02-22 EasyCloudBooks - The Smart Way of Managing Practice.png…]()
