### ISSUE TITLE
Contact custom file page - Button is not showing in action view page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1871]
**Describe the bug**
- when we tick checkbox of custom file and click on action button there is not showing any button

![image](https://user-images.githubusercontent.com/46588125/210297772-11d90aef-a3c4-4fa6-90fb-115d9038ed28.png)
![image](https://user-images.githubusercontent.com/46588125/210298934-0704f5e8-0d69-40e1-90a9-3229c8932c8e.png)

![image](https://user-images.githubusercontent.com/46588125/210297810-302b44fe-612d-4429-9c24-2514cc3d358a.png)

https://www.berrycast.com/conversations/5e4f1cb0-074e-5be9-bd6f-d9bfea51c016

**Comment by mitulpanch** [comment]
Invalid Now, OR Fixed
