### ISSUE TITLE
Company/Contact/Project custom file page - We can upload same file multiple time in custom file

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1877]
**Describe the bug**
- We can upload same file multiple times in custom file, there should be rename file or not accept same file multiple time

![image](https://user-images.githubusercontent.com/46588125/210928612-0c3fc871-6713-475b-a721-d88cdb78f4fc.png)
![image](https://user-images.githubusercontent.com/46588125/210928838-3b86162b-51fb-4044-a7dd-5c2772587a73.png)
![image](https://user-images.githubusercontent.com/46588125/210928972-867069a7-6834-4c43-a18e-c491afede06c.png)

**Comment by mitulpanch** [comment]
There is no way to stop this
