### ISSUE TITLE
Custom File - Image Optimization Feature required

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1880]
Problem -
Staff uploads big image files, Client wants file but in adequate Quality
So better image stabilization, Compression can be good feature to save File size and bandwidth

This can be tricky and may require additional testing and resource

Initiated by @sureshsirvi 
verified by @mitulpanch

**Comment by mitulpanch** [comment]
Another feature may be to stop uploading large files
like dont allow image more than 2 mb, this is advance feature not required for everybody,
only available after special url

**Comment by mitulpanch** [comment]
We have applied this all user, if we find some problem, then will provide new setting to stop compressing image

**Comment by sureshsirvi** [comment]
> We have applied this all user, if we find some problem, then will provide new setting to stop compressing image

Agree with propossed sollution.

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/233304983-79935115-c95c-485b-8e2c-06d6e8d293a7.png)
![image](https://user-images.githubusercontent.com/46588125/233305172-c38902b9-d72f-4afb-b15d-71e69676b066.png)
