### ISSUE TITLE
Contact/Company/Project Page - When there is not any custom file it shows 'No Folder Found'

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1882]
**Describe the bug**
- When there is not any custom file for any project then it shows 'No folder Found'

![image](https://user-images.githubusercontent.com/46588125/211241691-ddc1be6c-e158-403c-ad82-61e86cbbc66b.png)
![image](https://user-images.githubusercontent.com/46588125/211241839-55691fea-1e6f-4646-8360-8276709d03b9.png)
![image](https://user-images.githubusercontent.com/46588125/211241906-4e0258eb-afe5-40da-bc62-6012f2d046ee.png)

**Comment by mitulpanch** [comment]
no error in this, this is correct behaviour
