### ISSUE TITLE
Project custom file page - When delete file approved status is not reset

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1889]
**Describe the bug**
- when custom file has some file and it is approved by some user then if we delete any file then its status is not reseting
![image](https://user-images.githubusercontent.com/46588125/211464870-93781764-b203-4ed4-aee7-db518c8bb432.png)

https://www.berrycast.com/conversations/cd5f2ded-2080-5bf6-bc65-e769f74c45f5

**Comment by mitulpanch** [comment]
Not Required
