### ISSUE TITLE
project custom file page - After change custom file type to physical file it does not remove uploaded files

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1890]
**Describe the bug**
- There is some file are already uploaded and custom file type is cloud after changing file type uploaded file are not removed

![image](https://user-images.githubusercontent.com/46588125/211469977-38dbf441-d982-498d-bca0-ab140db65e06.png)

https://www.berrycast.com/conversations/fcf10c9a-d86f-5df5-83b6-9193a5cf00d8

**Comment by mitulpanch** [comment]
We dont remove anything , 
meaning taken from this action is
First Client has given 5 files, then remaining Files are physical so bot cloud files and Physical files given by clients,

The default ideal action is , staff should add all files to cloud instead of setting to physical,
