### ISSUE TITLE
Project custom file page - When we attach custom file from project page it does not show tick in project custom file page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1892]
**Describe the bug**
- When we attach customfile to project then that project service is also attached with customfile but it does not show tick in custom file page in service selection page

![image](https://user-images.githubusercontent.com/46588125/211509969-61c45af5-223e-47d0-b613-5164ade8df71.png)
![image](https://user-images.githubusercontent.com/46588125/211510027-1c01bdf1-4b26-4960-941a-9d6c30bde9f0.png)
![image](https://user-images.githubusercontent.com/46588125/211510092-33918604-e5a1-484c-bc03-4c298a37fde8.png)
![image](https://user-images.githubusercontent.com/46588125/211510171-58024a0e-c002-41e4-a7af-e2af53d42dbb.png)

https://www.berrycast.com/conversations/a0225aa2-40d1-59d9-b82e-fb4ce1e7189e

**Comment by mitulpanch** [comment]
I think this is not issue anymore, waiting for someone to repeat
