### ISSUE TITLE
Project custom file page - Removing Approval status of any approval file not trigger Reminder date reset to today

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1893]
**Describe the bug**
- When there is reminder date set for some date and if staff remove approval status of custom file then reminder date is not reset to today

![image](https://user-images.githubusercontent.com/46588125/211717053-f449720f-5410-4dd5-b94b-b59f82134839.png)

https://www.berrycast.com/conversations/cc46728b-ddaf-5d94-a3d8-a66ab737f966

**Comment by mitulpanch** [comment]
This was not required, So waiting for any user to complain
