### ISSUE TITLE
User wants ACCOUNTS button in project view page

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#190]
### User wants ACCOUNTS button in project view page, see below image for reference
![2021-02-12_14-28-44](https://user-images.githubusercontent.com/46882964/107748394-f9b94280-6d3e-11eb-8894-4950d4c9f62a.png)

### jis company ka project hai, usme accounts pe click kr k related client ka account section open honaa chahiye

**Comment by mitulpanch** [comment]
Discuss with @vinpahilwani
