### ISSUE TITLE
Import project page - Improvement in Saved Queries : can we help them with auto service wise client filter saved query

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1907]
**Describe the bug**
- Improvement in Saved Queries : can we help them with auto service wise client filter saved query

![image](https://user-images.githubusercontent.com/46588125/215406565-f26ba1ab-548c-4536-8b9a-4a146f8bcc8e.png)

https://www.berrycast.com/conversations/f294ddca-3dc4-53f2-a266-c556fcffed4c

**Comment by mitulpanch** [comment]
No Required any more, New Redesign Solved everything
I have confirmed over phone with Anydesk demo to @vinpahilwani
