### ISSUE TITLE
Custom Field - Add input, output , process Mode

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1910]
Add setting to set any custom field as 
"input" , "output" OR "process"

Initiated by @vinpahilwani , @sureshsirvi 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
Later on Removed from Company , Contact Page as required by @vinpahilwani

**Comment by sureshsirvi** [comment]
Let me see it again.

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/231683684-c489279d-f9f0-4124-825e-babdd107b55a.png)

![image](https://user-images.githubusercontent.com/46588125/231683425-199565a5-65a7-41ea-bc02-450d3f52b494.png)
