### ISSUE TITLE
Mobile app- contact us website click gives error

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#193]
### click on website opens error page
![2021-02-17_14-38-51](https://user-images.githubusercontent.com/46882964/108182435-04088180-712f-11eb-9739-28ee4270a4f8.png)

![2021-02-17_14-41-42](https://user-images.githubusercontent.com/46882964/108182449-07037200-712f-11eb-90d5-e27914a1b4b0.png)

**Comment by mitulpanch** [comment]
Remove Click Event

**Comment by Harsheasy** [comment]
### Click event has been remove from the website.
