### ISSUE TITLE
Setting Page - switch Off modules for new Companies

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1931]
New Companies get confused on all modules
So New functionality required to hide all modules on new companies
Who ever requires can switch on Module as required

Modules
1. Accounting
2. Document
3. Custom Field
4. Custom File
5. Timesheet
6. Automation
7. Notification Log
8. Website
9. Domain

All module are off by default

Initiated by @vinpahilwani , @dharmendraecb 
Verified by @mitulpanch

**Comment by dharmendraecb** [comment]
Document module **Off**  = > Document Page, Document Log  Remove in menu or Company, Contact and Project Profile in Tab Remove.

**Comment by dharmendraecb** [comment]
TimeSheet Module **Off** =>  Timesheet Page Remove in Menu, Header, Project List Page  in Play Button Remove

**Comment by dharmendraecb** [comment]
Custom Field Module **Off** => 

1. Company, Contact, Project Custom Field Page remove in Menu
2. Company, Contact Project Profile in Tab, related Multi Action Remove

**Comment by dharmendraecb** [comment]
Custom File Module Off =>

1.  Company, Contact, Project Custom File Page remove in menu.
2.  Company, Contact Profile in Tab, Related  Multi Action Remove.

**Comment by dharmendraecb** [comment]
Accounting Module **Off** => 

1. Company, Contact Ledger and Contract page, Remove in Menu. 
2. Company, Contact Profile in Tab, Related Multi Action Remove.
3. Transaction Page Remove in Menu
4. Setting page in Account,  Online Payment Tab Remove.

**Comment by dharmendraecb** [comment]
Automation Module **Off** =>  ProcessFlow, Api Key Page Remove in Menu.

**Comment by dharmendraecb** [comment]
Notification Module **Off** => 

1. All Template and Notification menu Remove in Menu.
2. Contact, Company, Project, Transaction Multi Action in Send Email, SMS, Notification, Custom Email Remove.
3. Settings Page in Email/SMS Tab Remove.

**Comment by dharmendraecb** [comment]
Website Module **On/Off** Button.
Setting page > Website Tab > 
 **Off**
![image](https://user-images.githubusercontent.com/46588108/220841313-e231244e-ccee-4b73-b075-a629439924fe.png)

**On**
![image](https://user-images.githubusercontent.com/46588108/220841410-7417d461-aa26-45a1-9e7a-de520cfb4373.png)

**Comment by dharmendraecb** [comment]
Website Module Same Custom Domain Module

![image](https://user-images.githubusercontent.com/46588108/220841640-2020bada-bad5-4303-b128-06294a8333f9.png)

**Comment by mitulpanch** [comment]
10. Personal Gadgets

**Comment by mitulpanch** [comment]
11. Removing Manage Year from Menu for ALL
