### ISSUE TITLE
Company Custom field page - Showing true/false instead of On/off in need attention view

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1933]
**Describe the bug**
- When some client make bool value on/off then it shows true/false in company custom field page it shoud show On/Off

True->On, False->Off

![image](https://user-images.githubusercontent.com/46588125/220823645-1d0e32f5-6b2a-48e5-b2b4-896b31e12b81.png)

**Comment by mitulpanch** [comment]
currently its ok
If client persists then will change
