### ISSUE TITLE
Billing Page - Require Opening Balance, Payment, Amount Charged, Ending Balance 

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1935]
instead of EB and Amount Changed

that should be
Opening Balance from Previous Month
+ 
Amount Charged - Total of current months expenses
-
Payment and Discounts - Total of all PAyment and Discounts
=
Ending Balance

![image](https://user-images.githubusercontent.com/5259926/220880801-74667f0e-5dff-4475-a27d-a7770f22d2ac.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/229998352-004b8695-4a6a-48b0-a283-f4577a26098d.png)
