### ISSUE TITLE
Client Company Page - All custom File is uploaded then also it shows required field label

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1936]
**Describe the bug**
- Client uploads all customfile then also it shows required filled red label
![image](https://user-images.githubusercontent.com/46588125/221091395-f0a83ebf-e1f6-4166-b054-96e2349f51eb.png)
![image](https://user-images.githubusercontent.com/46588125/221091432-84c5e783-0cf0-459d-9f90-5f0f7fa3be85.png)
https://www.berrycast.com/conversations/2def480c-7b33-5468-a660-c049e0f32aa6

**Comment by mitulpanch** [comment]
Unpproved sara Required he,
