### ISSUE TITLE
Setting Page - Module Settings remove "Chargeable" Word

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1938]
Remove "Chargeable" words from Module settings
This gives perspective that Other modules are not chargeable

Initiated by @vinpahilwani 
Verified By @mitulpanch

**Comment by mitulpanch** [comment]
Timesheet Module is charged on ON setting, that is why i thought that a warning is good for that particular module

but still usability is very much needed , so removing Chargeable word from Module Settings

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/222342101-84d3d671-3e20-47d2-b45e-031bc6ea7b49.png)
![image](https://user-images.githubusercontent.com/46588125/222342168-e96b3be6-207c-490f-9ef5-30700890ff90.png)
