### ISSUE TITLE
Mobile- Coming soon processing until i click another page

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#197]
### Mobile- Coming soon processing until i click another page
![2021-02-17_15-34-26](https://user-images.githubusercontent.com/46882964/108189424-bb54c680-7136-11eb-8153-9395d29cf579.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/111438214-fb08d100-8729-11eb-9f42-90097c50713e.png)
