### ISSUE TITLE
Service Page - Introduce Service Billing Mode - Manual

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1980]
@vinpahilwani will provide documentation for this

Manual billing service will not be available on Company Ledger page, to select as Schedule Billing OR Per Project Billing

Initiated by @vinpahilwani 
Verified by @mitulpanch

**Comment by mitulpanch** [comment]
I think Specifying as Manual Billing may lead to more problem

It is possible that some clients can specified per project billing for Services which are non-recurring other than CAs
Loan Providers, Lawyers may get better option for that kind of services

**Comment by vinpahilwani** [comment]
![Billing   Collection - Billing](https://user-images.githubusercontent.com/41849556/224259800-dd53b763-7fa0-4996-8551-959c7ce75c3a.jpg)

**Comment by mitulpanch** [comment]
Manual Option now given on Service Page

This Services wont come into Auto Billing Option on Company Page
