### ISSUE TITLE
Login - OTP based Signup Required

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#1987]
OTP based SignUp / Login required, for Client / Staff
Currently it is only by google login

**Comment by mitulpanch** [comment]
Scenarios 
----
✅ : Provided / Present   |  ❌ : Not Provided / Not Present  | ➖ : Present / Not Present

| No | [Email Login](# "User has provided Email") | [Phone Login](# "User has provided Phone") | [UserId](# "Userid comes when person Login to ECB, this maintains Login and Staff / Client Connection") | [StaffId](# "This comes when User is Staff") | [Contact](# "This comes when Provided Email / Phone exists on Contact List") | [Contact-email](# "stated True when Possible Contact has Email")| [GId](# "Contact had never Logged in to ECB Company, So we need to Provide UserId to contact") | Action | Silent SignUp |
| :---: | :------: | :-------: | :-------: | :-------: | :---------: | :--------------: | :---: | :---: | :---: |
|1 | ✅ | ❌ | ✅ | ✅ | ✅  | ➖  | ✅   | [Staff Login - OTP](# "Simple Login with OTP on email, User is both Staff and client") | ➖ |
|2 | ❌  | ✅  | ✅ | ✅ | ✅  | ➖  | ✅   | [Staff Login - OTP](# "Simple Login with OTP on SMS / WhatsApp, User is both Staff and client") | ➖ |
| 3 | ✅ | ❌ | ✅ | ✅ | ❌ | ❌ | ❌  | [Staff Login - OTP](# "Simple Staff Login with OTP on email, No Contact details, Staff should not be auto added as Client") | ➖ |
|4 | ❌  | ✅  | ✅ | ✅ | ❌ | ❌ | ❌  | [Staff Login - OTP](# "Simple Staff Login with OTP on SMS/WhatsApp, No Contact details, Staff should not be auto added as Client") | ➖ |
| 5 | ✅ | ❌ | ✅ | ➖ | ✅  | ➖  | ❌   | [Client SignUp](# "Sign Up as Client, as Contact have same email, Client need to join as same User, so from next login this becomes 1st Scenario") | ✅  |
| 6 | ❌  | ✅  | ✅ | ➖  | ✅  | ➖ | ❌  | [Client SignUp](# "Sign Up as Client, as Contact have same phone, Client need to join as same User, so from next login this becomes 1st Scenario") | ✅  |
| 7 | ✅ | ❌ | ✅ | ➖ | ❌  | ➖  | ❌   | [Client SignUp](# "Sign Up as Client, Create New Contact from User details, so from next login this becomes 1st Scenario") | ✅  |
| 8 | ❌  | ✅  | ✅ | ➖  | ❌    | ➖ | ❌  | [Client SignUp](# "Sign Up as Client, as Contact have same phone, Client need to join as same User, so from next login this becomes 1st Scenario") | ✅  |
| 9 | ✅ | ❌ | ❌  | ❌  | ✅   | ✅   | ❌   | [Client SignUp](# "Sign Up as Client, Silent Client SignUp as All details requierd to SignUp present") | ✅    |
| 10 | ❌  | ✅  | ❌  | ❌   |  ✅    | ✅  | ❌  | [Client SignUp](# "Sign Up as Client, Silent Client SignUp as All details requierd to SignUp present") | ✅    |
| 11 | ❌  | ✅  | ❌  | ❌   |  ✅    | ❌   | ❌  | [Client SignUp Form](# "Sign Up as Client, Contact dont have email, so SignUp form Required") | ❌   |
| 12 | ✅ | ❌ | ❌  | ❌  | ❌   | ❌  | ❌   | [Client SignUp Form](# "Sign Up as Client, Ask for FN,LN, email, Otp") | ❌     |
| 13 | ❌  | ✅  | ❌  | ❌   |  ❌     | ❌   | ❌  | [Client SignUp Form](# "Sign Up as Client, Ask for FN,LN, email, Otp") | ❌     |
| 14 | ✅  | ❌   | ✅   | ❌   |  ✅ | ➖  | ✅   | [Client Login](# "Login as Client") | ❌     |
| 15 | ❌   | ✅  | ✅   | ❌   |  ✅ | ➖  | ✅   | [Client Login](# "Login as Client") | ❌     |


----
There are some scenarios where Multiple Contact / User / Staff present or connected, then we give error Message

**Comment by Avinash-ecb** [comment]
16 check return url scenario like https://rajassociates.easycloudbooks.com/login?returnurl=https%3A%2F%2Frajassociates.easycloudbooks.com%2Fuser%2Fcompany%2Flist%23 

17 delete phone number & login with phone
18 delete phone number & login with email
19 delete email address & login with phone
20 delete email address & login with email

**Comment by Avinash-ecb** [comment]
Some more test case tested

- Change email and login with new email (contact has both email and phone) 
- change phone and login with new phone (contact has both email and phone) 

- create contact with only phone and login with phone 
- create contact with only email and login with email 

- change email and login with new email (contact has only email) 
- change phone and login with new phone (contact has only phone) 

- add multiple email and login with each one (contact has both email and single phone) 
- add multiple phone and login with each one (contact has both single email and phone) 
- add multiple email and login with each one (contact has both email and multiple phone) 
- add multiple phone and login with each one (contact has both multiple email and phone) 

- add multiple email and login with each one (contact has only email)
- add multiple phone and login with each one (contact has only phone)
