### ISSUE TITLE
Querybuilder page - When copy query its apply to is changed to querybuilder

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1993]
**Describe the bug**
- When we copy query created from other than querybuilder page then its apply to is changed to querybuilder

![image](https://user-images.githubusercontent.com/46588125/224640567-64aa5284-2334-428c-8f7a-8e2af09f3914.png)

https://www.berrycast.com/conversations/0bae8075-cf8b-586d-bae6-a728bb6c2925

**Comment by dharmendraecb** [comment]
check Old Page

**Comment by dharmendraecb** [comment]
querybuilder1
