### ISSUE TITLE
Client Area Website - New client though website (Some review of client)

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#1996]
**Describe the bug**

Dashboard page
1 When client login redirect him to client area
![image](https://user-images.githubusercontent.com/46588125/225509411-c4877591-e9f7-4884-89c8-97edd3bfd621.png)

2 Show welcome, companyname message on dashboard
![image](https://user-images.githubusercontent.com/46588125/225509776-163499b0-8343-4ebc-a59b-1546796ae89b.png)

3 show button place an order when click on button it redirect to service menu page (new page)
![image](https://user-images.githubusercontent.com/46588125/225509909-46977e6e-db7b-4085-96d5-4bc8d884ec90.png)

4 show whatsapp chat bubble button on bottom right
![image](https://user-images.githubusercontent.com/46588125/225509976-9ec8618a-f9c7-4618-8cd4-07ac19008fd9.png)

5 change text Don't show wording like no found, no record use other wording
- No receipt found => You have not made any payment till yet
- No Due date found => This information will appear as your setting
- Project chart, No Records => Your project chart will appear here
6 improve design like showing total 0 companies in one box and in other box total amount due 0, zero is not use same position
![image](https://user-images.githubusercontent.com/46588125/225510480-ff183940-ec5f-48c4-b595-353f59f1ae98.png)

7 File upload redirect to error page
![image](https://user-images.githubusercontent.com/46588125/225510690-7307555a-f980-4f36-89a0-6044815cfbb2.png)

Profile page
1 How client can change profile photo or edit profile
![image](https://user-images.githubusercontent.com/46588125/225510805-b8e25106-da50-4afa-93e6-124f21c66a6c.png)

2 Custom file change text no folder found to better word
![image](https://user-images.githubusercontent.com/46588125/225510912-1543e557-c9a8-4bcb-9d6f-202bada7b69a.png)

3 Note change text null
![image](https://user-images.githubusercontent.com/46588125/225510984-9022f600-d4e8-49e3-8890-8542b6a6266b.png)

4 Position No companies found=> you can link your company here
![image](https://user-images.githubusercontent.com/46588125/225511067-c0135da1-9310-41c1-a8f4-afbe3145b567.png)

5 How client can create his company there is not process or when he creates project then we will ask him company name

Fees contract page
1 Showing error message you do not have any previledge
![image](https://user-images.githubusercontent.com/46588125/225511702-de78974c-1d19-4ae0-bc23-604fa305f41d.png)

Project page
1 Change text no project found => you don't have any pending projects 
2 place your order now button beside filter button for order project

Completed projects
1 No Projects found => you don't have any completed projects
![image](https://user-images.githubusercontent.com/46588125/225511769-a4c3639f-417f-480f-b7c8-647b25f314bc.png)

Transaction page
- Don't show transaction page instead show ledger page
![image](https://user-images.githubusercontent.com/46588125/225511845-2b59d4c9-766c-493c-9f55-660a04a961ec.png)

https://www.berrycast.com/conversations/11b9ca25-1b83-554a-afbb-dd4425a0652e

**Comment by mitulpanch** [comment]
done
