### ISSUE TITLE
Mobile- UI issue related color text

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#200]
### Mobile- UI issue related color text
![2021-02-17_16-57-00](https://user-images.githubusercontent.com/46882964/108198834-23f57080-7142-11eb-918b-b45a95a92feb.png)

**Comment by mitulpanch** [comment]
Background Color Fix car denge
then ye issue nai hoga

**Comment by ajayrajecb** [comment]
> Background Color Fix car denge
> then ye issue nai hoga

https://github.com/Fammeo/EasyCloudBooks/issues/203
Ye sb bhi sayad isi wajah se ho raha hai

**Comment by ajayrajecb** [comment]
color change karne ka option gayab ho gaya, or disable ho gaya
