### ISSUE TITLE
Mobile app - Documents- Dark mode , ui color issue

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#203]
### Android= Folder/ image remove buttons is not visible  in dark mode
![2021-02-19_14-33-59](https://user-images.githubusercontent.com/46882964/108483946-52e62080-72c1-11eb-8e01-21cb8611cf22.png)

### IOS - Folder/ image remove buttons is not appear in dark mode
![Image from iOS](https://user-images.githubusercontent.com/46882964/108484045-6db89500-72c1-11eb-921c-c8fbf2a4a5a2.png)

**Comment by ajayrajecb** [comment]
![2021-02-19_15-16-59](https://user-images.githubusercontent.com/46882964/108487991-dc97ed00-72c5-11eb-88ce-5c87f1ca322e.png)

**Comment by Harsheasy** [comment]
The dark mode is not available at this time
