### ISSUE TITLE
Mobile app- Drag and drop files in this box is not working in client folder

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#204]
### files goes to file manager not in document folder
![2021-02-19_15-33-41](https://user-images.githubusercontent.com/46882964/108489894-1e299780-72c8-11eb-8d37-21414078ae23.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/111456860-8049b100-873d-11eb-8efb-6eafbc02a7a1.png)
