### ISSUE TITLE
Timesheet - When try to filter with service some service is not showing in option

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#2048]
**Describe the bug**
- When staff wants to filter project with service then in service filter some services are not showing in option

![image](https://user-images.githubusercontent.com/46588125/231352129-7c917978-25a8-4648-88c9-3ca3bd0b3c25.png)

https://www.berrycast.com/conversations/3bb33ce9-f704-5f99-9c69-5276e9f0c81a

**Comment by dharmendraecb** [comment]
this services Deleted User Can't Filter Services

**Comment by Avinash-ecb** [comment]
This issue is invalid by @dharmendraecb
