### ISSUE TITLE
Timesheet Page - Some UI changes 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#2049]
**Describe the bug**
- No Events Found. message should be left align
![image](https://user-images.githubusercontent.com/46588125/231354329-b9e34474-25c1-4186-ad8f-3e91bf068a56.png)

- There shoul be space between TimeSheet-> Time Sheet
![image](https://user-images.githubusercontent.com/46588125/231354687-d26794b0-d689-49f7-b672-924ee4fae6b1.png)
![image](https://user-images.githubusercontent.com/46588125/231354746-23fd257a-3b42-4fb5-9a57-9d694b984526.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/231700290-93c12608-beb3-4ee4-9938-4ce91c891dbf.png)
