### ISSUE TITLE
Mobile app= Document share button is not working

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#205]
### Mobile app= Document share button is not working
![2021-02-19_16-10-47](https://user-images.githubusercontent.com/46882964/108494155-38b23f80-72cd-11eb-8747-b5566221ef51.png)

**Comment by mitulpanch** [comment]
share file only works for image/video

**Comment by mitulpanch** [comment]
ios does not support this feature
