### ISSUE TITLE
Staff Page - When create staff it shows phone number already exist

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#2058]
**Describe the bug**
- When there is phone number with diffrent country code then also it shows phone number already exist

![image](https://user-images.githubusercontent.com/46588125/233615216-36b93bff-17bb-4841-b53d-95bfe632ec7b.png)
![image](https://user-images.githubusercontent.com/46588125/233615446-69d9397b-56cd-4233-a579-4cc906f79cbd.png)
https://www.berrycast.com/conversations/8a6450c7-002f-572a-bec5-2a8b3ca14516

**Comment by mitulpanch** [comment]
Yes, Currently we donot check for Country Code, as Some of clients data is not correct
later on we will correct this

Currently only phone number matching is ON
