### ISSUE TITLE
Client Profile Page - note is not display in client profile page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#2064]
**Describe the bug**
- In client profile if note is not required to show then remove note heading
- If it is required to show then note description is not showing 

**User section**
![image](https://user-images.githubusercontent.com/46588125/235048651-6bce0438-ac3e-4ae4-a088-2fcc27ccd8b2.png)

**Client section**
![image](https://user-images.githubusercontent.com/46588125/235048698-3762e65b-bb6f-4dea-bb20-a38472fcf1df.png)

**Comment by dharmendraecb** [comment]
Remove Note Section

**Comment by Avinash-ecb** [comment]
![image](https://github.com/Fammeo/EasyCloudBooks/assets/46588125/3c20fce4-8eff-4518-bc49-73a3882ed5f6)
![image](https://github.com/Fammeo/EasyCloudBooks/assets/46588125/566d19da-8302-43c4-9337-687f38da0ec8)
