### ISSUE TITLE
Broadcast page - Mode column is not sorting 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#2067]
**Describe the bug**
- When staff wants to sort with mode column then the mode column is not sorting
![image](https://user-images.githubusercontent.com/46588125/235298025-19d05bb8-9e76-4cef-9420-3164779e25c2.png)
![image](https://user-images.githubusercontent.com/46588125/235298042-529f74d0-1910-4add-991d-63491373ecc5.png)

![image](https://user-images.githubusercontent.com/46588125/235298099-b36d19d3-7901-417f-abd5-54afe302c0c3.png)
![image](https://user-images.githubusercontent.com/46588125/235298106-366e682d-9588-4e09-b590-219b509c310a.png)

**Comment by dharmendraecb** [comment]
Remove Sorting

**Comment by Avinash-ecb** [comment]
![image](https://github.com/Fammeo/EasyCloudBooks/assets/46588125/2d23554d-fc6a-464b-b4d0-58c7f7c836ed)
