### ISSUE TITLE
Broadcast page - when try to broadcast email it shows error in notification

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#2076]
**Describe the bug**
- When try to broadcast email it shows error message not triggered email
![image](https://user-images.githubusercontent.com/46588125/235425501-53d5842e-e763-42f8-aaf6-5ee2060fa494.png)
![image](https://user-images.githubusercontent.com/46588125/235425551-ad6c0c9f-33dd-45b4-9f64-6b3803e66c32.png)
![image](https://user-images.githubusercontent.com/46588125/235425584-681baf91-d071-4642-bc95-d70cab8f0df8.png)

**Comment by dharmendraecb** [comment]
https://www.berrycast.com/conversations/77386475-8cea-5b1c-9d81-c27e6b3a198d

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/b9325bec-32fd-5876-a335-92df43a1a215
