### ISSUE TITLE
Company page - When we apply some query to company page query does not work by Kailash Joshi

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#2093]
**Describe the bug**
- When we applied query on company page it does not work as defined in query
![image](https://user-images.githubusercontent.com/46588125/236393783-0d9f2598-c47f-4b9d-b413-11d0793ee7b4.png)
![image](https://user-images.githubusercontent.com/46588125/236393850-5b43b6d3-1b79-423c-8102-a958938590ee.png)
![image](https://user-images.githubusercontent.com/46588125/236393916-7a0f3080-f275-43e4-8e7e-15ef84d34fe2.png)

https://www.berrycast.com/conversations/b08cf522-814b-5ce9-b9d5-daae5a7dc298

**Comment by mitulpanch** [comment]
ye query galat he, tag ek ek tag ko check karta he

**Comment by mitulpanch** [comment]
![image](https://user-images.githubusercontent.com/5259926/236407912-28b31723-5e41-4db7-95c2-3e43fcfa54bf.png)
ye ayega
