### ISSUE TITLE
Notification Related- Rename link text please. Download link 

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#210]
### When export completes 2 notification comes, both looks same, please rename one with Download Link
![2021-02-23_14-35-24](https://user-images.githubusercontent.com/46882964/108822289-e2067780-75e4-11eb-90e9-6e4466937edc.png)

**Comment by ajayrajecb** [comment]
Sir ko chahiye tha notification pe click akren to file download ho jaye direct, but ye bhi chalega.

**Comment by mitulpanch** [comment]
Direct Download is not possible
