### ISSUE TITLE
Previous Periods Projects Working notes appearing in current project.

### ISSUE THREAD

**Issue by sureshsirvi** [Fammeo/EasyCloudBooks#2144]
Issue raised by Kishor Choudhary from Mumbai.

When we create Tax Audit project for current period i.e. FY 2022-23-FULL, old projects FY 2021-22 working notes appearing again in newly created projects..

We need separate Working notes for each projects.

**Comment by mitulpanch** [comment]
This was required by @vinpahilwani 
Idea was -
Need to copy all Previous Note which was used to complete project
like - How the ITR was done last time? OR Instruction to Complete ITR project for Company
Some notes that was accumulated last year to complete project
------
Although Some changes possible if user provides input, that how to Treat a Note, OR Select Client Note, Permanent Note, Non Repetitive Note

**Comment by mitulpanch** [comment]
Current Logic-

If Last Project is Present copy Working Paper from Last Project
if not than copy from Template


New Logic -
Always copy from Template on Service Page

Approved by @vinpahilwani @sureshsirvi over phone
----
I am removing code for copy logic, and Confirmed over phone that, we are not doing this again, not repeating same logic again to code

---
Todos are still coming from Last project

**Comment by mitulpanch** [comment]
Now everywhere ,
Working Note / Project Documents / Note 
Always copy from  Service Template - Last project is never checked


if Last Project is present -
Copy Todo
else from Service Template

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/d6c8f5b2-46ac-58a1-b82c-aabcd124ec8d
![image](https://github.com/Fammeo/EasyCloudBooks/assets/46588125/0fbee3b9-6b54-4296-a587-38c0900329aa)
