### ISSUE TITLE
accounts print

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#215]
when opening ledger from.account, unsettled transaction comes up with opening balance .

instead of that unsettled view need to show all unsettled transactions without date filter

opening balance. and closing balance not required

client wants to see what they need to pay

currently its designed as tally view demand by ashok bhurani

by @vinpahilwani, Afshin chauhan

**Comment by ajayrajecb** [comment]
![2021-02-24_16-37-46](https://user-images.githubusercontent.com/46882964/108992674-92e14500-76bf-11eb-8a17-da885130fa13.png)

Need Closing Balance
