### ISSUE TITLE
Module - Company Auto Billing

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#225]
![WhatsApp Image 2021-02-23 at 12 48 04 PM(1)](https://user-images.githubusercontent.com/5259926/109470255-2e463180-7a95-11eb-9038-f539b3ac73c8.jpeg)

Above Image was base Example of what was required

**Comment by mitulpanch** [comment]
Requirement Discussed over phone -
1. Printable version for single Company - as shown above
2. Printable Version for Company List - 
https://docs.google.com/spreadsheets/d/1v2DYYP_36nFu1UYPlKPT7oy8TzzClEncsJ8o1xjARgo/edit?usp=sharing

**Comment by mitulpanch** [comment]
Printable Version for Company List

1. QueryBuilder with with simple company/contact parameters
2. This columns not required for QueryBuilder ie. Companies with Jan month Billing > 5000 **not required**
3. No External link required on this page only link required is to - go to single company printable version, its view button at end of row to see Printable version for single Company
4. Contact wise total not required
5. Paging with 20 Companies
6. Export of this columns required through Export Module to CSV
7. this columns are not used anywhere except this page - no foreign links

**Comment by mitulpanch** [comment]
Company Page - Create AutoBilling

1. Company Page - Add Recurring Billing as Column
2. Service that is selected for Service Scheduler will appear in this section to select
3. Direct Add Service to this is not Required, as it changes service scheduler pattern
ie. some may need to create project through Service Scheduler but Auto Billing only require for some services
4. Only Output Tax can be selected as tax applicable
5. Max 12 Schedulers can be Added
6. Some Service may charge 0 but required for auto billing, ie. may be a  free service with currently selected Services. ex. Income Ta is free with GST Services , so Income Tax Service Projects will be Billed with All Scheduler Patterns. 
7. Multiple changes to companies taken to consideration but not created as we need to process each company details/ Input taking is much complex, for simplicity this is ignored/not supported
8. Schedulers can not be repeated/ only Yearly Schedulers can be  selected
9. fore Above Photo
   a. Accounting, GST , TDS Returns will be billed on all 4 Schdulers
   b. But ITR, GST Annual Return will be Billed on Last Scheduler only -
  c. If any Service's Selected Annual Price is 0 then it can be billed on all Scheduler
  d. Bill any PRoject which is not billed, do not check Year / Period Combination

**Comment by mitulpanch** [comment]
![Screenshot 2021-03-01 143454](https://user-images.githubusercontent.com/5259926/109475150-59338400-7a9b-11eb-8f7a-49def657baeb.jpg)


This is sample for Printable Version for Company List

**Comment by dharmendraecb** [comment]
Printable Version for Company List - user/RecurringBilling
Single view mode  - user/RecurringBilling?mode=detail&crid=$$

**Comment by mitulpanch** [comment]
Update - 4th march

Now we dont need multiple tax on company structure, 

@vinpahilwani  required simple structure, so we are not supporting multiple tax possibilities anymore, only one tax thing we are goint to support

**Comment by mitulpanch** [comment]
Update - 4th march By @sureshsirvi 
Single Note Required,

**Comment by mitulpanch** [comment]
Update 5th March-

Notes Required for each scheduler

**Comment by mitulpanch** [comment]
Update 5th march - @vinpahilwani 

Link to Printable version and from printable version to company autobill change popup link required

------
tax, Total, Note changes discussed over phone

**Comment by sureshsirvi** [comment]
![image](https://user-images.githubusercontent.com/46813198/110567555-ba341980-8177-11eb-9a85-296bb336b5d6.png)

We need this notes in print ... and Editor is required .... having option for Bold, Italic, Font Size, Table... etc...

**Comment by sureshsirvi** [comment]
Currently ... we need to setup this automation separetly for each company .... is there in way to borrow same setup for one company to another company ...

**Comment by sureshsirvi** [comment]
![image](https://user-images.githubusercontent.com/46813198/110569646-c7063c80-817a-11eb-8f1d-dedfa6cca436.png)

Sub-Type(Optional) ... selection is needed.

**Comment by mitulpanch** [comment]
#294 Update on 15 March
