### ISSUE TITLE
Company- service price and recurring price is not match

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#226]
### Service price

![2021-03-01_14-39-16](https://user-images.githubusercontent.com/46882964/109476670-2d190280-7a9d-11eb-9c59-7427fe4fba02.png)

### Recurring Price

![2021-03-01_14-39-54](https://user-images.githubusercontent.com/46882964/109476773-4a4dd100-7a9d-11eb-838b-149eabe6f880.png)

**Comment by ajayrajecb** [comment]
### Price is not change when I change price in attach service tab

**Comment by mitulpanch** [comment]
both prices are different

**Comment by mitulpanch** [comment]
annual price is not equal to price
