### ISSUE TITLE
Company - add service price remove

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#230]
### Company - add service price remove
![2021-03-01_18-01-52](https://user-images.githubusercontent.com/46882964/109497773-922e2180-7ab8-11eb-9425-b83ed41d09b2.png)

**Comment by mitulpanch** [comment]
what?
It is required

**Comment by mitulpanch** [comment]
Please do not remove anything without my approval,
Display none is different
