### ISSUE TITLE
Design changes in company auto billing (By sir)

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/EasyCloudBooks#238]
### Second "Select items for Auto Billing" 
![2021-03-03_14-42-23](https://user-images.githubusercontent.com/77724114/109783178-b6f8d500-7c2f-11eb-98b4-959d52f5ed38.png)

**Comment by ajayrajecb** [comment]
### Company Name
### Select Items for Auto Billing

**Comment by ajayrajecb** [comment]
### Title first line me company name
### 2nd line me Select Items for Auto Billing

**Comment by Harsheasy** [comment]
![2021-03-05_11-40-04](https://user-images.githubusercontent.com/77724114/110074938-03ffb700-7da8-11eb-8fd4-0f7c77b17208.png)
