### ISSUE TITLE
Company Auto Billing Requirement

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#239]
### When new user type anything in scheduler text box, please show Create New Scheduler Button

![2021-03-03_15-02-05](https://user-images.githubusercontent.com/46882964/109785113-ce38c200-7c31-11eb-9476-73fd8ae34867.png)

**Comment by Harsheasy** [comment]
when a new client wants to auto-billing and if he did not have any scheduler then create a 
new scheduler does not appear, so this is needed
