### ISSUE TITLE
Company page- Industry type values is not in same line with others

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#241]
### Company page- Industry type values is not in same line with others

![2021-03-03_16-18-13](https://user-images.githubusercontent.com/46882964/109795396-e235f100-7c3c-11eb-8199-3c30fb9a336c.png)

**Comment by mitulpanch** [comment]
this happens when name length is greater than 15 characters,
as we try to split to 2nd line

**Comment by mitulpanch** [comment]
to solve this we need bigger column size, to save on size, we try to split big names into 2 lines
