### ISSUE TITLE
Change By Default Group Name "Other" to "Compliance" and show suggestions in EASYCLOUDBOOKS

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/EasyCloudBooks#245]
![2021-03-04_17-06-33](https://user-images.githubusercontent.com/77724114/110069081-0b6d9300-7d9d-11eb-8ab1-c016cc904c9e.png)
 
### Show below group name in suggestion while adding the service in website

![2021-03-04_17-10-29](https://user-images.githubusercontent.com/77724114/110069077-0a3c6600-7d9d-11eb-853c-cfce898595ce.png)

**Comment by mitulpanch** [comment]
Other is default used in database at multiple places,
this will take time , so holding it for next bug fix round
