### ISSUE TITLE
Favicon change when sharing - fammeo user section page

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#248]
![Screenshot 2021-03-05 114804](https://user-images.githubusercontent.com/5259926/110075335-a9b32600-7da8-11eb-93b3-9a7ebeadfcf6.jpg)

remove flower favicon - use fammeo "f" favicon

**Comment by ajayrajecb** [comment]
![favicon16](https://user-images.githubusercontent.com/46882964/110076211-2266b200-7daa-11eb-855c-384781dfb105.png)
![favicon32](https://user-images.githubusercontent.com/46882964/110076215-2397df00-7daa-11eb-8a7e-efaf2dd0fdca.png)

**Comment by ajayrajecb** [comment]
https://github.com/Fammeo/EasyCloudBooks/issues/196
