### ISSUE TITLE
Print page need edit option sothat user can change price in final time- By sir

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#254]
### Print page need edit option so that user can change price in final time- By sir
![2021-03-08_11-42-42](https://user-images.githubusercontent.com/46882964/110306020-5ac4f500-8023-11eb-9ee2-f7b6096eac4d.png)

**Comment by dharmendraecb** [comment]
![Screenshot_2021-03-08 EasyCloudBooks - The Smart Way of Managing Practice](https://user-images.githubusercontent.com/46588108/110306338-ba230500-8023-11eb-9a81-02be33c7169d.png)

Button add
