### ISSUE TITLE
print date shows only in final print

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/EasyCloudBooks#255]
### As per sir, remove print date from this page and it should show only in the final print

![2021-03-08_15-30-05](https://user-images.githubusercontent.com/77724114/110306000-54367d80-8023-11eb-8cac-31c8019deb5c.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/110307770-4d106f00-8025-11eb-9732-7f5f86f751e1.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/110307812-5994c780-8025-11eb-9cce-c1b7d87caf5e.png)
