### ISSUE TITLE
Remove the border box from recurringBilling page and auto-billing section

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/EasyCloudBooks#256]
![2021-03-08_15-34-44](https://user-images.githubusercontent.com/77724114/110306536-f5bdcf00-8023-11eb-8650-254eca5b2450.png)
![2021-03-08_15-34-16](https://user-images.githubusercontent.com/77724114/110306544-f6eefc00-8023-11eb-875a-a91c7689cba5.png)

**Comment by ajayrajecb** [comment]
![2021-03-09_15-32-09](https://user-images.githubusercontent.com/46882964/110454351-23bb1600-80ed-11eb-812c-c5f6073b091a.png)
