### ISSUE TITLE
Voucher note box save without taking any value(blank), and need save successfully message after click on save

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#260]
### Voucher note box save without taking any value(blank), 
![2021-03-08_15-58-52](https://user-images.githubusercontent.com/46882964/110309521-73cfa500-8027-11eb-852a-65577484d304.png)

### and please show **"Save Successfully"** message after click on save

**Comment by dharmendraecb** [comment]
Note data save temporary after click main popop save button save data.

**Comment by ajayrajecb** [comment]
In Blank note note title color is black, and if we put same text in it its title color is red.(For User)
