### ISSUE TITLE
Need Combine import excel for International level(Requirement arise when Nepal client wants to setup)

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#268]
### Need Combine import excel for International level(Requirement arise when Nepal client wants to setup)

Currently not supported Phone Number with other country code and Address shown Vadodara by default

#264

**Comment by mitulpanch** [comment]
Only +91 check karne ka requirement tha,

Total more than 500 country codes he, each phone pe ye check karne me bahut time jayega , So ignore kiya tha

**Comment by mitulpanch** [comment]
International client ye use nai karenge esa bat tha, ktu ki hum PAN number lete he

**Comment by mitulpanch** [comment]
Agar client ko operatin country Nepal Select kare to +977 auto matic aa jayega

**Comment by mitulpanch** [comment]
But its not tested

**Comment by ajayrajecb** [comment]
> Agar client ko operatin country Nepal Select kare to +977 auto matic aa jayega

excel me bhi kam karega kya , kr k dekhu test

**Comment by ajayrajecb** [comment]
> Agar client ko operatin country Nepal Select kare to +977 auto matic aa jayega

country aap change kr k dogey , apne aap client change kare, aisa option nhi hai na abhi

**Comment by mitulpanch** [comment]
only admin can change country
