### ISSUE TITLE
Scheduler Page - Timing Not Required

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#270]
Timing Option not required - Remove Time Selection 

Every Scheduler will run at morning 6 AM

Warning

Back to Back Schedulers will fail in this case

ie. First Create Project then , Send SMS
on Different Automations with Timing Gap

There is no issue from Engine this is done because User cant understand
and Big timing Names on Scheduler Name

So with Scheduler Name change Remove Timing is also Required

**Comment by ajayrajecb** [comment]
### In some scenarios timing is required, kisi client ko particular time me mail sms bhejna hai to time chahiye hoga scheduler me,

**Comment by mitulpanch** [comment]
![Screenshot_20210309-193358.png](https://user-images.githubusercontent.com/5259926/110482216-6f31ec00-810e-11eb-89f4-b02075352010.png)

**Comment by mitulpanch** [comment]
@![Screenshot_20210309-194135.png](https://user-images.githubusercontent.com/5259926/110483205-80c7c380-810f-11eb-9543-a35fa2ae3ecc.png)

**Comment by mitulpanch** [comment]
Now only 6AM - to 12PM Available

All 30 Minute sections are removed.
