### ISSUE TITLE
Scheduled Items Tab not required (By sir)

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#276]
### Scheduled Items Tab not required (By sir)
![2021-03-10_16-27-44](https://user-images.githubusercontent.com/46882964/110619635-086c0b80-81be-11eb-8b48-27dfd1ef0e9d.png)

**Comment by mitulpanch** [comment]
this is to check , how scheduler will work, some times user calculation and system calculation is different

**Comment by mitulpanch** [comment]
list ka koi use nahi he, agree

**Comment by ajayrajecb** [comment]
### Dependency jo dikh rahin hain, unko aur acche se dikhane k liye kuch karna hai
![2021-03-10_16-46-38](https://user-images.githubusercontent.com/46882964/110621651-774a6400-81c0-11eb-9b8f-22dd1cf5df28.png)
