### ISSUE TITLE
company page 

### ISSUE THREAD

**Issue by dharmendraecb** [Fammeo/EasyCloudBooks#278]
Company Page me Service select modal me first Save button click after service price section me Is Recurring On he 
wahi Services Dikhe gi by: @vinpahilwani

**Comment by dharmendraecb** [comment]
![Screenshot_2021-03-12 EasyCloudBooks - The Smart Way of Managing Practice](https://user-images.githubusercontent.com/46588108/110913053-aab0fe00-833a-11eb-85a7-05024be0aae5.png)

**Comment by dharmendraecb** [comment]
![Uploading Screenshot_2021-03-12 EasyCloudBooks - The Smart Way of Managing Practice(1).png…]()

**Comment by ajayrajecb** [comment]
? ye upar upload nhi hua image, kya tha ye ?

**Comment by dharmendraecb** [comment]
![Screenshot_2021-03-15 EasyCloudBooks - The Smart Way of Managing Practice](https://user-images.githubusercontent.com/46588108/111105898-06b59580-857a-11eb-9bc6-27a4750ded58.png)
