### ISSUE TITLE
New user Login error after payment

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#282]
### New user Login error after payment https://auto-1a96a816e5ed480da1c47e0ef.fammeo.in/unautherized
![2021-03-12_13-12-41](https://user-images.githubusercontent.com/46882964/110924744-69274f80-8348-11eb-92f5-57769aa5e699.png)

**Comment by mitulpanch** [comment]
Actual Error

Auto-Assigned Id's DNS is not working Correctly,

To stop this we need to find out why user got auto id

CompanyCreating on Fammeo needs Testing

Need to Find Dcenation where we can repeat this

**Comment by ajayrajecb** [comment]
4-5 new companies create by harsh
