### ISSUE TITLE
Accounts- Statement manager appear 2 times 

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#283]
### Accounts- Statement manager appear 2 times 
![2021-03-12_16-16-57](https://user-images.githubusercontent.com/46882964/110929928-85c68600-834e-11eb-8633-21dfb3f5be8d.png)

**Comment by ajayrajecb** [comment]
![2021-03-12_16-30-16](https://user-images.githubusercontent.com/46882964/110931571-6d576b00-8350-11eb-910f-c9dd9ec69397.png)

**Comment by mitulpanch** [comment]
This is Old bug, if this thing repeat then we can do something

Corrupted data can not be repaired

**Comment by mitulpanch** [comment]
not required any more
