### ISSUE TITLE
Account- account members not required in account page, anyone who comes in account page do all things according account Roles (By Sir)

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#288]
### accounts me jo members add functionality hai, uski jarurat nhi hai, Jise bhi accounts page pe jo role hain uske according wo access kr paye

![2021-03-13_17-02-40](https://user-images.githubusercontent.com/46882964/111028961-0e612700-8420-11eb-92bb-8d656b51f49a.png)

**Comment by mitulpanch** [comment]
Abhi ye change karne me bahut time jayega

**Comment by sureshsirvi** [comment]
Following Further chages suggested ...
<img width="1280" alt="Account View" src="https://user-images.githubusercontent.com/46813198/111447405-6a36f300-8733-11eb-8924-2882b7b36547.png">
<img width="1280" alt="Ledger Print Changes" src="https://user-images.githubusercontent.com/46813198/111447432-70c56a80-8733-11eb-9d17-9225122b76d8.png">

**Comment by ajayrajecb** [comment]
sirvi sir comments requirement baki hai

**Comment by mitulpanch** [comment]
@ajayrajecb New issue bana do agar kuch reh jaye to
