### ISSUE TITLE
Project Create Page Error : You do not have enough privilege

### ISSUE THREAD

**Issue by sureshsirvi** [Fammeo/EasyCloudBooks#290]
When we are going to create new project ... if already same project earlier created then it shows duplicate project ... along with link of previous project exist... 

When we click on the link ... "Go to Project" .... then above error appears.
<img width="1280" alt="Screenshot 2021-03-13 at 3 32 31 PM" src="https://user-images.githubusercontent.com/46813198/111103575-ce5f8880-8574-11eb-9da6-2cc5da650bde.png">
<img width="1280" alt="Screenshot 2021-03-13 at 3 32 25 PM" src="https://user-images.githubusercontent.com/46813198/111103585-d4ee0000-8574-11eb-8c46-e53dbb4310e3.png">

**Comment by mitulpanch** [comment]
i think, project is in finished state that why error,

we can redirect appropriate page after checking status of project
