### ISSUE TITLE
Account Page - All/ Setteled / Unsetteled Transaction

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#300]
Account Page - All / Setteled / Unsetteled Transaction tab required

Warning 
I dont suggest to create tab to show same data with  filter, that will increase bill and load on servers
Users can see same thing with filters

**Comment by ajayrajecb** [comment]
sath me lana hi nahi hai jo tab pe click kiya utna hi lana hai-by vinod Sir

**Comment by mitulpanch** [comment]
> 
> 
> sath me lana hi nahi hai jo tab pe click kiya utna hi lana hai-by vinod Sir

Ram usage is directly link with no of  things present on page, multiple tabs with same thing will increase load on Ram/PC/ slow loading

**Comment by mitulpanch** [comment]
Also Settlement button, Print all things need to redone , single tab trigger / now all tabs triggers event to settlement button
