### ISSUE TITLE
Contact page- Multiple selection button design issue

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#305]
### Contact page- Multiple selection button design issue

![2021-03-19_14-48-01](https://user-images.githubusercontent.com/46882964/111758375-6f767800-88c2-11eb-9dd6-eca4e7a8adcb.png)

### its not look proper- please make some changes

**Comment by ajayrajecb** [comment]
### Change button ka naam 'Tag Change' kar sakte hain fir change multiple tag title likhne ki jarurat nhi padegi

**Comment by ajayrajecb** [comment]
### Send Notification button should be just below of Contact Name title (with left alignment)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/111863450-abbcdd80-8981-11eb-9285-32d9d39113c3.png)
