### ISSUE TITLE
In account Page ... We are add notes... but it shows only upto 2 notes .... we need all notes for our review...

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#308]
In account Page ... We are add notes... but it shows only upto 2 notes .... we need all notes for our review...
<img width="1280" alt="Reminder Notes" src="https://user-images.githubusercontent.com/46813198/111736616-33341f00-88a4-11eb-8c98-cf628d6eb68e.png">
<img width="1280" alt="RN-1" src="https://user-images.githubusercontent.com/46813198/111736622-362f0f80-88a4-11eb-9915-701f365c838c.png">

_Originally posted by @sureshsirvi in https://github.com/Fammeo/EasyCloudBooks/issues/301#issuecomment-802573904_

**Comment by vinpahilwani** [comment]
Yes mitul Notes are required.

**Comment by mitulpanch** [comment]
Approved by @vinpahilwani
