### ISSUE TITLE
Account Page - Company Relation Detail not Required

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#313]
![Screenshot 2021-03-20 173131](https://user-images.githubusercontent.com/5259926/111868813-2269d300-89a2-11eb-8a28-1fc9988f72f8.jpg)

Company Relation Detail not required as shown in above image

only add "V" Company Image before " Account Name"

incase of Contact Account

Add just Circle Image of Contact

**Comment by dharmendraecb** [comment]
![Screenshot_2021-03-22 EasyCloudBooks - The Smart Way of Managing Practice](https://user-images.githubusercontent.com/46588108/111966893-73ea9d00-8b1d-11eb-8bc5-bd690e276e0e.png)
