### ISSUE TITLE
Account Page - Settle button not Required on All Tab

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#314]
Account Page - Settle button not Required on All Tab

![Screenshot 2021-03-20 173755](https://user-images.githubusercontent.com/5259926/111868976-06b2fc80-89a3-11eb-9ac8-54cd94138e13.jpg)

Some of the Transactions are already settled on All Transaction tab, so its confusing for user that some are settled and some can not be Settled, 
so Removing "Settle" Button from All Tab, "Settle" Button will be Available only in Open Transaction to remove confusion

This is also needed to stop confusion with Email/ Send Notification functionality

**Comment by ajayrajecb** [comment]
![2021-03-22_11-16-31](https://user-images.githubusercontent.com/46882964/111945731-36c3e200-8b00-11eb-8314-1ca1075e8746.png)
