### ISSUE TITLE
Accounts Print- Remove some text (By Sir)

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#317]
### Please remove text shown in RED box, 
![2021-03-22_16-58-26](https://user-images.githubusercontent.com/46882964/111983597-53780e00-8b30-11eb-9a35-20b586e7788e.png)

### Sales account ki jagah **PROFESSIONAL FEES** chahiye

Talk with Vinod sir, if needed

**Comment by dharmendraecb** [comment]
![Uploading Screenshot_2021-03-23 Fammeo - The Smart Way of Managing Practice.png…]()

**Comment by dharmendraecb** [comment]
![Screenshot_2021-03-23 Fammeo - The Smart Way of Managing Practice](https://user-images.githubusercontent.com/46588108/112134763-0d37b300-8bf3-11eb-9688-2f9154c234d2.png)
