### ISSUE TITLE
Company- Remove company text from title in service attach and auto billing section

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#322]
### Company- Remove company text from title in service attach and auto billing section
![2021-03-22_17-37-40](https://user-images.githubusercontent.com/46882964/111987916-cc2d9900-8b35-11eb-8f90-861334ff492c.png)

![2021-03-22_17-38-36](https://user-images.githubusercontent.com/46882964/111987935-d059b680-8b35-11eb-954f-c172f77d825e.png)

**Comment by ajayrajecb** [comment]
![2021-03-23_16-40-06](https://user-images.githubusercontent.com/46882964/112137619-7c62d680-8bf6-11eb-8eb0-4d0c4b0b4193.png)
### Not solve in Auto Billing

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/112141974-0b262200-8bfc-11eb-9a6c-42c6570107cc.png)

**Comment by dharmendraecb** [comment]
Ctrl +F5

**Comment by ajayrajecb** [comment]
Not solve in Auto Billing

**Comment by Harsheasy** [comment]
![Snag_1454103](https://user-images.githubusercontent.com/77724114/112452621-d5f50d80-8d7c-11eb-9c2e-6c08e85a7c3c.png)

**Comment by Harsheasy** [comment]
### After clicking on next this tab appear in this tab "company" should be remove
