### ISSUE TITLE
Image issue in Sir Company ac-1, in company page and Recurring bill page

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#326]
### Photos hain clients k andar.

![2021-03-23_15-31-34](https://user-images.githubusercontent.com/46882964/112132635-d5c80700-8bf0-11eb-92b0-b420103ead46.png)

![2021-03-23_15-20-25](https://user-images.githubusercontent.com/46882964/112132640-d791ca80-8bf0-11eb-8de1-0eb58f6a7788.png)

**Comment by mitulpanch** [comment]
Ye Solve nai ho sakta
Imagepath Pattern change hua he 
so can not fix this

**Re Uploading Image to Company / Contact will solve this**

**Comment by ajayrajecb** [comment]
reset pe name ka 1st last alphabet ka option de sakte hain ?

**Comment by mitulpanch** [comment]
Reset kaha he?

**Comment by ajayrajecb** [comment]
![2021-04-12_14-46-54](https://user-images.githubusercontent.com/46882964/114371390-1090df80-9b9e-11eb-97eb-1daa68cf97f6.png)

fammeo pe reset hota hai proper alphabet

**Comment by mitulpanch** [comment]
Ye Reset Fammeo ka reset nai he, 
ye usse pehle se bana hua he

--------------
1. Open Edit Mode
2. Change Image
3. Click Reset will set image to original which was before
4. Reset is not for Creating Default Image - no connection with fammeo reset image
