### ISSUE TITLE
Recurring Bill Page - Total should be BOLD 

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#327]
### Total wali row ko BOLD karna hai
![2021-03-23_16-14-41](https://user-images.githubusercontent.com/46882964/112136356-d498d900-8bf4-11eb-973b-887f664bb04e.png)

**Comment by Harsheasy** [comment]
![Snag_14a2332](https://user-images.githubusercontent.com/77724114/112453319-94b12d80-8d7d-11eb-8677-6d5f608f16f8.png)
### Total should be bold
