### ISSUE TITLE
Remove Global Email Template

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#328]
Global Templates are in Control of ECB Admin Team

If someone is using Global Templates on Automation, and Admin decide to drop support for Template then the Automation get into Error, there is no way to warn User about this issue so , dropping support for Global Templates

**Comment by mitulpanch** [comment]
same for Notification Template

**Comment by ajayrajecb** [comment]
Main pehle sb kuch market me copy kr du, fir hatana aap, abhi nhi

**Comment by mitulpanch** [comment]
72 me rahenge
dont worry

**Comment by ajayrajecb** [comment]
> 72 me rahenge
> dont worry

ok
