### ISSUE TITLE
Broad cast page- after click email template, querybuilder section UI issue

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#329]
### email notification page se click kiya to broadcast page open hua, wahan query builder section k andar UI issue hsi, Please refer below image
![2021-03-23_16-47-25](https://user-images.githubusercontent.com/46882964/112138957-2858f180-8bf8-11eb-99ae-506e64446e46.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/112146291-6870a200-8c01-11eb-960b-bdae0a8ed614.png)
