### ISSUE TITLE
Income Account module is missing on billing section  of service page

### ISSUE THREAD

**Issue by harshitaexpcon** [Fammeo/EasyCloudBooks#33]
design of easycloud service page

![image](https://user-images.githubusercontent.com/66782635/90503689-7a6efb80-e16d-11ea-8c8d-073e4f414b19.png)

design of fammeo easycloud service page

![image](https://user-images.githubusercontent.com/66782635/90503717-865abd80-e16d-11ea-8df2-088795c84180.png)

Income Account module is missing on billing section  of service page

**Comment by mitulpanch** [comment]
@vinpahilwani Sir ne demand kiya tha
