### ISSUE TITLE
Email template- after click on broadcast changes ( By Sir)

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#331]
### click karne k baad jo bhi template choose kr k aagey ja raha hai, wahi naam se broadcast save ho jaye, naam or description na puche.

![2021-03-23_17-18-26](https://user-images.githubusercontent.com/46882964/112144432-3bbb8b00-8bff-11eb-8bb0-34535120aea9.png)

**Comment by mitulpanch** [comment]
API Requires Name, So send Template Name as Broadcast Name in backgroud

**Comment by ajayrajecb** [comment]
Notification or sms me bhi same chahiye, broadcast me naam puch raha hai, template page se click kr k jane pe

**Comment by mitulpanch** [comment]
By default hi nai chahiye, esa bat hua he mera 

Template se aye ya nai aye, 
Broadcast page pe hi nai chahiye


so, Design hi remove kar deni he
