### ISSUE TITLE
Email Template me image , gif insert ka option chahiye (By Sir)

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#335]
### Email Template me image , gif insert ka option chahiye.
abhi nhi hai ck editor me, 
possible ho to App template me bhi chahiye

**Comment by mitulpanch** [comment]
Email Template Approved,

Image Option already he on Notification Template

**Comment by mitulpanch** [comment]
![Screenshot 2021-03-24 074341](https://user-images.githubusercontent.com/5259926/112244067-ace95580-8c74-11eb-917a-5493d58b2806.jpg)
Aur inline Image possible nai he
