### ISSUE TITLE
Email Template- How to see or fetch personal key in email template page

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#336]
### Email Template- How to see or fetch personal key in email template page

**Comment by mitulpanch** [comment]
Last Design me tha, but isme hatva diya

**Comment by mitulpanch** [comment]
I suugest dubara nai leke aao, if nobody using it - stick to it

**Comment by mitulpanch** [comment]
Need Approval from @vinpahilwani

**Comment by vinpahilwani** [comment]
Yes mitul is right. We just need to remove all those texts which suggest there is something called personal keys

**Comment by mitulpanch** [comment]
![Screenshot 2021-03-24 092505](https://user-images.githubusercontent.com/5259926/112252297-d9a46980-8c82-11eb-9d27-2a64d4993458.jpg)

[@keyword] are your Personal Keys that you specified on Setting Page. hatana he

**Comment by dharmendraecb** [comment]
![1](https://user-images.githubusercontent.com/46588108/112299843-3a04cc80-8cbe-11eb-93a1-bcdf020bc073.png)

**Comment by dharmendraecb** [comment]
Your personal key search in Text Box.
