### ISSUE TITLE
Email Templates - Subject box single line wala chahiye, bht badaa nhi

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#339]
### Email Templates - Subject box single line wala chahiye, bht badaa nhi
![2021-03-23_23-32-32](https://user-images.githubusercontent.com/46882964/112195910-7ee22200-8c30-11eb-9d7e-e79fead78047.png)

**Comment by mitulpanch** [comment]
Plugin is not supporting this, so cantfix

**Comment by ajayrajecb** [comment]
> Plugin is not supporting this, so cantfix

Without plugin subject text box use kar sakte hain kya ?

**Comment by mitulpanch** [comment]
Drag Drop and Design changes hote he woh support nai hota
