### ISSUE TITLE
Seed message- Text format issue, preview proper chahiye

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#343]
### Email ka preview proper chahiye, release note section me text dalne pe format bigad raha hai.
![2021-03-24_15-06-09](https://user-images.githubusercontent.com/46882964/112287903-d6c16d00-8cb2-11eb-9ad9-c47ba3f6b930.png)

**Comment by mitulpanch** [comment]
Email template ka preview hata do

**Comment by ajayrajecb** [comment]
### As same, not solve
