### ISSUE TITLE
Company custom field- In first page many fields missing and horizontal scroll is also missing

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#348]
### Company custom field- In first page many fields missing and horizontal scroll is also missing in sir company
![2021-03-24_16-44-01](https://user-images.githubusercontent.com/46882964/112306580-f6ae5c00-8cc5-11eb-9f6a-3bc09a2a727e.png)

**Comment by ajayrajecb** [comment]
No issue.

**Comment by mitulpanch** [comment]
It is designed like that
