### ISSUE TITLE
Market- your package notification click

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#355]
### Market- Your package notification click throws to separate notification page which are not exist in new design

![2021-03-25_17-01-00](https://user-images.githubusercontent.com/46882964/112466797-422b3d80-8d8c-11eb-9ead-0d8cf001b652.png)

![2021-03-25_17-02-37](https://user-images.githubusercontent.com/46882964/112466819-45bec480-8d8c-11eb-9dc9-642f4a251ee4.png)

**Comment by mitulpanch** [comment]
ye to bahut jagah pe change karne ka ayega

**Comment by ajayrajecb** [comment]
> ye to bahut jagah pe change karne ka ayega

email template wala sahi page, new page pe hi la raha hai,

**Comment by mitulpanch** [comment]
page ka url alltemplate ayega , matlab hat jagah badlana padega
