### ISSUE TITLE
Auto bill -  Professional fee account created with client name

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#357]
### client name not required after Professional Fee 
![2021-03-25_17-16-58](https://user-images.githubusercontent.com/46882964/112468728-a4853d80-8d8e-11eb-8bb4-751075f8fb3a.png)

**Comment by mitulpanch** [comment]
Ye design Error He, Automation working correctly

**Comment by ajayrajecb** [comment]
> Ye design Error He, Automation working correctly

scheduler se hi banaya tha ye auto bill

**Comment by mitulpanch** [comment]
yes design me company ka name dikh raha he,
baki account name , voucher details barobar he, design me name alag se append ho raha be
