### ISSUE TITLE
All Custom field report page requirement

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#359]
### after click Save , popup box close ho jana chahiye, abhi nhi ho raha.

![2021-03-26_14-26-11](https://user-images.githubusercontent.com/46882964/112608425-4e70d280-8e40-11eb-9d51-af2fb20fe74a.png)

**Comment by Harsheasy** [comment]
### Save and next karne par save nai ho raha means when we click on save&next and close the tab without pressing save button it should save but in this case it does not happened
