### ISSUE TITLE
Recurring Billing - User in page 30th after view then he cancel and page comes in 1st page, thats problem

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#361]
### Solution is View page open in next new TAB
![2021-03-26_15-21-52](https://user-images.githubusercontent.com/46882964/112616846-3a31d300-8e4a-11eb-9f27-171a21901d39.png)

**Comment by ajayrajecb** [comment]
hello

**Comment by Harsheasy** [comment]
hello
