### ISSUE TITLE
Account - Voucher Billing

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#366]
Auto Voucher should be charged in Company Billing

**Comment by mitulpanch** [comment]
Previously it was counted as Auto Project, Now correctly Reflecting into Billing

**Comment by ajayrajecb** [comment]
![2021-03-31_11-58-18](https://user-images.githubusercontent.com/46882964/113100063-84cf9880-9218-11eb-9632-31437312d8b1.png)
### like this
