### ISSUE TITLE
Email Template- Remove Description box while create new email template

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#370]
### Email Template- Remove Description box while create new email template
![2021-03-31_15-17-09](https://user-images.githubusercontent.com/46882964/113125576-5eb7f180-9234-11eb-9eff-813669514e6e.png)

**Comment by ajayrajecb** [comment]
### Template Body wala box bade size ka chahiye

**Comment by dharmendraecb** [comment]
email Template, SMS Template, Notification Template
