### ISSUE TITLE
When user reset something in the Website General tab then it should ask for confirmation

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/EasyCloudBooks#376]
### When the user reset it the confirmation box did not appear, how to know if it reset or not.
![Snag_7728c2](https://user-images.githubusercontent.com/77724114/113250101-79927080-92dd-11eb-9a09-c50b7c8857ef.png)

**Comment by mitulpanch** [comment]
User is clicking Reset,

User can Reload Page if not sure,
This settings only save after "Save" Button click at bottom of page
