### ISSUE TITLE
Hindi Sms not shown in template page and show sample is not working

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#388]
### Hindi Sms not shown in template page and show sample is not working
![2021-04-02_22-45-25](https://user-images.githubusercontent.com/46882964/113438253-d426ec00-9405-11eb-9653-42c707f1614a.png)

**Comment by mitulpanch** [comment]
this is particular Template Problem, Other template is working fine

**Comment by mitulpanch** [comment]
Mene Original Text dal diya he from old databases, agar edit / create karte waqt error aye to solve kar sakte he

**Comment by Harsheasy** [comment]
![Uploading Screenshot (1).png…]()

**Comment by Harsheasy** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/77724114/113661653-2137e600-96c4-11eb-9fc4-79ba9c365934.png)
