### ISSUE TITLE
Company Mobile - Add Right Arrow to Company Name

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#392]
Company Mobile - Add Right Arrow to Company Name
Company Image Required

![Capture](https://user-images.githubusercontent.com/5259926/113561107-b33ae280-9621-11eb-8d5e-0a389736a645.PNG)

**Comment by Harsheasy** [comment]
![IMG_8946](https://user-images.githubusercontent.com/77724114/113659307-5db51300-96bf-11eb-94d0-7b37d60f74e5.jpg)
