### ISSUE TITLE
Mobile - Project Page - Redesign

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#397]
@vinpahilwani need Top bar Redesign as Client  Note / Project Header is confusing

![Screenshot 2021-04-05 183940](https://user-images.githubusercontent.com/5259926/113577082-54379680-963e-11eb-9ca0-1d1ea12c36c9.jpg)

it was Approved design

**Comment by mitulpanch** [comment]
Change Note Message - "No Notes Found"

Write Note instead of Client Note, this is Client Area

**Comment by ajayrajecb** [comment]
### Notes aata hai fir disappeared ho jata hai

**Comment by ajayrajecb** [comment]
![2021-05-10_11-49-44](https://user-images.githubusercontent.com/46882964/117614407-e70ba980-b185-11eb-80e8-4db2999e6a04.png)
