### ISSUE TITLE
Mobile - Change Menu Text

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#398]
change "Company" to "My Companies"

![Screenshot 2021-04-05 184504](https://user-images.githubusercontent.com/5259926/113577594-2272ff80-963f-11eb-8524-673c0d21886c.jpg)

**Comment by dharmendraecb** [comment]
change
1. "project" to "My Projects"
 2. "Finish project" to "my finished projects"
 3.  "document" to "my documents"
