### ISSUE TITLE
Account Page - Edit Button - New Outline style

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#403]
![Screenshot 2021-04-06 154018](https://user-images.githubusercontent.com/5259926/113695578-a2a46e00-96ee-11eb-8c56-102016cab799.jpg)

**Comment by ajayrajecb** [comment]
### Ye buttons bhi reh gaye hain 
![2021-04-06_16-05-09](https://user-images.githubusercontent.com/46882964/113698642-48a5a780-96f2-11eb-9f5f-779d2e316670.png)

### Voucher tab
![2021-04-06_16-06-11](https://user-images.githubusercontent.com/46882964/113698670-51967900-96f2-11eb-9146-ce4f34706d35.png)

**Comment by ajayrajecb** [comment]
### Ye buttons bhi reh gaye hain thik karne k
![2021-04-06_16-05-09](https://user-images.githubusercontent.com/46882964/113698880-8c98ac80-96f2-11eb-9e95-33bf6a622746.png)

### On Voucher Tab
![2021-04-06_16-06-11](https://user-images.githubusercontent.com/46882964/113698924-96221480-96f2-11eb-9c2c-b6dea2ba37ad.png)
