### ISSUE TITLE
ECB - New Billing Structure

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#407]
Api billing is complicated
simple billing is required

**Comment by mitulpanch** [comment]
1. 150 Rs Per Staff / Month 
2. First Month take only Remainder of days ie. if Staff joins on 25th then take only 5 OR 6 days charge
3. Billing as Per Staff unique UserId, No slots are considered
4. Total No of User Active in Month is considered for Billing, Remove 1 user and add another will lead to 2 staff charge
5. Removing Staff will not Refund

**Comment by mitulpanch** [comment]
6. ClientApp - 10 Rs Per Client/Month
7. Staff App - Free
8. Fixed charge - regardless of when they are joining
9. No Refund in case of ClientApp Off, no charge from Next Month
10. No charge if already charged in billing cycle for same Client

**Comment by ajayrajecb** [comment]
### 10 me se 2 staff remove kiya , billing me no change - Perfect
