### ISSUE TITLE
Contact Page - Contact EmailId / Phone Number must not repeat

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#408]
Contact Page - Contact Email Id / Phone Number must not repeat

**Comment by mitulpanch** [comment]
this makes editing current Contact with same email lot more difficult
1. user cannot save contact untill user correct data, inthis case remove duplicate email/phone

**Comment by vinpahilwani** [comment]
We do not need any change here. we need to just check at the time of invite for mobile app. plz call me so that i can explain

**Comment by vinpahilwani** [comment]
NO NEED OF DEVELOPMENT GO WITH EXISTING SOLUTION ONLY PROVIDE EMAIL INVITE AS WELL.

**Comment by vinpahilwani** [comment]
UNLESS WE HAVE GOOD USE CASE WE DO NOT NEED ANY DEVELOPMENT

**Comment by mitulpanch** [comment]
still No Patch for Existing Data
