### ISSUE TITLE
Client Login- Mobile App

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/EasyCloudBooks#409]
- Client ko invite karna hai
- us client k jo bhi email address ho us se woh login kar sakta hai 
- agar ek email multiple client me use hua hai toh invite karne pe error message dikhao email is linked with another contact kindly provide unique email
- client invite ka ek unique url ho accountant company ka. client us url ko kholega and apna email id dalega toh woh connect ho jayega us accountant company k sath agar usko invite bheja hai toh

**Comment by mitulpanch** [comment]
@Harsheasy I Required Video of current Process here

**Comment by vinpahilwani** [comment]
GO WITH EXISTING SOLUTION JUST PROVIDE EMAIL INVITE AS WELLBESIDES SMS
