### ISSUE TITLE
Testing Request

### ISSUE THREAD

**Issue by dharmendraecb** [Fammeo/EasyCloudBooks#410]
"Company page, Account page in buttons style common".

**Comment by ajayrajecb** [comment]
![2021-04-13_12-28-07](https://user-images.githubusercontent.com/46882964/114510020-ce29da00-9c53-11eb-8e74-967480430ac0.png)
### ye search btn on account page

**Comment by ajayrajecb** [comment]
![2021-04-13_12-30-41](https://user-images.githubusercontent.com/46882964/114510869-d0406880-9c54-11eb-8fdd-0c4df00843fa.png)
![2021-04-13_12-34-30](https://user-images.githubusercontent.com/46882964/114510876-d20a2c00-9c54-11eb-8d0b-39760f03df35.png)

**Comment by ajayrajecb** [comment]
![Uploading 2021-04-13_12-36-34.png…]()

**Comment by ajayrajecb** [comment]
![2021-04-13_12-36-34](https://user-images.githubusercontent.com/46882964/114513461-d6841400-9c57-11eb-867c-c68a326d634e.png)

**Comment by mitulpanch** [comment]
Query Builder me koi change nai hoga
