### ISSUE TITLE
Project Template - Error shown while view page 

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#412]
### Service delete ho chuki hai but, project template delete nhi hua so error aa rahi hai sayad
![2021-04-07_17-22-48](https://user-images.githubusercontent.com/46882964/113864334-680f0400-97c8-11eb-9ba0-b0b964c0ab1a.png)

**Comment by mitulpanch** [comment]
Service was removed,

Fixed- When ever service is removed template will be removed
Previous Template Error cannot be solved,
