### ISSUE TITLE
When i attach company it assign default automatically 

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/EasyCloudBooks#433]
If the user want to remove the default company then what 
and if I add company in contact then it choose automatically default 

![2021-04-08_14-32-05](https://user-images.githubusercontent.com/77724114/113999248-7d8f3700-9877-11eb-9ed4-ef690817e670.png)

**Comment by dharmendraecb** [comment]
ek company me default contact koiii ek ho sak ta he 
ek contact multiple companies me default ho sak ta he

**Comment by ajayrajecb** [comment]
> ek company me default contact koiii ek ho sak ta he
> ek contact multiple companies me default ho sak ta he

### but how to remove default, ek bar default ho jaye to hatana hai , kaise hatega?

**Comment by mitulpanch** [comment]
pehle bhi ye kar chuke he,

dusra contact banao and usko default karo for company
