### ISSUE TITLE
Scheduler - remove name, description, possible item tab

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#434]
### Possible item same page pe niche kahin dikha sakte hain,

**Comment by Harsheasy** [comment]
### Remove name from schduler
![Snag_1c4fe6e](https://user-images.githubusercontent.com/77724114/114864774-03c6f280-9e0f-11eb-8c07-8a4da31a8554.png)

**Comment by ajayrajecb** [comment]
> ### Remove name from schduler
> ![Snag_1c4fe6e](https://user-images.githubusercontent.com/77724114/114864774-03c6f280-9e0f-11eb-8c07-8a4da31a8554.png)

name static aana chahiye, user edit na kr paye text box
