### ISSUE TITLE
Scheduler Filters checkbox wale chahiye

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#435]
### Scheduler Filters checkbox wale chahiye
![2021-04-08_14-41-02](https://user-images.githubusercontent.com/46882964/114001227-5d607780-9879-11eb-807b-a2a4ff69a1bf.png)

**Comment by mitulpanch** [comment]
filterExpression.ReturnTypes

filter Api Ready to Implement

**Comment by dharmendraecb** [comment]
sir se bat ho gaii he sir ko nahi kar na aa change
