### ISSUE TITLE
SAVE button Solid aana chahiye every where, Baki sb Border button 

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#442]
### SAVE ka button sab jagah solid chahiye. baki sab border wala jaisa abhi kr rahe ho sab jagah
![save](https://user-images.githubusercontent.com/46882964/114011510-eb8d2b80-9882-11eb-9d09-a4cdd4d63bb4.png)

![2021-04-08_15-57-08](https://user-images.githubusercontent.com/46882964/114011711-2d1dd680-9883-11eb-8fa7-5872a98de2a9.png)

**Comment by dharmendraecb** [comment]
bahut sari jaga pe kiya he save button border wala jo vinod sir ne bola tha. abhi change nahi kar sakte.

**Comment by ajayrajecb** [comment]
> bahut sari jaga pe kiya he save button border wala jo vinod sir ne bola tha. abhi change nahi kar sakte.

Ye bhi sir ne hi kaha hai karne ko
