### ISSUE TITLE
Other Setting- Account Print me Tab chahiye

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#449]
### Other Setting- Account Print me Tab chahiye, If any issue please comment
![2021-04-08_16-57-20](https://user-images.githubusercontent.com/46882964/114019860-8b9b8280-988c-11eb-82f4-1c2bcc18082a.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/114514939-74c4a980-9c59-11eb-8fe9-d9b0afe116c8.png)

**Comment by ajayrajecb** [comment]
Sir wants Tag

**Comment by ajayrajecb** [comment]
> ### Sir wants Tab format

comment if not possible or put can't fix label

**Comment by mitulpanch** [comment]
abhi dusre kam chalu he
user section pe wapas ayenge tab karenge
