### ISSUE TITLE
Can not see price pr hour and cost pr hour in staff page 

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/EasyCloudBooks#452]
### I have the role of price/cost hour but I can not see them into the staff 
![2021-04-08_17-27-35](https://user-images.githubusercontent.com/77724114/114022944-eda9b700-988f-11eb-8bd1-20cc1c6b64df.png)

**Comment by ajayrajecb** [comment]
![2021-04-12_16-15-21](https://user-images.githubusercontent.com/46882964/114382763-61a6d080-9baa-11eb-8819-6727a053bf63.png)
