### ISSUE TITLE
Mobile App - Contact Profile

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#457]
Features - 

1. Camera to Upload Picture
2. Show Emails not editable
3. Show Phone not editable

**Comment by ajayrajecb** [comment]
### user area pe click pe coming soon process hota rehta hai
### Contacts pe click karne pe list aati hai but kisi bhi contact pe click pe error page aata hai, back home karne pe client section me le jata hai

**Comment by ajayrajecb** [comment]
### No camera option to click picture

**Comment by mitulpanch** [comment]
this was for client area
User arre abhi chalu kiya he

**Comment by ajayrajecb** [comment]
> ### No camera option to click picture

ye option kahan hai

**Comment by ajayrajecb** [comment]
> > ### No camera option to click picture
> 
> ye option kahan hai

its available on mobile, not labtop
