### ISSUE TITLE
Service- Recurring pattern should show on mouse over 

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#458]
### Abhi pattern dekhne k liye edit kr k andar jana padta hai. mouse over pe dikh jaye to accha hai.

![2021-04-09_14-59-06](https://user-images.githubusercontent.com/46882964/114162495-c5c95a80-9946-11eb-9c20-5cf54b6b1991.png)

**Comment by mitulpanch** [comment]
Hum Count leke ate he pattern nai, banate waqt hi discuss kiya tha
