### ISSUE TITLE
While create a new project same member showing two times

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/EasyCloudBooks#46]
![image](https://user-images.githubusercontent.com/58812881/91433764-66b84900-e881-11ea-9acb-7ce5e3f2a4d1.png)

**Comment by ajayrajecb** [comment]
![2020-09-28_16-48-24](https://user-images.githubusercontent.com/46882964/94426015-8efdd500-01aa-11eb-9ad5-84c28e0d5850.png)
