### ISSUE TITLE
Other Settings - Unbilled Project Minimum Date is not working

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#462]
### Other Settings - Unbilled Project Minimum Date is not working
![2021-04-10_15-07-40](https://user-images.githubusercontent.com/46882964/114265599-53707d00-9a0f-11eb-817b-ca203a74b7c8.png)

**Comment by mitulpanch** [comment]
bahut jagah pe change karna he, so kaha nai aa raha wo issue chahiye

**Comment by mitulpanch** [comment]
Automatic Project Billing me mene kar diya he
iska testing kar sakte he

**Comment by ajayrajecb** [comment]
![2021-04-12_15-32-06](https://user-images.githubusercontent.com/46882964/114377474-5355b600-9ba4-11eb-8b2b-752ca9985b59.png)

**Comment by ajayrajecb** [comment]
![2021-04-12_15-33-15](https://user-images.githubusercontent.com/46882964/114377641-826c2780-9ba4-11eb-9c4f-821f7f00dfbf.png)
