### ISSUE TITLE
Voucher - link projects requirement

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#468]
### change title bcoz tax is not shown there now
![2021-04-12_14-54-37](https://user-images.githubusercontent.com/46882964/114372574-57cba000-9b9f-11eb-958c-1afbbe70c4a8.png)

**Comment by mitulpanch** [comment]
Remove Imcome Account as well

**Comment by dharmendraecb** [comment]
projects multiple select (Cantfix)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/114704632-74eda380-9d44-11eb-94cc-54804e86aa22.png)

**Comment by ajayrajecb** [comment]
![2021-04-15_17-03-36](https://user-images.githubusercontent.com/46882964/114863125-fa3c8b00-9e0c-11eb-91d4-b0971442d9fe.png)

**Comment by ajayrajecb** [comment]
jo nhi ho saktaa ,usme cant fix wala tag laga do,
