### ISSUE TITLE
Setting- Hide Country , user cant change It

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#469]
### Setting - Hide Country , user cant change It so hide it
![2021-04-13_14-44-21](https://user-images.githubusercontent.com/46882964/114533972-1e149b00-9c6c-11eb-8dc2-d832c02e711b.png)

**Comment by mitulpanch** [comment]
its full functionality, just disabled to stop users playing with it

and user can see settings,


![Screenshot 2021-04-13 152848](https://user-images.githubusercontent.com/5259926/114534915-1f929300-9c6d-11eb-8fe9-28d2418dec9a.jpg)
