### ISSUE TITLE
SMS not receiving on mobile ... however it shows as sent on report.

### ISSUE THREAD

**Issue by sureshsirvi** [Fammeo/EasyCloudBooks#481]
We have sent sms by way of notification from project page on selected projects ... it appears in sms report that SMS sent but .. actually sms not receiving on mobile.
<img width="1280" alt="Screenshot 2021-04-13 at 6 38 48 PM" src="https://user-images.githubusercontent.com/46813198/114557933-cc7a0980-9c87-11eb-853a-04c2717ee9b6.png">

**Comment by mitulpanch** [comment]
Please wait for some time, New Government laws are under implementation
you may receive Template Mismatch Error

------------------------

Above image shows SMS is sent from ECB, but still no delivery Report Received
SMS delivery to actual Phone takes time in some cases

**Comment by mitulpanch** [comment]
@ajayrajecb Check and Close this
