### ISSUE TITLE
Old staff appeared in service  team

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#494]
### Nirav, Dipti, shweta, hitesha
![2021-04-14_17-01-58](https://user-images.githubusercontent.com/46882964/114705244-25f43e00-9d45-11eb-85fb-30f810b9405b.png)

**Comment by mitulpanch** [comment]
Please retry removing a staff from 74 and test on any service in AC-74

**Comment by mitulpanch** [comment]
this might be fixed last time, but  data we cannot change once corrupted
