### ISSUE TITLE
Due Dates not appeared in Projects in sir company ac-1

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#495]
### Duedates hain services me but Projects me nhi dikh rahin
![2021-04-14_17-18-20](https://user-images.githubusercontent.com/46882964/114706118-35c05200-9d46-11eb-9323-f26682b5b8e0.png)
![2021-04-14_17-17-23](https://user-images.githubusercontent.com/46882964/114706122-36f17f00-9d46-11eb-9dea-16e376fb4163.png)

**Comment by mitulpanch** [comment]
need to find scenario
