### ISSUE TITLE
Custom  field design changes in company , contact

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#498]
### Custom field me (-) dalna jaroori hai user ko yeh takleef nahi honi chahiye. woh backhand me manage karna hai baki jaise simple text hota hai wasa dikhna chahiye
![Screenshot 2021-04-15 at 9 10 49 AM](https://user-images.githubusercontent.com/46882964/114824115-0b23d700-9de2-11eb-9e96-e71ba2593d2e.png)

**Comment by mitulpanch** [comment]
Too much at stake to enable this

**Comment by vinpahilwani** [comment]
I mean user is typing display text and we can manage rest of things. this field will still be there not visible to user

**Comment by mitulpanch** [comment]
Later on jub search ayega, user wahi search karega jo use dikhega,

Uniqueness maintain karne ke liye kiya gaya he
