### ISSUE TITLE
Accounts - on view, all wale tab pe vouchers edit or delete nhi aata randomly

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#510]
### Accounts - on view, all wale tab pe vouchers edit or delete nhi aata randomly
![2021-04-15_23-06-35](https://user-images.githubusercontent.com/46882964/114915776-a5ffce00-9e41-11eb-9cde-69fa60381c1f.png)

**Comment by ajayrajecb** [comment]
https://rajassociates.fammeo.in/user/Accounts
### Abhi bhi nhi aa raha
 ![2021-04-27_14-23-31](https://user-images.githubusercontent.com/46882964/116214370-44eec900-a764-11eb-807f-c03de7842d31.png)

**Comment by mitulpanch** [comment]
All me button nai chaiye, only Open Transaction me rakhne he
