### ISSUE TITLE
Contact- Multiple select and send all 900 contacts mail 

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#522]
### Birthdate missing ki query lagayi, result 900 aaya, sabko ek sath contact page se mail bhejna ho to kya kare?
at a time 100 select hota hai.
![2021-04-19_15-01-54](https://user-images.githubusercontent.com/46882964/115215095-c8833700-a120-11eb-8435-56f8282db133.png)

**Comment by mitulpanch** [comment]
use broadcast
