### ISSUE TITLE
Update in easycloudbooks help section

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/EasyCloudBooks#535]
1. Need to upload videos 
2. if something come new then it should show in suggestion.
3. can share with the client from that page means if user want see contact information then we can share that.
4. we can add blog section in help so if we update something it appear on that. 
5. It should show pipeline means what we doing and what coming next.
6. user can search in help section

**Comment by mitulpanch** [comment]
1. Need to upload videos - Youtube Upload and link it here
2. if something come new then it should show in suggestion. - Writing Blog for any changes on community.fammeo.in
3. can share with the client from that page means if user want see contact information then we can share that. - community.fammeo.in does that by sending email
4. we can add blog section in help so if we update something it appear on that. - Write anything regarding Update / Change Log on Community
5. It should show pipeline means what we doing and what coming next. - Write Blog on Community
6. user can search in help section - Google Search is best Option, still we have Google Search bar can be added
