### ISSUE TITLE
issue in help section while open first time

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/EasyCloudBooks#536]
### when we one first time help section then this page appear for sometime. we need to remove this page

![Snag_43770e](https://user-images.githubusercontent.com/77724114/115336369-b951c700-a1bc-11eb-8329-660694339759.png)

**Comment by mitulpanch** [comment]
it was 404 because of domain change from easycloudbooks to fammeo

Earlier it was working correctly

Redirect from 404 to actual page is still there, if landing url is invalid
We try to send him to correct url if possuible
