### ISSUE TITLE
Mobile App Blog shows html Tag H1, Br etc

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#539]
### Mobile App Blog shows html Tag H1, Br etc
![Screenshot_20210420-144757](https://user-images.githubusercontent.com/46882964/115371984-144ce380-a1e8-11eb-8b25-0aa4ceb6fab4.png)

**Comment by mitulpanch** [comment]
blog ka name details sub bhejo
