### ISSUE TITLE
when i search company that time show all company 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/EasyCloudBooks#54]
![image](https://user-images.githubusercontent.com/58812881/92093472-04b39280-edf1-11ea-9cda-d7dfefa0e3a7.png)

https://ac-40.fammeo.in/user/FinishedProjects

company, contact, project & finish project

**Comment by dharmendraecb** [comment]
contact page me company serach nahi he bhai...

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/93298970-e2b70880-f811-11ea-9b2f-f505e471dd5e.png)
https://ac-40.fammeo.in/user/Projects

![image](https://user-images.githubusercontent.com/58812881/93299084-198d1e80-f812-11ea-93d2-b84c20726ea6.png)
https://ac-40.fammeo.in/user/Company
