### ISSUE TITLE
Mobile App- Menu hide karne k liye left swipe hona chahiye, no option for menu close

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#540]
### Mobile App- Menu hide karne k liye left swipe hona chahiye, no option for menu close
![WhatsApp Image 2021-04-20 at 2 56 16 PM](https://user-images.githubusercontent.com/46882964/115373633-b0c3b580-a1e9-11eb-85ca-9b9202306210.jpeg)

**Comment by mitulpanch** [comment]
click on gray part do that
