### ISSUE TITLE
Mobile App- Blog view pe edit option aa rahe hain, jo click pe unauthrised aa raha hai

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#541]
### I am admin alos sayad isliye blog pe edit option aa jate hain mobile app me

https://rajassociates.fammeo.in/Edit?page=blog/what-is-lorem-ipsum

![2021-04-20_15-07-55](https://user-images.githubusercontent.com/46882964/115374201-39daec80-a1ea-11eb-972a-4eda3f480c79.png)

**Comment by mitulpanch** [comment]
@dharmendraecb Remove Edit buttons on mobile

**Comment by dharmendraecb** [comment]
oky
