### ISSUE TITLE
While Create new company- Industry type value shown in legal structure column

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#57]
### I create new company and fill industry type = mobile, after click save this value shown in legal structure column
![2](https://user-images.githubusercontent.com/46882964/92111685-4a308980-ee0a-11ea-908e-66ded0d1461b.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/93566132-2e9cb580-f9aa-11ea-9acd-226e8ad49176.png)
