### ISSUE TITLE
Chat page-  don't have role, but icon appeared and go to that page

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#570]
### Chat page-  don't have role, but icon appeared and go to that page
![c](https://user-images.githubusercontent.com/46882964/118632337-ef9b5a00-b7ed-11eb-8900-f77bbfeee7cb.png)

**Comment by ajayrajecb** [comment]
### Msg send b ho raha hai , role nhi hai but

**Comment by mitulpanch** [comment]
chat page on hi rahega, just client se chat kar sakta he ke nai wo he

**Comment by mitulpanch** [comment]
staff se chat kar sakta he
