### ISSUE TITLE
Automation- add action screen all time blur or processing, 15 min tk check kiya, same in sai dulu pc

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#573]
### Automation- add action screen all time blur or processing, 15 min tk check kiya, same in sai dulu pc
![2021-05-20_14-46-18](https://user-images.githubusercontent.com/46882964/118953416-69604e80-b97a-11eb-8075-e5ee3c9e81e3.png)

**Comment by mitulpanch** [comment]
getallvouchersubtypes
ka error he


console pe dikha raha he
