### ISSUE TITLE
Auto billing contract control required for year wise.

### ISSUE THREAD

**Issue by sureshsirvi** [Fammeo/EasyCloudBooks#579]
We need
1. selection for current year contract or Continious contract billing..
2. ECB Compnay name on Print screen ..
[https://www.berrycast.com/conversations/362c56ad-67cf-5b9b-9013-b39371e93e95](url)

**Comment by ajayrajecb** [comment]
https://www.berrycast.com/conversations/362c56ad-67cf-5b9b-9013-b39371e93e95
