### ISSUE TITLE
company page- multiple select or single select, requirement

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#58]
### in company page we select multiple companies or select single company checkbox, options appeared, but when we remove tick , options should be hide, but it didn't hide after deselect

![2020-09-03_22-40-27](https://user-images.githubusercontent.com/46882964/92146167-f12b1a80-ee36-11ea-9feb-b42048893bb6.png)

**Comment by ajayrajecb** [comment]
In live easycloudbooks, it works perfectly

**Comment by dharmendraecb** [comment]
https://ac-115.easycloudbooks.in/user/Company

**Comment by ajayrajecb** [comment]
> https://ac-115.easycloudbooks.in/user/Company

12 din pehle jb dala tha tb ho raha tha, contact pe jaisa hai waisa karna hai, if possible
