### ISSUE TITLE
Rename button name  Change as "Change Tag"

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#580]
### Rename button name  Change as "Change Tag" clients ko button nhi mil raha , so please Button name should be Change Tag
![2021-05-28_12-13-18](https://user-images.githubusercontent.com/46882964/119944241-a5666580-bfb1-11eb-8981-d0a2523496f4.png)

**Comment by mitulpanch** [comment]
Pura likhne ki jagah nai he
