### ISSUE TITLE
Company Page- Add license pop up text correction related

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#59]
### when click on add license popup appear, there is no check box for need reminder, so please remove this text from there.
![2020-09-03_22-47-27](https://user-images.githubusercontent.com/46882964/92146776-d311ea00-ee37-11ea-9901-7ebbd9a4b5e8.png)

**Comment by jayshah6777** [comment]
![Uploading image.png…]()
