### ISSUE TITLE
Broadcast page is not working without preview

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#599]
### Broadcast page is not working without preview, send now button is not working.
![2021-06-17_16-28-59](https://user-images.githubusercontent.com/46882964/122384743-9c9df980-cf89-11eb-83fe-430ff0b63a91.png)

### Preview field me type nhi hona chahiye, but when user type in preview box, its works

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/122894968-510e9580-d365-11eb-93a6-5c39fee1cea3.png)
