### ISSUE TITLE
Client want to hide email address form team page

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/EasyCloudBooks#621]
![Snag_258c194](https://user-images.githubusercontent.com/77724114/126595821-bd7af8bd-7c9e-4d73-a9a0-35a20be8a3e3.png)

**Comment by Avinash-ecb** [comment]
After discussion with mitul sir 
- Add one setting in theme edit contact page for hide/show all email of staff

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/126773880-a2a2eb3e-113d-4bba-82f0-404f46aac752.png)

Added option for hide/show email address of team member in contact page
- indian ocean is left, all themes are completed
