### ISSUE TITLE
When we choose Custom field exits then it shows static and dynamic option

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/EasyCloudBooks#626]
<img width="960" alt="2021-07-30" src="https://user-images.githubusercontent.com/77724114/127609890-191504ce-72c7-431a-87e2-710a211ef4bd.png">

**Comment by mitulpanch** [comment]
Isme khali static option ayega

**Comment by ajayrajecb** [comment]
### abhi bhi aa raha hai dynamic option
![2021-08-02_21-58-31](https://user-images.githubusercontent.com/46882964/127893978-c1343596-9f40-4c0b-8b00-cefd3da7fa9a.png)

**Comment by ajayrajecb** [comment]
![2021-08-02_22-07-28](https://user-images.githubusercontent.com/46882964/127895024-b35b0a85-0c1e-4051-9241-b336520d259d.png)
