### ISSUE TITLE
please change design of button

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/EasyCloudBooks#640]
![Snag_1568d3c](https://user-images.githubusercontent.com/77724114/130051076-96516dbb-c50a-420d-97e0-fd8b2d67cc58.png)
![Snag_156980a](https://user-images.githubusercontent.com/77724114/130051084-f14e479f-7f1b-4109-bd81-17aa59aac53a.png)

**Comment by J-odion** [comment]
Hi
Any update on this task as well as other open issues?
I was hoping to join the train and fix some of the issues raised starting from the issues labeled Design-change.
What do you say?
