### ISSUE TITLE
Get details off but sometimes click on icon its shows and not close then

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#643]
### Get details off but sometimes click on icon its shows and not close then
![2021-08-19_16-41-14](https://user-images.githubusercontent.com/46882964/130059308-dcf94963-fe78-439c-afbc-0406ccc281b1.png)
### icon pe click kr k drag karne pe hota hai ye issue

**Comment by dharmendraecb** [comment]
1. remove popover design 
 2. new design flow process  updated.
