### ISSUE TITLE
Remove ecb prefix in event name if possible

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#644]
### Is this possible to remove ecb prefix in event name?
![2021-08-19_17-50-18](https://user-images.githubusercontent.com/46882964/130067959-b5c876f9-ba43-40b8-9618-7c4e9532ca8d.png)

**Comment by mitulpanch** [comment]
Not possible

**Comment by mitulpanch** [comment]
@dharmendraecb change diaplay name

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/130316213-44bb31c9-a5a4-4528-9d89-52cb378f757d.png)
