### ISSUE TITLE
Filter Required on Company Page and Contact page

### ISSUE THREAD

**Issue by sureshsirvi** [Fammeo/EasyCloudBooks#666]
We are required daily to filter companies of contacts ... curretly we are using Query filter ... but it is always required to go to query for each contact filter frequently ....

We need separate Contact wise filter for company page...

and

on Contact page ... Company wise filter.

![image](https://user-images.githubusercontent.com/46813198/135790915-339ac677-1da0-45f7-b755-94347a8d8c5f.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/138032830-1afc39e0-ea06-405c-9e31-a8fa174115a6.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/138032860-b9c275c6-d53f-45ed-9dde-ffb6ee2f8951.png)
