### ISSUE TITLE
Add time on automatically name on scheduler

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/EasyCloudBooks#667]
When we create new scheduler then it should get time also , because it is difficult in process to know whish scheduler is working 
![1](https://user-images.githubusercontent.com/77724114/135982426-686960ed-9b31-4521-92f8-33ddd9dee08b.png)

**Comment by mitulpanch** [comment]
@Vinod Pahilwani ***@***.***>  sir aapko ye chahiye? Aapne hi
last time hatvaya tha
