### ISSUE TITLE
Project manager profile photo Should be show  on mouse hover

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/EasyCloudBooks#67]
![image](https://user-images.githubusercontent.com/58812881/92372632-dc8ea100-f11a-11ea-8086-c64db6bfb0a2.png)

project page
should be show project manager profile photo on mouse hover

**Comment by ajayrajecb** [comment]
![2021-02-22_12-29-44](https://user-images.githubusercontent.com/46882964/108673468-bbbfd980-7509-11eb-83d3-ba830228110b.png)

mr robin photo still not shown

**Comment by mitulpanch** [comment]
dusre sab ka aa raha he?

**Comment by mitulpanch** [comment]
mr robin ka photo firse upload karne pe ho jayega

**Comment by mitulpanch** [comment]
on fammeo

**Comment by ajayrajecb** [comment]
after change image, its working
