### ISSUE TITLE
Errors and changes in Data settings page

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/EasyCloudBooks#688]
### General changes
1. Need update button on the header 
2. Then add-website page here so user can change the website theme over here
3. then add team on this page ( on behalf of Vinod sir)
4. then add domain over here on the header so user can go to the website directly 
5. change name data settings to website settings( on behalf of Vinod sir )
### Error in software and industry experience
1. Can not change a new image to added experience
2. can not change the name of an already added 
3. When we upload the image then it shows please wait- > it should not be clickable
4. Experience name should start with a capital letter
### Error in Award
1. When we edit added award then it changes the image automatically and adds a new google image
2. the First letter should be capital
### Remove industry
there is no need for this industry in user section because we already added industry experience and this industry has no value right now
### Error in affiliations
1. the first letter should be capital
2. when we edit the added affiliations then it changes the image automatically and adds a new google image
### Error in Testimonials
1. when we edit the added testimonials then it changes the image automatically and adds a new google image
2. the first letter should be capital
### error in blog
1. Remove button is not working
2. need scroll in a short description

**Comment by Avinash-ecb** [comment]
After discuss with @mitulpanch It is before 3 months old and not related
