### ISSUE TITLE
Tag size should be 50 characters in company

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#719]
**Describe the bug**
When we are adding tags in company it allowed to add more than 50 characters

**To Reproduce**
1. Go to https://ac-74.s1.easycloudbooks.com/user/company/list#
2. Click on any company in company list it will open company view page
3. Click on three dots it will open company edit page
4. Scroll down to tags and add tags (how much you want more than 50)
5. See error

**Expected behavior**
Tags length should be 50 characters or ui issue 

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/158118290-0bf0d8ea-1855-4599-8c3f-76349701f428.png)

**Describe the bug**
When we are adding tags in contact it allowed to add more than 50 characters

**To Reproduce**
1. Go to https://ac-74.s1.easycloudbooks.com/user/contact/list#
2. Click on any contact in the contact list it will open the contact view page
3. Click on three dots it will open the contact edit page
4. Scroll down to tags and add tags (how much you want more than 50)
5. See error

**Expected behavior**
Tags length should be 50 characters or UI issue 

**Screenshots**

![bug Tag](https://user-images.githubusercontent.com/77724114/158120141-134f45fd-9350-44c9-a5f4-78e93dfa7468.png)

**Comment by dharmendraecb** [comment]
tag char length 49
