### ISSUE TITLE
When create license with more character it shows error

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#725]
**Describe the bug**
When we add more characters (300 char) in name, number, issue authority, applicable law and note  it shows system error 

**To Reproduce**
1. Go to https://ac-74.s1.easycloudbooks.com/user/company/list#
2. Click on any company in company list it will display company view page
3. click on three dots and select license/registration option it will open license page click on create license button
4. Add more characters (300 char) in name, number, issue authority, applicable law and note 
5. See error

**Expected behavior**
It shows validation or character length message

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/158311491-52b8caba-7c67-47be-a701-4809f5bcfeb4.png)

**Comment by dharmendraecb** [comment]
Registration Name char length 50
Registration Number char length 50
Registration Issuing char length 50
Applicable Law char length 50
Note char length 200
