### ISSUE TITLE
UI Issue in company list table

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#730]
**Describe the bug**
- There is no any tool tip on service count so user can know that he can add service from here.
- The same things in change manager so user don't get idea about he can change manager
- The same things in auto billings

**Expected behavior**
There should be tool tip on hover so user can understand what action can he do on that place

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/158517371-86cb20d2-2b03-4964-af30-9e5ebcff3857.png)

**Comment by dharmendraecb** [comment]
change manager title not possible  => Already Title bind 

![image](https://user-images.githubusercontent.com/46588108/158750863-9707cdd0-4db8-46b4-bb8a-f0feb20cd705.png)
