### ISSUE TITLE
Count Issue in adding service in company

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#733]
**Describe the bug**
When we are adding service to company
- click on service count on company list it will open selected service for company page
- click on +service button it will open add service page, select some service
- filter that records with filter until that selected record is not visible
- Select some other records again filter and again select some other records
Now you don't have idea how many records has selected

**Expected behavior**
- there should be show some count how many service are adding 
- or if we filter records in add page all checkbox should uncheck

**Screenshots**

![image](https://user-images.githubusercontent.com/46588125/158530034-0f8293f7-81fc-4753-8984-ebdebf81ac75.png)

![image](https://user-images.githubusercontent.com/46588125/158530196-d07a7248-d2ad-425e-a8e6-1ce380d04a6a.png)

![image](https://user-images.githubusercontent.com/46588125/158531059-d05fc839-1a69-443c-b551-7cb85fbfad42.png)

**Comment by dharmendraecb** [comment]
Selected Count Removed @vinpahilwani 
and Design Change Check Again

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/5b56bf71-4f94-56ad-8cfb-ecb2c007055c
