### ISSUE TITLE
Issue in calculate annual fees

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#736]
**Describe the bug**
- When remove characters or number from service annual price then total annual fees getting zero
- When we add 9999999998 to a service it takes in total 1000c

**Expected behavior**
- It should get zero in that service price and calculate other fees
- It should calculate correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/158554729-5391705f-cc3b-430c-9753-40cdbf910f84.png)

![image](https://user-images.githubusercontent.com/46588125/158558750-9c70fc1c-abbe-40bc-a4d1-f443b2ba9f8c.png)

**Comment by dharmendraecb** [comment]
When we add 9999999998 to a service it takes in total 1000c this issue Plugin Issue
