### ISSUE TITLE
Create company page Issues

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#743]
**Describe the bug**
- Unique Id showing with space or without space

- Industry type placeholder should be "Provide company industry type"

- In legal structure textbox placeholder should be "Provide company legal structure"

- showing limit 1000 characters in note but taking 200 characters

- Auto generate image issue in company filter 

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/158751009-825e126e-d686-4cd2-a024-e7445f9787b2.png)

![image](https://user-images.githubusercontent.com/46588125/158751196-3bc6a569-9285-45ce-9346-29bd7ef1cdca.png)

![image](https://user-images.githubusercontent.com/46588125/158751331-27113d33-7720-4282-a955-4d31bd29fbf1.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/159654937-f4864b21-5edb-4c94-8e8f-3eb7035d17f6.png)

**Comment by dharmendraecb** [comment]
Note length 1000 char.

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/31a92d97-ee2d-5970-b245-7b4c7717730e

Note taking 200 characters

**Comment by dharmendraecb** [comment]
Note 500 characters company and contact

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/6a4cf188-83b0-5bb8-a353-8391c959cf7f
