### ISSUE TITLE
staff page Block function and staff shift work function is not working properly

### ISSUE THREAD

**Issue by harshitaexpcon** [Fammeo/EasyCloudBooks#75]
![image](https://user-images.githubusercontent.com/66782635/93070067-0b1cf680-f69c-11ea-8f74-c1eacff6eb78.png)

1) block button is not working

2) shifting work to other staff is not working properly

### shift work me option aa nahi raha
name selection nahi ho raha 
![sw](https://user-images.githubusercontent.com/46882964/93081794-73280880-f6ad-11ea-9fb2-c696c9f8b6b5.png)

### block kiya maine staff ko toh uske bad option change hoke unblock hona chahiye na?
![s11](https://user-images.githubusercontent.com/46882964/93081835-820ebb00-f6ad-11ea-9963-582beaebac17.png)

**Comment by harshitaexpcon** [comment]
![image](https://user-images.githubusercontent.com/66782635/93201800-4dfbce80-f76f-11ea-8f81-e20c75d1955d.png)
 block work done

shifting work pending

**Comment by dharmendraecb** [comment]
live (easycloudbooks) ka screen  short send karo na

**Comment by dharmendraecb** [comment]
shifting work chalu he

**Comment by ajayrajecb** [comment]
> live (easycloudbooks) ka screen short send karo na

![Uploading 2020-09-23_22-20-33.png…]()
