### ISSUE TITLE
Show correct validation message in contact page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#750]
**Describe the bug**
When create a contact adding 30 characters in first name and last name error message is "Please provide correct name"

**Expected behavior**
This message should specify the error so client can know his mistake. Message should be understandable by client

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/159209591-d20bf6ab-d186-4757-8d22-5546abb2a57c.png)

**Comment by dharmendraecb** [comment]
name char length 29
