### ISSUE TITLE
Display verified tick in email in contact list

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#759]
**Describe the bug**
- Verify tick of email not available in contact
- also give space between green tick in view contact page

**Expected behavior**
Display verify tick on email in contact list

**Screenshots**

![image](https://user-images.githubusercontent.com/46588125/159414318-294816c3-b6da-4b65-a1e0-7f8b07d0286b.png)
![image](https://user-images.githubusercontent.com/46588125/159414363-d6e84fdd-130d-408b-bcab-b3af1800f3c0.png)

**Comment by dharmendraecb** [comment]
email length vadhare hova thi tick hide che.
jayare hover karva thi title ma avche
![Untitled](https://user-images.githubusercontent.com/46588108/160779252-d20e032f-0134-4215-bfef-00d57eb150ba.png)

**Comment by Avinash-ecb** [comment]
Increase email column width by @mitulpanch

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/04b8bafc-eb49-5018-a682-7be53ed0909e
