### ISSUE TITLE
UI Issue in Staff page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#766]
**Describe the bug**
- When check header checkbox of staff table and click the any staff row it opens staff view, after closing staff view  it not uncheck header checkbox.
- When check header checkbox of staff table and click on create new staff it open create page, after closing the page  it not uncheck header checkbox.
- "EasyCloudBooks will send this Message in Invitation Email" this message should near message label

**Expected behavior**
- It should uncheck all checkbox
- show message on correct position

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/159620064-7337bd28-4487-4c83-b390-769d41fb6b02.png)
![image](https://user-images.githubusercontent.com/46588125/159843129-726d145c-8df4-4003-97bf-466921a1d7f8.png)

**Comment by dharmendraecb** [comment]
Check Box issue Fixed but Message (that's not a right way) Invalid
