### ISSUE TITLE
Some UI Issue in Project Page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#775]
**Describe the bug**
- Projects | List  should be  Project | List
- Change project tab name according to project page
- Company name column should have some space like company page
- In pending status dotted line should not see on number label
- What is the use of select view option in list view filter
- Add a pointer cursor on company image on view project page

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/159858293-940b4eaf-e158-4ae0-9887-a7e40ceaa5c0.png)
![image](https://user-images.githubusercontent.com/46588125/160051733-a324aaa4-b370-47ca-8750-a27b7fce4798.png)

**Comment by dharmendraecb** [comment]
Border and background color theme color not a changeable this issue  can't fixed
![image](https://user-images.githubusercontent.com/46588108/160823864-bb7ce9dc-0506-461d-b5d8-d93b7335388d.png)
