### ISSUE TITLE
Issue in save description in change info in project page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#779]
**Describe the bug**
When we adding more characters in description field in change info page their is database issue "An error occurred while updating the entries. See the inner exception for details."

**Expected behavior**
There should be a validation

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/159878005-a0c5746c-3da0-4816-970c-a282df215d5f.png)

**Comment by dharmendraecb** [comment]
description field  400 char allow

**Comment by Avinash-ecb** [comment]
when we adding more characters in title it is showing database error

https://www.berrycast.com/conversations/a0a8e3a9-9c2a-507e-a3ed-c42caffeb0d6

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/65d6a559-5de1-5775-8e52-16f0db00bbc9
