### ISSUE TITLE
Some issue in create Todo in project page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#786]
**Describe the bug**
- There should be red star on title field
- When adding more characters there is database error

**Expected behavior**
- There should be a red star so client knows required field 
- Add characters limit 

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/160063378-156ec213-de9a-4ca9-ac33-db5d3c84c19e.png)

**Comment by dharmendraecb** [comment]
title char 200
description char 450

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/5a7b851e-9558-536f-aac8-2861fa18222b
