### ISSUE TITLE
Some issue in start time tracker in project list

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#789]
**Describe the bug**
- set timer button name should be start timer
- close button name should be cancel
- project box should be a project name 
- current status label should be a company name

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/160070513-6418b30c-4ba0-4407-8db3-dda8d9bd9772.png)

**Comment by dharmendraecb** [comment]
compare old module and any small  change approval by **@vinpahilwani**  **@mitulpanch**
