### ISSUE TITLE
Staff page UI Issue By sir

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#79]
### Yeh sare option changeable hai par is change karne par jo box khulta hai woh alag alag hai - jo achha nahi lag raha
![2020-09-14 (1)22](https://user-images.githubusercontent.com/46882964/93081383-cfd6f380-f6ac-11ea-9c82-c2cb1b37563c.png)
![2020-09-14](https://user-images.githubusercontent.com/46882964/93081390-d06f8a00-f6ac-11ea-8855-1b0b83453f3d.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/93569004-994ff000-f9ae-11ea-9549-8a7dbedaaebe.png)

![image](https://user-images.githubusercontent.com/58812881/93569031-a1a82b00-f9ae-11ea-9503-3613b80da7b2.png)

![image](https://user-images.githubusercontent.com/58812881/93569047-a967cf80-f9ae-11ea-962f-3ba2c6791796.png)
