### ISSUE TITLE
Some issue in project page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#790]
**Describe the bug**
- There should be a client note in bracket if client not is selected in status note 
- There should be a option of applicable and not application in todo in project

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/160078589-fb544b81-4644-481a-b0f7-dfdf3094c22e.png)
![image](https://user-images.githubusercontent.com/46588125/160078649-2c6e0775-d6e9-4cad-bc7b-c26c953015ca.png)
![image](https://user-images.githubusercontent.com/46588125/160078896-1aaeb18f-8ae9-4096-b956-47e3e87fbeab.png)

**Comment by dharmendraecb** [comment]
not application in todo in project remove functionality

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/f8819461-b328-53e1-8083-1e4c7dc55156
