### ISSUE TITLE
Issue in create query page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#791]
**Describe the bug**
- Required field red star not  available in title label
- There is no validation available in textbox for more characters (database error)
- There is not redirect to discussion page available

**Expected behavior**
- Give red start for required field
- Give characters validation in input fields
- Give redirect option to go on discussion page

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/160080309-f03082f3-b889-4a86-8082-6780e263e913.png)
![image](https://user-images.githubusercontent.com/46588125/160080543-0a59ff58-1dc8-4c4f-a6db-fa16c02f471f.png)

**Comment by dharmendraecb** [comment]
Give redirect option to go on discussion page **on Hold**
