### ISSUE TITLE
Issue in add custom field

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#794]
**Describe the bug**
- when we add more than 15 in number it gets 999999999999999
- Issue adding year before 1999
- project custom fields contains below boxes but not look like this

**Expected behavior**
- Allow only 15 character length
- Allow year before 1999 in year date field
- add json, turnover details etc box in project custom field box

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/160098560-5abe6833-35a0-459d-8853-ef8660d9f537.png)
![image](https://user-images.githubusercontent.com/46588125/160108593-a146cf6d-6779-4b70-9442-3350dcb68141.png)

**Comment by dharmendraecb** [comment]
Project or Company CRF click and show result

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/163513965-1c3ca11b-bf0e-4b32-b07a-8a6429150f10.png)
Can not identify difference between parent box and child box

**Comment by dharmendraecb** [comment]
This Box approve By @vinpahilwani 
and Date issue solved

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/7d3c067e-536d-58e9-8da7-931d7e2bd24f
