### ISSUE TITLE
Issue in create invoice in transaction page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#803]
**Describe the bug**
- It is allowed to get future date up to 1 year
- Amount is not calculated according to quantity
- Service text box should be disabled

**Expected behavior**
- It should not allowed to future date
- Quantity should also get multiple by amount
- Service text box should be disabled

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/160382308-b0b5a1cf-af46-4bd9-8199-20d46fe29947.png)
![image](https://user-images.githubusercontent.com/46588125/160383004-c2b1a8d4-52de-4da4-b2de-76ac52e90b07.png)

**Comment by dharmendraecb** [comment]
Service Amount Not issue
