### ISSUE TITLE
Issue in printing invoice in transaction page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#808]
**Describe the bug**
- Quantity is not calculated in total amount
- When showing amount calculation there is some text in capital and some are camel case  
- When we print there is one extra white page in printing 
- Pay button not working

 **Screenshots**
![image](https://user-images.githubusercontent.com/46588125/160539831-66d865fa-d805-4feb-bc31-1034b858a43d.png)
![image](https://user-images.githubusercontent.com/46588125/160539904-1ea5d515-786a-4b1e-b849-fb6b014a0101.png)

**Comment by dharmendraecb** [comment]
text in capital and some are camel case in client Entry
