### ISSUE TITLE
Issue while print ledger from view invoice page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#809]
**Describe the bug**
- When we print there is one more extra white page in printing
- There is not any payment button but in comment it shows that "You can Directly pay Here through Pay Button above"

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/160541786-9955bbcd-3283-4e5e-b800-a6ff8ba67a59.png)
![image](https://user-images.githubusercontent.com/46588125/160541877-f58fdeed-dea6-4b13-93a1-3c6a77ecdd3d.png)

**Comment by dharmendraecb** [comment]
header and footer text provide Defaults. but client change any time in setting
