### ISSUE TITLE
Service page - max note span related issue  by sir

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#81]
### Maximum Note Span - change this to Status Update, and 7 jo dikh raha hai usko 7 days aisa dikhao
![ns](https://user-images.githubusercontent.com/46882964/93082100-edf12380-f6ad-11ea-8c00-ad64ee5d7546.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/93567151-d797e000-f9ab-11ea-9363-a6edd10ce40c.png)
