### ISSUE TITLE
Issue while print payment in transaction page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#815]
**Describe the bug**
- Can not identify payment mode
- name should be a payment only 
- There is one extra white page in printing

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/160552678-eb1d47a6-89b8-441a-9b11-a811520d1de4.png)
![image](https://user-images.githubusercontent.com/46588125/160552754-3a075c6d-0f16-4677-a6d0-bbc0cf96b2a6.png)

**Comment by dharmendraecb** [comment]
provide transaction print link

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/7dc40737-d825-57c7-9683-69a18fb0c1b3
