### ISSUE TITLE
Issue in printing multiple transactions in transaction page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#816]
**Describe the bug**
When selecting multiple transaction from list and click on print button it shows first debit transaction in print

**Expected behavior**
It should show message for select single record  

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/160565464-7f5a5096-9a9f-412b-ae5c-bcc5b74de48e.png)
![image](https://user-images.githubusercontent.com/46588125/160566045-bd063d2e-c0a8-415d-8cfa-d8387dcbfafe.png)

**Comment by dharmendraecb** [comment]
Scrolling

**Comment by Avinash-ecb** [comment]
I can not understand, please explain in details
