### ISSUE TITLE
Date is not updating in auto billing in company page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#821]
**Describe the bug**
When we update auto billing details date is not updating 

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/160755770-6144419a-b99c-4624-8988-50863325b5c1.png)
![image](https://user-images.githubusercontent.com/46588125/160755831-bb833489-5ec1-475a-ad8f-5a9f7625f6d8.png)

**Comment by dharmendraecb** [comment]
on hold by @mitulpanch

**Comment by mitulpanch** [comment]
not relevant
