### ISSUE TITLE
Service page- after edit error occurs

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#83]
### edit accounting service, add new duedate and want to save then msg apperes 
![ser](https://user-images.githubusercontent.com/46882964/93083445-3e698080-f6b0-11ea-815f-900d7698634c.png)

**Comment by ajayrajecb** [comment]
### Create new service also is not working now

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/93566995-8a1b7300-f9ab-11ea-99f4-0a7b4c9abe7f.png)
