### ISSUE TITLE
Design issue in payment page in transaction

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#830]
**Describe the bug**
- Header name should be in different color and give some padding

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/160814748-6c9fc332-35b9-4c36-8751-576261dda9f3.png)

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/161057466-0bb90762-268f-4f87-a4d7-d833535d4811.png)
