### ISSUE TITLE
Issue in date picker and display date in service page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#832]
**Describe the bug**
- Date format in setting: Saturday, 01 January 2022
- While saving date date displayed invalid date 
- After edit date picker not working correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/160982791-03dcdb40-0e32-4635-b344-49cf41e089a4.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/162412746-21e3d55e-c5d4-47be-b082-5bec340de7bb.png)

**Comment by dharmendraecb** [comment]
recheck 
remove all dudate. create new
