### ISSUE TITLE
Some issues by Vinod sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#843]
**Describe the bug**
- inoice transaction pe click karne par side panel me ledger option aa raha hai par receipt and discount transaction pe click pe ledger nahi aa rha
- https://ac-74.s1.easycloudbooks.com/TransactionPrint?crids=HAMzzG-7tEqpwQbiO4JlmA period ko top pe ledger ke neeche centre pe rakho
- print date ko neeche rakho and woh bhi ek hi line pe
- ledger ko A4 me print leke dekho mere hisaab se problem aayega

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/161245429-17024309-4259-45e8-b9df-8c1991ea03d5.png)
![image](https://user-images.githubusercontent.com/46588125/161245840-c0022d0e-4ce9-4e7a-839f-cde7f0177057.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/163516116-7fde5ced-bac2-4bfb-9941-78b426306dcc.png)
![image](https://user-images.githubusercontent.com/46588125/163516149-f90fb19b-52da-44d1-8467-6deea157f338.png)
There is not any ledger showing

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/163668728-6c62abd5-cd71-4773-beef-752093274c39.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/163759597-0997f4ed-07c1-4615-bb16-66a65657adfd.png)
![image](https://user-images.githubusercontent.com/46588125/163759623-45d7f8d8-cecc-451c-8a12-538654ce6676.png)

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/e2157951-2c2a-51b4-b7f1-16b01d122df8
