### ISSUE TITLE
Issue while edit service image in service page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#845]
**Describe the bug**
- When edit service image it does not display in image uploader, showing default image

**Expected behavior**
- It should show service image which is uploaded previously
- save button does not have tick icon **check all page for save button tick issue**

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/161368357-cad089a0-4b21-4960-b273-33a3d6d9a99c.png)

![image](https://user-images.githubusercontent.com/46588125/161368737-faae9ed7-9efd-469d-a39d-cd8ea36a519e.png)

**Comment by dharmendraecb** [comment]
provide Images all type issues @Avinash-ecb

**Comment by dharmendraecb** [comment]
Images Load Failed Auto Default Images Load (All Page Cropper Issue Solved)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/164690951-12a69f26-a793-4355-96e9-8a1cd81b4721.png)

- save button is not working after edit service
- download button is not working

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/d48e0927-3eac-593d-8a77-6f2153ec8ebf
