### ISSUE TITLE
Issue while adding description in service page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#847]
**Describe the bug**
- When adding more characters in description then  database error showing

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/161374408-b3c59e36-cbe4-46c0-9895-996b9ac69e28.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/163517208-6fdc8461-e55b-4a2e-a392-cd47a29177f3.png)

**Comment by dharmendraecb** [comment]
maxlength 500

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/163759415-605ebae7-4861-4c86-a331-770066619220.png)
