### ISSUE TITLE
Date picker issue in due dates in service page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#852]
**Describe the bug**
- date picker is not display correctly while change date
- When create due dates it shows success message but not display in list
**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/161474540-ce672134-6a82-45e1-b1d7-efab6d0d3fc2.png)
![image](https://user-images.githubusercontent.com/46588125/161536675-081e1a54-c0bf-400a-b03a-ba264df9a328.png)

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/adcbe958-0aba-54a3-afd4-81e7b18c753b

apply button is not display

**Comment by dharmendraecb** [comment]
Date picker one click close

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/51596d99-d462-5617-8bca-93a761eddad9
