### ISSUE TITLE
Issue in FAQs in service page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#859]
**Describe the bug**
- title should be Question and Description should be Answer
- save & next button not available
- default sort order should be 1
- show order in list because if there is more record then we can not identify order
- show red star on sort order & show correct message for required field
- Description shows 2000 characters limit but accept only 1988 characters
- characters limit showing wrong message

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/161522801-2a16ac4f-a8ab-4d3b-85ab-4b3757892609.png)
![image](https://user-images.githubusercontent.com/46588125/161522953-82398041-c950-483c-8968-d6475dd48d41.png)
![image](https://user-images.githubusercontent.com/46588125/161523006-12c42df2-8385-483f-9e81-c6b5779efc84.png)

**Comment by Avinash-ecb** [comment]
- title should be Question and Description should be Answer
- save & next button not available
- show order in list because if there is more record then we can not identify order
- validation shows 2000 characters limit but accept only 1988 characters

**Comment by dharmendraecb** [comment]
save & next button remove

**Comment by dharmendraecb** [comment]
this Design Already Approve  @vinpahilwani

**Comment by dharmendraecb** [comment]
characters limit 2000 with html characters
