### ISSUE TITLE
Company - Combine import related(work task page)

### ISSUE THREAD

**Issue by ajayrajecb** [Fammeo/EasyCloudBooks#86]
###1. when click on task , only filter company-contact-import dikhna chaiye, click pe sare task dikh rahe hain (ecb live pe hota hai perfectly)

![2020-09-16_14-31-36](https://user-images.githubusercontent.com/46882964/93316059-5f091600-f829-11ea-943a-6610f54ee526.png)

### 2. work task expand button not working
![2020-09-16_14-32-21](https://user-images.githubusercontent.com/46882964/93316282-a099c100-f829-11ea-9669-019b265a9b5d.png)

### 3. in work task page on expand company-contact-import Report button hai jo documents pe le jata hai. fammeo pe nhi aa raha work task expand pe
![2020-09-16_14-40-40](https://user-images.githubusercontent.com/46882964/93317103-aba12100-f82a-11ea-9793-841acb9824e0.png)

**Comment by dharmendraecb** [comment]
filter problem solve and report button click URL wrong  he @mitulpanch 

![Uploading image.png…]()
