### ISSUE TITLE
some correction on company page by Vinod sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#867]
**Describe the bug**
- billing pattern nahi Billing Dates karna

**Barrycast video**
https://www.berrycast.com/conversations/109a002b-eb7e-53c8-b7b3-eb04e7501d1b

https://www.berrycast.com/conversations/af9f4119-52cb-5ce2-b0e6-41b000544594

**Comment by dharmendraecb** [comment]
some correction fixed and correction correction can't fixed
