### ISSUE TITLE
Show some default image if there is not image available in software experience setting

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#893]
**Describe the bug**
Show some default image if there is not image available in software experience setting

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/162565192-8c6edb41-7ee2-472d-b6ec-80eec56b8cd8.png)

**Comment by dharmendraecb** [comment]
Update Images in Admin Company (Image's Blank)*
