### ISSUE TITLE
Issue in award page in setting

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#895]
**Describe the bug**
- award is accepting 0000 as a year
- when clear award it clears all the texbox
**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/162566984-0706e910-0a30-4815-a865-ae4e87f4fe05.png)
![image](https://user-images.githubusercontent.com/46588125/162567818-5e942407-6a3e-4571-a42f-f6b7ffe46814.png)
![image](https://user-images.githubusercontent.com/46588125/162568215-61b188ec-2a56-48b0-9259-d165524689f0.png)

**Comment by dharmendraecb** [comment]
no any required validation in Year field
