### ISSUE TITLE
After shorting design disturb on staff page 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/EasyCloudBooks#90]
![image](https://user-images.githubusercontent.com/58812881/93582024-898cd780-f9bf-11ea-96c4-534b31304154.png)

**Comment by ajayrajecb** [comment]
![2021-02-02_12-50-48](https://user-images.githubusercontent.com/46882964/106565882-80a73780-6555-11eb-8f7e-b7695db8754b.png)
