### ISSUE TITLE
Info button is not working in query builder page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#904]
**Describe the bug**
- When click on i button it does not show any information 

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/162889269-cd65a4b4-559b-4095-b526-c369daa3a15f.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/163755174-2cbed1b9-5e8a-4122-a363-1c7e1a155008.png)
info button is not working for that

![image](https://user-images.githubusercontent.com/46588125/163755229-0d60fe1c-33bf-4e42-a892-fea274b3c23c.png)

**Comment by dharmendraecb** [comment]
![Uploading image.png…]()

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/167246728-80831a5d-a2a1-4b66-9028-abeb07ae3a90.png)

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/e683c578-5d08-55c6-8105-603e5fecab17
