### ISSUE TITLE
some options are not available in query builder

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#912]
**Describe the bug**
some options are not available on query 

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/162949351-c18440a7-dd3c-49a6-ac06-0dcf9a04afda.png)
![image](https://user-images.githubusercontent.com/46588125/162949435-96205ad6-2d39-4878-a605-fe2d79d8dfa1.png)

**Comment by dharmendraecb** [comment]
Old and new module compare only functionalities.
New module Dropdown Option Different. It's Not bug
 @Avinash-ecb
