### ISSUE TITLE
some changes in project page by Vinod sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#926]
**Describe the bug**
Email Notification --> Send Email
SMS Notification --> Send SMS
Tag Change --> Change Tags
Status Change --> Change Status
Year Change --> Change Period
Projects Remove --> Delete Projects
Data Upload --> Upload Custom Fields
Manager Change --> Change Project Manager

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/163672840-e7a0f71d-20a0-4d45-b76e-3c5e136daecb.png)

**Comment by dharmendraecb** [comment]
project , Company , contact

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/167071103-45b19023-9302-441a-b049-621358ba9a16.png)
