### ISSUE TITLE
some issue in award in setting page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#935]
**Describe the bug**
- images -> image in form and cropper
- image is not showing in cropper
- when we clear name it clears all the data
**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/163796381-8c2ab6a9-75f7-4e8d-89b6-00141aea5d02.png)
![image](https://user-images.githubusercontent.com/46588125/163796438-a505d3a4-6613-48c6-83b4-9261e3915e76.png)

**Comment by dharmendraecb** [comment]
(when we clear name it clears all the data) Not Error

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/e44a4d08-275c-5f49-b21b-533742a484a8
