### ISSUE TITLE
some issue in affiliations in setting page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#936]
**Describe the bug**
- images -> image in form and cropper
- image is not showing in cropper
- when adding year like 200_ then some api error occur
- remove button not working
- when we clear name on edit time it clear image also
**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/163798686-4033fc54-2fbe-4de7-bdf9-4d0ddd00599d.png)
![image](https://user-images.githubusercontent.com/46588125/163798726-2f1ffcf0-7c06-451e-bd32-256016e7b5ab.png)
![image](https://user-images.githubusercontent.com/46588125/163798558-257bbb2b-77d4-4b65-a3c8-a61fabda263b.png)
![image](https://user-images.githubusercontent.com/46588125/163802005-e98b1dc1-d0e6-40fc-9e45-b7d126e469bd.png)

**Comment by dharmendraecb** [comment]
(when we clear name on edit time it clear image also) Not Error

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/988bc638-c2a0-56f5-9ad9-80eadaee79cc
