### ISSUE TITLE
some issue in testimonial in setting page

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#938]
**Describe the bug**
- images -> image in form and cropper
- image is not showing in cropper
- position place should be below name
- if sort is blank then get default value 1
- testimonial is not is sort order in list
- when we edit and clear name then image is autogenerated and old one is removed

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/163917633-ac154cbc-0cf1-498f-9f87-2a7a16a12972.png)
![image](https://user-images.githubusercontent.com/46588125/163917852-5190b594-a882-4c04-97c1-65b8288cd714.png)
![image](https://user-images.githubusercontent.com/46588125/163918483-952d9ff1-7d1a-405b-8e3b-e55945cd64a8.png)

**Comment by dharmendraecb** [comment]
(when we edit and clear name then image is autogenerated and old one is removed) not error

**Comment by dharmendraecb** [comment]
(position place should be below name)  flowing theme UI

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/26b3f562-0666-5401-995c-13e11a78ac48
