### ISSUE TITLE
Some changes discussion in contact page with Vinod sir and Dhramendra

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#941]
**Describe the bug**
- In contact view their should be a plus button after tag, plus button will display only who have role to view contact page
- display tab wise design in contact page like project page also
- tab names are 1) Info 2) Metrics
- Info Tab: 
- Below name there should be first phone number, first email , city and state in single line
- Changes in left cards boxes are 
- add new box projects
- companies-> position
- add new box companies which will open default view
- contract-> contracts
- Metrics Tab:
- Charts

**Comment by mitulpanch** [comment]
not required / already done, currently focused on sales module
