### ISSUE TITLE
Feature request by vinod sir

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#952]
Kindly Provide Filter option 
- Kindly Provide Filter option 1. Service 2. Tag in company
- in contact 1. Tag
- Querybuilder parameter : company relationship manager exist - Yes or No

Require custom fields on team member as well.
service list me ek colum dalna hai recurring non recurring wala

**Post**
https://community.easycloudbooks.com/t/Questions%20or%20Bugs/31e00629-cf8d-4d2c-a414-16ae26c83bae
https://community.easycloudbooks.com/t/Questions%20or%20Bugs/93f39aa9-a000-44bb-b5ac-2fbdfa74d70c
https://community.easycloudbooks.com/t/Questions%20or%20Bugs/f6d6a686-8cb3-4740-9bd2-38233eb069f9

**Comment by Avinash-ecb** [comment]
- Querybuilder parameter : company relationship manager exist - Yes or No
- Require custom fields on team member as well.
This two points are not resolved 
https://www.berrycast.com/conversations/0ed4242f-354a-5a38-aeab-e1760eca5c2c

**Comment by mitulpanch** [comment]
multiple issue in single issue
