### ISSUE TITLE
Service Page Changes - list

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#965]
![Screenshot 2022-04-25 112155](https://user-images.githubusercontent.com/5259926/165028440-beb5d317-4aee-40e8-bbd1-54cfa37d7484.png)
Remove 2 Colums - Add Recurring On /Off and Recurring Scheduler Count - 5 to service list

demand by @vinpahilwani

**Comment by mitulpanch** [comment]
Remove Status Update Column and Group Column

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/166431363-e3e95b36-e549-458c-a8e4-26a36d3a372a.png)
