### ISSUE TITLE
Contact Page - Increase Email Column Width

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#966]
![Screenshot 2022-04-25 112521](https://user-images.githubusercontent.com/5259926/165028793-11d97727-31bd-4b70-bc34-a2b68ff6d049.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/166430909-e11cb14e-6f24-4082-9f26-5d96f00d9887.png)
