### ISSUE TITLE
company ledger page - When delete project from unbilled project unbilled project list not refresh - Deepa Mam

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/EasyCloudBooks#969]
**Describe the bug**
when we are try to delete project from unbilled project then unbilled project list not refresh so deleted project is displayed if we click on that page it shows blank page and shows error you do not have enough previldege

**Screenshots**
![image](https://user-images.githubusercontent.com/46588125/165059873-47814bbc-54e9-4ba9-b65b-048550e411e0.png)
![image](https://user-images.githubusercontent.com/46588125/165059945-9ded0751-466e-4c09-bcc7-6d0b32241150.png)

https://www.berrycast.com/conversations/0f3eb84f-6250-5d90-8e72-4e014104b328

**Comment by mitulpanch** [comment]
#970 
Explains this
