### ISSUE TITLE
Company Name Length 4 or more character

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#972]
@vinpahilwani wants company name length should be 4 or more character

Search length will be min 4 character

**Comment by mitulpanch** [comment]
Import Api ready

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/166429977-82aee186-5b91-409c-b8b1-bb0e1f3bc66e.png)
Message is showing minium 8 characters

**Comment by Avinash-ecb** [comment]
when create company it takes minimum 6 characters not 4 
![image](https://user-images.githubusercontent.com/46588125/168213919-cb6f6cb1-6561-4726-8bde-534dfebdfae0.png)

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/be7d52c0-222f-5cb5-9ff1-b7dea988d3de
