### ISSUE TITLE
Project Page - Status Placeholder is missing in new Theme

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#978]
Project Page - Status Placeholder is missing in new Theme
while Adding new Status
Previous theme had different placeholders for different Status, which was helping User that what to write while changing Status

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/166428119-fa8451cb-55d5-4007-a1ab-bd90bef95ca3.png)
