### ISSUE TITLE
Setting Page - Website Section - General Redesign

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#988]
Website Section needs new General section, to show Analytics , Update Website, Deactivate button with some help

currently it is
![Screenshot 2022-04-28 140527](https://user-images.githubusercontent.com/5259926/165712364-5cea6d5b-31c1-4ec9-b2e9-4e9dfa76b568.png)

Change this

**Comment by dharmendraecb** [comment]
https://www.berrycast.com/conversations/12038ff6-e47d-5005-a14d-a95e7c9f993f
