### ISSUE TITLE
Company Page - Auto Billing - Redesign

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#990]
+Service Button ko niche shift karna he - 
Total Annual Fees ke samne
Total from Service ko right side shift karna he

and
Jo Schedulers ka total he usko schedulers ke samne leke jana he

![Screenshot 2022-04-29 115148](https://user-images.githubusercontent.com/5259926/165894168-d1638ef0-66e0-4dbd-9505-d737eb29469c.jpg)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/168213403-1c2d3f27-e66e-412c-9cd5-5efb1e439f48.png)
