### ISSUE TITLE
Company Page - Auto Billing - Change

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#991]
jub Service na ho to auto matic services pe chala jata he,
uski jagah auto billing ke page pe hi rakhna he, +Service ka button click kar ne te service me jayega

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/168213223-4201ecb9-c335-4a33-b5cd-14fa7d84ec00.png)
