### ISSUE TITLE
Contact Page - Edit Tag - Shift to View Section

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#994]
Remove Tag Edit from Edit section and Add 
Edit Tag to View Section

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/166424144-a6948ac6-6ef7-4b2e-ac2f-a1787b65f788.png)

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/9d1a9220-8f6c-5114-89e5-31db9529f884
