### ISSUE TITLE
Contact Page - New positions

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#996]
Please Add 4 More Positions While Connecting Contact with Company

Group Chairmen
Group CFO
Group CS
Group HR

By client
https://community.easycloudbooks.com/t/Questions%20or%20Bugs/78fa26ea-9655-4263-a2c4-ef9ef008ad12

**Comment by dharmendraecb** [comment]
![image](https://user-images.githubusercontent.com/46588108/166951708-9945b94d-7482-4563-b37b-6e05f201dbd7.png)
![image](https://user-images.githubusercontent.com/46588108/166951753-8a255c4d-d82c-4b19-9c8f-f28a64382091.png)

**Comment by Avinash-ecb** [comment]
https://www.berrycast.com/conversations/316ebf74-01f6-5dcb-9e1a-5dd7a0b9c07c
