### ISSUE TITLE
Service Page - Type options

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/EasyCloudBooks#999]
Add Filter Type Options to Edit mode Type Option

they are Different

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/166422826-6439fdf0-70f4-4732-9d70-a4e31233c3eb.png)
![image](https://user-images.githubusercontent.com/46588125/166422882-851ba81f-5b6c-4f80-9f07-2ccc6849a5e4.png)
